"""Explicit study-validity envelopes and reproducible parameter sweeps."""

from exhaust_plume.validation.claims import (
  BenchmarkDefinition,
  ClaimRole,
  ClaimStatus,
  EvidenceLevel,
  EvidenceLevelSpec,
  MeasurementOperatorSpec,
  OperatorStatus,
  ValidationClaim,
  ValidationRegistry,
)
from exhaust_plume.validation.envelope import (
  DEFAULT_STUDY_VALIDITY_ENVELOPE,
  NozzleCaseAssessment,
  NozzleValidityCase,
  StudyValidityEnvelope,
  default_nozzle_geometries,
  default_pressure_sweep,
  default_validity_cases,
  evaluate_nozzle_case,
  evaluate_validity_matrix,
  write_validity_report_csv,
  write_validity_report_json,
)
from exhaust_plume.validation.fpa_operators import (
  DetectorResponse,
  FPA_PIXEL_DETECTOR_OPERATOR_ID,
  FpaPixelGeometry,
  FpaPixelImage,
  integrate_ray_transfer_to_fpa,
)
from exhaust_plume.validation.measurement_operators import (
  BAND_INTEGRATION_OPERATOR_ID,
  PEAK_NORMALIZATION_OPERATOR_ID,
  SPECTRAL_SAMPLING_OPERATOR_ID,
  BandIntegratedSpectrum,
  PeakNormalizedSpectrum,
  SampledSpectrum,
  integrate_spectral_band_rows,
  peak_normalize_spectral_rows,
  sample_spectral_rows,
)
from exhaust_plume.validation.spectral_comparisons import (
  SpectralShapeComparison,
  compare_peak_normalized_spectral_shape,
)
from exhaust_plume.validation.visual_comparisons import (
  MACH_DISK_FEATURE_OPERATOR_ID,
  MachDiskPressureComparison,
  compare_mach_disk_pressure_relation,
)

__all__ = (
  'BenchmarkDefinition',
  'BandIntegratedSpectrum',
  'BAND_INTEGRATION_OPERATOR_ID',
  'ClaimRole',
  'ClaimStatus',
  'DEFAULT_STUDY_VALIDITY_ENVELOPE',
  'EvidenceLevel',
  'EvidenceLevelSpec',
  'DetectorResponse',
  'FPA_PIXEL_DETECTOR_OPERATOR_ID',
  'FpaPixelGeometry',
  'FpaPixelImage',
  'MeasurementOperatorSpec',
  'MACH_DISK_FEATURE_OPERATOR_ID',
  'MachDiskPressureComparison',
  'NozzleCaseAssessment',
  'NozzleValidityCase',
  'OperatorStatus',
  'PEAK_NORMALIZATION_OPERATOR_ID',
  'PeakNormalizedSpectrum',
  'SPECTRAL_SAMPLING_OPERATOR_ID',
  'SampledSpectrum',
  'SpectralShapeComparison',
  'StudyValidityEnvelope',
  'ValidationClaim',
  'ValidationRegistry',
  'default_nozzle_geometries',
  'default_pressure_sweep',
  'default_validity_cases',
  'evaluate_nozzle_case',
  'evaluate_validity_matrix',
  'integrate_spectral_band_rows',
  'integrate_ray_transfer_to_fpa',
  'compare_peak_normalized_spectral_shape',
  'compare_mach_disk_pressure_relation',
  'peak_normalize_spectral_rows',
  'sample_spectral_rows',
  'write_validity_report_csv',
  'write_validity_report_json',
)
