"""A promotion-safe characteristic-family restart at a detected caustic.

The reflected source strip can reach a point where its old triangular source
family is no longer forward.  This module does not stitch the two one-sided
states together or call that event a shock.  It uses one selected one-sided
state as a new-family anchor, reflects its ``C-`` characteristic to the
symmetry line, and marches an ambient-pressure/tangent ``C+`` boundary.  The
result is an open boundary handoff for a future remesher or shock solver; it
is not a closed upstream field or a chain-cell seed.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from math import isfinite, sqrt

from exhaust_plume.models.moc.boundary import (
  MocFreeBoundaryPointResult,
  solve_ambient_pressure_free_boundary_point,
)
from exhaust_plume.models.moc.chain import (
  MocChainTerminationDecision,
  MocChainTerminationReason,
)
from exhaust_plume.models.moc.primitives import (
  CharacteristicFamily,
  CharacteristicState,
  centerline_characteristic_point,
)
from exhaust_plume.models.moc.source_strip import (
  MocSourceCharacteristicStripResult,
  MocSourceStripCausticShockSeedResult,
  assemble_source_characteristic_strip,
)
from exhaust_plume.models.moc.topology import MocTopologyResult, validate_moc_mesh
from exhaust_plume.models.moc.zone import MocCharacteristicCell

__all__ = (
  'MocCausticFamilyRestartStatus',
  'MocCausticFamilyBandStatus',
  'MocCausticFamilyBandResult',
  'MocCausticFamilyRestartResult',
  'restart_characteristic_family_from_caustic',
)


class MocCausticFamilyRestartStatus(str, Enum):
  """Outcome of the open new-family boundary restart."""

  CONVERGED_OPEN_BOUNDARY = 'converged_open_caustic_family_boundary'
  INVALID_INPUT = 'invalid_input'
  SEED_FAILURE = 'caustic_seed_failure'
  CENTERLINE_FAILURE = 'caustic_restart_centerline_failure'
  AMBIENT_BOUNDARY_FAILURE = 'caustic_restart_ambient_boundary_failure'


class MocCausticFamilyBandStatus(str, Enum):
  """Outcome of the connected two-triangle restart-band assembly."""

  CONVERGED_OPEN_BAND = 'converged_open_caustic_family_band'
  INVALID_INPUT = 'invalid_input'
  GEOMETRY_FAILURE = 'caustic_family_band_geometry_failure'
  TOPOLOGY_FAILURE = 'caustic_family_band_topology_failure'


@dataclass(frozen=True, slots=True)
class MocCausticFamilyBandResult:
  """A connected open band generated by one-sided caustic continuation.

  Each continuation step is split along its incoming C- diagonal into a
  centerline-side triangle and an ambient-boundary-side triangle.  The band
  is a numerical characteristic patch, not a shock cell: its input and output
  edges remain explicit open seams and no downstream entropy jump is implied.
  """

  status: MocCausticFamilyBandStatus
  centerline_states: tuple[CharacteristicState, ...]
  boundary_states: tuple[CharacteristicState, ...]
  cells: tuple[MocCharacteristicCell, ...]
  topology: MocTopologyResult
  input_edge_points_m: tuple[tuple[float, float], ...]
  output_edge_points_m: tuple[tuple[float, float], ...]
  maximum_absolute_geometry_residual_m: float | None
  maximum_absolute_invariant_residual: float | None
  message: str = ''

  @property
  def converged(self) -> bool:
    return self.status is MocCausticFamilyBandStatus.CONVERGED_OPEN_BAND

  @property
  def physical_closure_verified(self) -> bool:
    """The band has no shock or downstream physical termination."""

    return False

  @property
  def chain_promotion_blocked(self) -> bool:
    return True

  def as_chain_termination_decision(self) -> MocChainTerminationDecision:
    """Return the explicit non-physical stop at the open band outlet."""

    if not self.converged:
      raise ValueError(
        'a caustic family chain stop requires a converged open family band'
      )
    return MocChainTerminationDecision(
      physical_termination=False,
      reason=MocChainTerminationReason.OPEN_PHYSICAL_CLOSURE,
      message=(
        'caustic family band is numerically connected but has no fitted shock '
        'or entropy closure for continued-cell promotion'
      ),
      diagnostics={
        'termination_model': 'caustic-family-open-band',
        'cell_count': self.cell_count,
        'step_count': self.step_count,
        'input_edge_points_m': self.input_edge_points_m,
        'output_edge_points_m': self.output_edge_points_m,
        'topology_status': self.topology.status.value,
        'topology_forms_closed_zone': self.topology.forms_closed_zone,
      },
    )

  @property
  def cell_count(self) -> int:
    return len(self.cells)

  @property
  def step_count(self) -> int:
    return max(0, min(len(self.centerline_states), len(self.boundary_states)) - 1)

  def as_report(self) -> dict[str, object]:
    return {
      'status': self.status.value,
      'converged': self.converged,
      'physical_closure_verified': self.physical_closure_verified,
      'chain_promotion_blocked': self.chain_promotion_blocked,
      'band_kind': 'centerline-ambient-two-triangle-characteristic-band',
      'centerline_sample_count': len(self.centerline_states),
      'boundary_sample_count': len(self.boundary_states),
      'step_count': self.step_count,
      'cell_count': self.cell_count,
      'input_edge_points_m': [list(point) for point in self.input_edge_points_m],
      'output_edge_points_m': [list(point) for point in self.output_edge_points_m],
      'topology': {
        'status': self.topology.status.value,
        'connected': self.topology.connected,
        'forms_closed_zone': self.topology.forms_closed_zone,
        'boundary_component_count': self.topology.boundary_component_count,
        'boundary_edge_count': self.topology.boundary_edge_count,
        'nonmanifold_edge_count': self.topology.nonmanifold_edge_count,
      },
      'maximum_absolute_geometry_residual_m': self.maximum_absolute_geometry_residual_m,
      'maximum_absolute_invariant_residual': self.maximum_absolute_invariant_residual,
      'chain_termination_decision': (
        None
        if not self.converged
        else self.as_chain_termination_decision().as_report()
      ),
      'message': self.message,
    }


@dataclass(frozen=True, slots=True)
class MocCausticFamilyRestartResult:
  """An open, one-sided new-family boundary after a characteristic caustic."""

  status: MocCausticFamilyRestartStatus
  seed: MocSourceStripCausticShockSeedResult | None
  anchor_edge_index: int | None
  anchor_point_m: tuple[float, float] | None
  anchor_state: CharacteristicState | None
  centerline_states: tuple[CharacteristicState, ...]
  boundary_states: tuple[CharacteristicState, ...]
  boundary_points_m: tuple[tuple[float, float], ...]
  total_pressure_Pa: float | None
  ambient_pressure_Pa: float | None
  maximum_absolute_pressure_residual: float | None
  maximum_absolute_tangent_residual: float | None
  maximum_absolute_geometry_residual_m: float | None
  minimum_forward_progress_m: float | None
  source_strip: MocSourceCharacteristicStripResult | None
  family_band: MocCausticFamilyBandResult | None = None
  message: str = ''

  @property
  def converged(self) -> bool:
    return self.status is MocCausticFamilyRestartStatus.CONVERGED_OPEN_BOUNDARY

  @property
  def physical_closure_verified(self) -> bool:
    """The restart has no downstream shock or closed characteristic mesh."""

    return False

  @property
  def chain_promotion_blocked(self) -> bool:
    return True

  @property
  def boundary_sample_count(self) -> int:
    return len(self.boundary_states)

  def as_report(self) -> dict[str, object]:
    return {
      'status': self.status.value,
      'converged': self.converged,
      'physical_closure_verified': self.physical_closure_verified,
      'chain_promotion_blocked': self.chain_promotion_blocked,
      'anchor_edge_index': self.anchor_edge_index,
      'anchor_point_m': self.anchor_point_m,
      'anchor_state': (
        None
        if self.anchor_state is None
        else {
          'x_m': self.anchor_state.x_m,
          'y_m': self.anchor_state.y_m,
          'theta_rad': self.anchor_state.theta_rad,
          'mach': self.anchor_state.mach,
          'gamma': self.anchor_state.gamma,
        }
      ),
      'centerline_sample_count': len(self.centerline_states),
      'boundary_sample_count': self.boundary_sample_count,
      'boundary_points_m': [list(point) for point in self.boundary_points_m],
      'total_pressure_Pa': self.total_pressure_Pa,
      'ambient_pressure_Pa': self.ambient_pressure_Pa,
      'maximum_absolute_pressure_residual': self.maximum_absolute_pressure_residual,
      'maximum_absolute_tangent_residual': self.maximum_absolute_tangent_residual,
      'maximum_absolute_geometry_residual_m': self.maximum_absolute_geometry_residual_m,
      'minimum_forward_progress_m': self.minimum_forward_progress_m,
      'source_strip': (
        None
        if self.source_strip is None
        else {
          'status': self.source_strip.status.value,
          'converged': self.source_strip.converged,
          'node_count': self.source_strip.node_count,
          'cell_count': self.source_strip.cell_count,
          'topology_status': self.source_strip.topology.status.value,
          'topology_forms_closed_zone': self.source_strip.topology.forms_closed_zone,
          'topology_nonmanifold_edge_count': self.source_strip.topology.nonmanifold_edge_count,
          'message': self.source_strip.message,
        }
      ),
      'family_band': (
        None if self.family_band is None else self.family_band.as_report()
      ),
      'message': self.message,
    }


def _failure(
  status: MocCausticFamilyRestartStatus,
  *,
  seed: MocSourceStripCausticShockSeedResult | None,
  anchor_edge_index: int | None,
  anchor_point_m: tuple[float, float] | None = None,
  anchor_state: CharacteristicState | None = None,
  centerline_states: tuple[CharacteristicState, ...] = (),
  boundary_states: tuple[CharacteristicState, ...] = (),
  boundary_points_m: tuple[tuple[float, float], ...] = (),
  total_pressure_Pa: float | None = None,
  ambient_pressure_Pa: float | None = None,
  maximum_absolute_pressure_residual: float | None = None,
  maximum_absolute_tangent_residual: float | None = None,
  maximum_absolute_geometry_residual_m: float | None = None,
  minimum_forward_progress_m: float | None = None,
  source_strip: MocSourceCharacteristicStripResult | None = None,
  message: str,
) -> MocCausticFamilyRestartResult:
  return MocCausticFamilyRestartResult(
    status=status,
    seed=seed,
    anchor_edge_index=anchor_edge_index,
    anchor_point_m=anchor_point_m,
    anchor_state=anchor_state,
    centerline_states=centerline_states,
    boundary_states=boundary_states,
    boundary_points_m=boundary_points_m,
    total_pressure_Pa=total_pressure_Pa,
    ambient_pressure_Pa=ambient_pressure_Pa,
    maximum_absolute_pressure_residual=maximum_absolute_pressure_residual,
    maximum_absolute_tangent_residual=maximum_absolute_tangent_residual,
    maximum_absolute_geometry_residual_m=maximum_absolute_geometry_residual_m,
    minimum_forward_progress_m=minimum_forward_progress_m,
    source_strip=source_strip,
    message=message,
  )


def _state_result_reportable(result: MocFreeBoundaryPointResult) -> bool:
  return (
    result.converged
    and result.state is not None
    and result.point_m is not None
  )


def _assemble_open_family_band(
  centerline_states: tuple[CharacteristicState, ...],
  boundary_states: tuple[CharacteristicState, ...],
  *,
  position_tolerance_m: float,
  invariant_tolerance: float,
  seed_geometry_residual_m: float | None,
) -> MocCausticFamilyBandResult:
  """Assemble the connected two-triangle band carried by the restart trace."""

  empty_topology = validate_moc_mesh(())
  input_edge = (
    ((centerline_states[0].x_m, centerline_states[0].y_m),
     (boundary_states[0].x_m, boundary_states[0].y_m))
    if centerline_states and boundary_states
    else ()
  )
  output_edge = (
    ((centerline_states[-1].x_m, centerline_states[-1].y_m),
     (boundary_states[-1].x_m, boundary_states[-1].y_m))
    if centerline_states and boundary_states
    else ()
  )

  def _failure(
    status: MocCausticFamilyBandStatus,
    message: str,
    *,
    cells: tuple[MocCharacteristicCell, ...] = (),
    topology: MocTopologyResult | None = None,
    geometry_residuals: tuple[float, ...] = (),
    invariant_residuals: tuple[float, ...] = (),
  ) -> MocCausticFamilyBandResult:
    geometry_values = tuple(geometry_residuals)
    if seed_geometry_residual_m is not None:
      geometry_values = (*geometry_values, abs(seed_geometry_residual_m))
    return MocCausticFamilyBandResult(
      status=status,
      centerline_states=centerline_states,
      boundary_states=boundary_states,
      cells=cells,
      topology=empty_topology if topology is None else topology,
      input_edge_points_m=input_edge,
      output_edge_points_m=output_edge,
      maximum_absolute_geometry_residual_m=max(geometry_values, default=None),
      maximum_absolute_invariant_residual=max(
        map(abs, invariant_residuals),
        default=None,
      ),
      message=message,
    )

  if len(centerline_states) != len(boundary_states) or len(centerline_states) < 2:
    return _failure(
      MocCausticFamilyBandStatus.INVALID_INPUT,
      'caustic family band requires equal centerline and boundary arrays with at least two samples',
    )
  if any(
    not isinstance(state, CharacteristicState)
    for state in (*centerline_states, *boundary_states)
  ):
    return _failure(
      MocCausticFamilyBandStatus.INVALID_INPUT,
      'caustic family band states must be CharacteristicState values',
    )
  gamma = centerline_states[0].gamma
  if any(
    abs(state.gamma - gamma) > invariant_tolerance
    for state in (*centerline_states, *boundary_states)
  ):
    return _failure(
      MocCausticFamilyBandStatus.INVALID_INPUT,
      'caustic family band states must use one common gamma',
    )
  if any(abs(state.y_m) > position_tolerance_m for state in centerline_states):
    return _failure(
      MocCausticFamilyBandStatus.INVALID_INPUT,
      'caustic family band centerline states must lie on y=0',
    )

  geometry_residuals: list[float] = []
  invariant_residuals: list[float] = []
  cells: list[MocCharacteristicCell] = []
  for index in range(1, len(centerline_states)):
    previous_boundary = boundary_states[index - 1]
    axis_state = centerline_states[index]
    boundary_state = boundary_states[index]
    axis_result = centerline_characteristic_point(
      previous_boundary,
      CharacteristicFamily.MINUS,
      position_tolerance_m=position_tolerance_m,
      invariant_tolerance=invariant_tolerance,
    )
    if (
      not axis_result.converged
      or axis_result.state is None
      or axis_result.point_m is None
    ):
      return _failure(
        MocCausticFamilyBandStatus.GEOMETRY_FAILURE,
        f'centerline trace failed at band step {index}: {axis_result.message}',
        cells=tuple(cells),
        geometry_residuals=tuple(geometry_residuals),
        invariant_residuals=tuple(invariant_residuals),
      )
    if axis_result.geometry_residual is not None:
      geometry_residuals.append(abs(axis_result.geometry_residual))
    point_residual = sqrt(
      (axis_result.point_m[0] - axis_state.x_m) ** 2
      + (axis_result.point_m[1] - axis_state.y_m) ** 2
    )
    if point_residual > position_tolerance_m:
      geometry_residuals.append(point_residual)
      return _failure(
        MocCausticFamilyBandStatus.GEOMETRY_FAILURE,
        f'centerline trace disagrees with restart state at band step {index}',
        cells=tuple(cells),
        geometry_residuals=tuple(geometry_residuals),
        invariant_residuals=tuple(invariant_residuals),
      )
    if axis_state.x_m <= centerline_states[index - 1].x_m + position_tolerance_m:
      return _failure(
        MocCausticFamilyBandStatus.GEOMETRY_FAILURE,
        f'centerline trace is not downstream at band step {index}',
        cells=tuple(cells),
        geometry_residuals=tuple(geometry_residuals),
        invariant_residuals=tuple(invariant_residuals),
      )
    if boundary_state.x_m <= previous_boundary.x_m + position_tolerance_m:
      return _failure(
        MocCausticFamilyBandStatus.GEOMETRY_FAILURE,
        f'ambient boundary is not downstream at band step {index}',
        cells=tuple(cells),
        geometry_residuals=tuple(geometry_residuals),
        invariant_residuals=tuple(invariant_residuals),
      )
    compatibility_residual = boundary_state.k_plus - axis_state.k_plus
    invariant_residuals.append(compatibility_residual)
    if abs(compatibility_residual) > invariant_tolerance:
      return _failure(
        MocCausticFamilyBandStatus.GEOMETRY_FAILURE,
        f'ambient C+ compatibility failed at band step {index}',
        cells=tuple(cells),
        geometry_residuals=tuple(geometry_residuals),
        invariant_residuals=tuple(invariant_residuals),
      )
    axis_previous_point = (
      centerline_states[index - 1].x_m,
      centerline_states[index - 1].y_m,
    )
    previous_boundary_point = (previous_boundary.x_m, previous_boundary.y_m)
    axis_point = (axis_state.x_m, axis_state.y_m)
    boundary_point = (boundary_state.x_m, boundary_state.y_m)
    try:
      cells.append(
        MocCharacteristicCell(
          cell_index=len(cells),
          cell_kind='caustic-restart-centerline-band',
          vertices_xr_m=(axis_previous_point, previous_boundary_point, axis_point),
          centerline_indices=(index - 1, index),
          boundary_indices=(index - 1,),
        )
      )
      cells.append(
        MocCharacteristicCell(
          cell_index=len(cells),
          cell_kind='caustic-restart-ambient-band',
          vertices_xr_m=(axis_point, previous_boundary_point, boundary_point),
          centerline_indices=(index,),
          boundary_indices=(index - 1, index),
        )
      )
    except (TypeError, ValueError) as error:
      return _failure(
        MocCausticFamilyBandStatus.GEOMETRY_FAILURE,
        f'caustic family band cell failed at step {index}: {error}',
        cells=tuple(cells),
        geometry_residuals=tuple(geometry_residuals),
        invariant_residuals=tuple(invariant_residuals),
      )

  topology = validate_moc_mesh(tuple(cells))
  if not topology.connected or topology.nonmanifold_edge_count:
    return _failure(
      MocCausticFamilyBandStatus.TOPOLOGY_FAILURE,
      f'caustic family band topology failed: {topology.message}',
      cells=tuple(cells),
      topology=topology,
      geometry_residuals=tuple(geometry_residuals),
      invariant_residuals=tuple(invariant_residuals),
    )
  geometry_values = tuple(geometry_residuals)
  if seed_geometry_residual_m is not None:
    geometry_values = (*geometry_values, abs(seed_geometry_residual_m))
  return MocCausticFamilyBandResult(
    status=MocCausticFamilyBandStatus.CONVERGED_OPEN_BAND,
    centerline_states=centerline_states,
    boundary_states=boundary_states,
    cells=tuple(cells),
    topology=topology,
    input_edge_points_m=input_edge,
    output_edge_points_m=output_edge,
    maximum_absolute_geometry_residual_m=max(geometry_values, default=None),
    maximum_absolute_invariant_residual=max(
      map(abs, invariant_residuals),
      default=None,
    ),
    message=(
      'caustic restart produced a connected open two-triangle family band; '
      'shock fitting, downstream closure, and chain promotion remain blocked'
    ),
  )


def restart_characteristic_family_from_caustic(
  seed: MocSourceStripCausticShockSeedResult,
  total_pressure_Pa: float,
  ambient_pressure_Pa: float,
  *,
  anchor_edge_index: int = 0,
  sample_count: int = 6,
  position_tolerance_m: float = 1.0e-10,
  invariant_tolerance: float = 1.0e-10,
  pressure_tolerance: float = 1.0e-10,
  maximum_iterations: int = 16,
) -> MocCausticFamilyRestartResult:
  """Restart an open reflected boundary from one side of a caustic.

  ``anchor_edge_index`` selects one already-solved one-sided C- edge.  The
  selected state is not averaged with the opposite edge and is not treated as
  a shock state.  A first C- reflection creates an axis state; each following
  C+ boundary point is solved against the previous ambient/tangent boundary.
  The optional triangular source-strip assembly is retained only as a local
  diagnostic because a caustic restart generally needs a new mesh family.
  """

  if not isinstance(seed, MocSourceStripCausticShockSeedResult):
    return _failure(
      MocCausticFamilyRestartStatus.INVALID_INPUT,
      seed=None,
      anchor_edge_index=None,
      message='seed must be a MocSourceStripCausticShockSeedResult',
    )
  try:
    total_pressure = float(total_pressure_Pa)
    ambient_pressure = float(ambient_pressure_Pa)
  except (TypeError, ValueError):
    return _failure(
      MocCausticFamilyRestartStatus.INVALID_INPUT,
      seed=seed,
      anchor_edge_index=anchor_edge_index,
      message='pressures must be finite numeric values',
    )
  if (
    not isfinite(total_pressure)
    or total_pressure <= 0.0
    or not isfinite(ambient_pressure)
    or ambient_pressure <= 0.0
    or total_pressure <= ambient_pressure
  ):
    return _failure(
      MocCausticFamilyRestartStatus.INVALID_INPUT,
      seed=seed,
      anchor_edge_index=anchor_edge_index,
      total_pressure_Pa=total_pressure,
      ambient_pressure_Pa=ambient_pressure,
      message='total pressure must exceed finite positive ambient pressure',
    )
  if (
    isinstance(anchor_edge_index, bool)
    or not isinstance(anchor_edge_index, int)
    or anchor_edge_index not in (0, 1)
  ):
    return _failure(
      MocCausticFamilyRestartStatus.INVALID_INPUT,
      seed=seed,
      anchor_edge_index=anchor_edge_index,
      total_pressure_Pa=total_pressure,
      ambient_pressure_Pa=ambient_pressure,
      message='anchor_edge_index must be 0 or 1',
    )
  if (
    isinstance(sample_count, bool)
    or not isinstance(sample_count, int)
    or sample_count < 3
  ):
    return _failure(
      MocCausticFamilyRestartStatus.INVALID_INPUT,
      seed=seed,
      anchor_edge_index=anchor_edge_index,
      total_pressure_Pa=total_pressure,
      ambient_pressure_Pa=ambient_pressure,
      message='sample_count must be an integer of at least three',
    )
  for name, value in (
    ('position_tolerance_m', position_tolerance_m),
    ('invariant_tolerance', invariant_tolerance),
    ('pressure_tolerance', pressure_tolerance),
  ):
    if not isfinite(float(value)) or value <= 0.0:
      raise ValueError(f'{name} must be finite and positive')
  if isinstance(maximum_iterations, bool) or maximum_iterations < 1:
    raise ValueError('maximum_iterations must be a positive integer')
  if not seed.converged or len(seed.edge_states) != 2:
    return _failure(
      MocCausticFamilyRestartStatus.SEED_FAILURE,
      seed=seed,
      anchor_edge_index=anchor_edge_index,
      total_pressure_Pa=total_pressure,
      ambient_pressure_Pa=ambient_pressure,
      message=f'caustic restart seed is not usable: {seed.message}',
    )
  anchor = seed.edge_states[anchor_edge_index]
  if anchor.state is None or anchor.point_m is None:
    return _failure(
      MocCausticFamilyRestartStatus.SEED_FAILURE,
      seed=seed,
      anchor_edge_index=anchor_edge_index,
      total_pressure_Pa=total_pressure,
      ambient_pressure_Pa=ambient_pressure,
      message='selected caustic edge does not carry a one-sided anchor state',
    )
  anchor_state = anchor.state
  centerline_states: list[CharacteristicState] = []
  boundary_states: list[CharacteristicState] = []
  boundary_points: list[tuple[float, float]] = []
  pressure_residuals: list[float] = []
  tangent_residuals: list[float] = []
  geometry_residuals: list[float] = []
  forward_progress: list[float] = []
  previous_boundary = anchor_state
  for step in range(sample_count):
    axis_result = centerline_characteristic_point(
      previous_boundary,
      CharacteristicFamily.MINUS,
      position_tolerance_m=position_tolerance_m,
      invariant_tolerance=invariant_tolerance,
    )
    if not axis_result.converged or axis_result.state is None:
      return _failure(
        MocCausticFamilyRestartStatus.CENTERLINE_FAILURE,
        seed=seed,
        anchor_edge_index=anchor_edge_index,
        anchor_point_m=anchor.point_m,
        anchor_state=anchor_state,
        centerline_states=tuple(centerline_states),
        boundary_states=tuple(boundary_states),
        boundary_points_m=tuple(boundary_points),
        total_pressure_Pa=total_pressure,
        ambient_pressure_Pa=ambient_pressure,
        maximum_absolute_pressure_residual=max(map(abs, pressure_residuals), default=None),
        maximum_absolute_tangent_residual=max(map(abs, tangent_residuals), default=None),
        maximum_absolute_geometry_residual_m=max(map(abs, geometry_residuals), default=None),
        minimum_forward_progress_m=min(forward_progress, default=None),
        message=f'caustic restart centerline reflection failed at step {step}: {axis_result.message}',
      )
    boundary_result = solve_ambient_pressure_free_boundary_point(
      axis_result.state,
      previous_boundary,
      CharacteristicFamily.PLUS,
      total_pressure_Pa=total_pressure,
      ambient_pressure_Pa=ambient_pressure,
      position_tolerance_m=position_tolerance_m,
      pressure_tolerance=pressure_tolerance,
      maximum_iterations=maximum_iterations,
    )
    if not _state_result_reportable(boundary_result):
      return _failure(
        MocCausticFamilyRestartStatus.AMBIENT_BOUNDARY_FAILURE,
        seed=seed,
        anchor_edge_index=anchor_edge_index,
        anchor_point_m=anchor.point_m,
        anchor_state=anchor_state,
        centerline_states=tuple(centerline_states),
        boundary_states=tuple(boundary_states),
        boundary_points_m=tuple(boundary_points),
        total_pressure_Pa=total_pressure,
        ambient_pressure_Pa=ambient_pressure,
        maximum_absolute_pressure_residual=max(map(abs, pressure_residuals), default=None),
        maximum_absolute_tangent_residual=max(map(abs, tangent_residuals), default=None),
        maximum_absolute_geometry_residual_m=max(map(abs, geometry_residuals), default=None),
        minimum_forward_progress_m=min(forward_progress, default=None),
        message=f'caustic restart ambient boundary failed at step {step}: {boundary_result.message}',
      )
    assert boundary_result.state is not None
    assert boundary_result.point_m is not None
    progress = boundary_result.point_m[0] - previous_boundary.x_m
    if progress <= position_tolerance_m:
      return _failure(
        MocCausticFamilyRestartStatus.AMBIENT_BOUNDARY_FAILURE,
        seed=seed,
        anchor_edge_index=anchor_edge_index,
        anchor_point_m=anchor.point_m,
        anchor_state=anchor_state,
        centerline_states=tuple(centerline_states),
        boundary_states=tuple(boundary_states),
        boundary_points_m=tuple(boundary_points),
        total_pressure_Pa=total_pressure,
        ambient_pressure_Pa=ambient_pressure,
        maximum_absolute_pressure_residual=max(map(abs, pressure_residuals), default=None),
        maximum_absolute_tangent_residual=max(map(abs, tangent_residuals), default=None),
        maximum_absolute_geometry_residual_m=max(map(abs, geometry_residuals), default=None),
        minimum_forward_progress_m=min(forward_progress, default=None),
        message='caustic restart ambient boundary did not make downstream progress',
      )
    centerline_states.append(axis_result.state)
    boundary_states.append(boundary_result.state)
    boundary_points.append(boundary_result.point_m)
    pressure_residuals.append(boundary_result.pressure_residual or 0.0)
    tangent_residuals.append(boundary_result.tangent_residual or 0.0)
    geometry_residuals.append(boundary_result.geometry_residual or 0.0)
    forward_progress.append(progress)
    previous_boundary = boundary_result.state

  source_strip = assemble_source_characteristic_strip(
    tuple(centerline_states),
    tuple(boundary_states),
    total_pressure,
    position_tolerance_m=position_tolerance_m,
    invariant_tolerance=invariant_tolerance,
  )
  family_band = _assemble_open_family_band(
    tuple(centerline_states),
    tuple(boundary_states),
    position_tolerance_m=position_tolerance_m,
    invariant_tolerance=invariant_tolerance,
    seed_geometry_residual_m=anchor.geometry_residual_m,
  )
  return MocCausticFamilyRestartResult(
    status=MocCausticFamilyRestartStatus.CONVERGED_OPEN_BOUNDARY,
    seed=seed,
    anchor_edge_index=anchor_edge_index,
    anchor_point_m=anchor.point_m,
    anchor_state=anchor_state,
    centerline_states=tuple(centerline_states),
    boundary_states=tuple(boundary_states),
    boundary_points_m=tuple(boundary_points),
    total_pressure_Pa=total_pressure,
    ambient_pressure_Pa=ambient_pressure,
    maximum_absolute_pressure_residual=max(map(abs, pressure_residuals), default=None),
    maximum_absolute_tangent_residual=max(map(abs, tangent_residuals), default=None),
    maximum_absolute_geometry_residual_m=max(map(abs, geometry_residuals), default=None),
    minimum_forward_progress_m=min(forward_progress, default=None),
    source_strip=source_strip,
    family_band=family_band,
    message=(
      'one-sided caustic family restart converged as an open '
      'centerline/ambient boundary; triangular interior remesh and shock '
      'closure remain separate gates'
    ),
  )
