"""Solver-generated attached-shock boundaries for the planar MOC lane.

The older post-shock primitives accept an explicitly sampled shock curve.  This
module supplies the next boundary: it marches the shock tangent returned by the
attached theta-beta-Mach solve until a requested symmetry-line ordinate is
reached.  The upstream state and static-pressure fields remain explicit
callbacks so this solver does not invent a thermodynamic field or silently
reuse a lower-fidelity provider.

The uniform reference helper is a deterministic canonical fixture for the
constant-gamma planar lane.  It uses a uniform upstream state and a linear
downstream flow-angle law; its shock geometry is still generated by the
attached-shock march, not supplied as points.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from enum import Enum
from math import isfinite, sin, tan
from typing import TYPE_CHECKING, Callable, Sequence

if TYPE_CHECKING:
  from exhaust_plume.models.moc.coupled import MocAmbientClosureResult

from exhaust_plume.models.moc.compression import solve_attached_compression_to_turn
from exhaust_plume.models.moc.boundary import MocReflectedBoundaryResult
from exhaust_plume.models.moc.chain import MocChainBoundarySample, MocChainCell
from exhaust_plume.models.moc.post_shock import (
  MocPostShockBoundaryState,
  MocPostShockChainCellSolve,
  MocPostShockCharacteristicFieldResult,
  MocPostShockFieldStatus,
  MocShockBoundaryFitResult,
  assemble_post_shock_characteristic_field,
  fit_attached_shock_boundary,
)
from exhaust_plume.models.moc.primitives import CharacteristicState
from exhaust_plume.models.moc.source_strip import MocSourceCharacteristicStripResult
from exhaust_plume.models.moc.zone import (
  MocReflectedCharacteristicZoneResult,
  MocReflectedZoneShockCouplingResult,
  MocReflectedZoneShockCouplingStatus,
  sample_reflected_zone_along_shock_path,
)
from exhaust_plume.util.aero.shock_validity import ShockBranch

__all__ = (
  'MocFreeBoundaryShockResult',
  'MocFreeBoundaryShockStatus',
  'MocReflectedZoneShockSolveResult',
  'MocReflectedZoneAmbientClosureResult',
  'solve_marched_attached_shock_field',
  'solve_marched_attached_shock_from_source_strip',
  'solve_marched_attached_shock_from_reflected_zone',
  'solve_marched_attached_shock_with_ambient_pressure_closure_from_reflected_zone',
  'solve_reflected_boundary_trace_extension',
  'solve_marched_attached_shock_chain_cell',
  'solve_marched_attached_shock_chain_cell_from_reflected_zone',
  'solve_uniform_attached_shock_field',
)


class MocFreeBoundaryShockStatus(str, Enum):
  """Structured outcome for a solver-generated attached-shock field."""

  CONVERGED_FIELD = 'converged_free_boundary_field'
  INVALID_INPUT = 'invalid_input'
  UPSTREAM_FIELD_FAILURE = 'upstream_field_failure'
  COMPRESSION_FAILURE = 'compression_failure'
  SUBSONIC_TERMINAL_REQUIRED = 'subsonic_terminal_required'
  GEOMETRY_FAILURE = 'geometry_failure'
  SHOCK_FIT_FAILURE = 'shock_fit_failure'
  FIELD_FAILURE = 'field_failure'
####


@dataclass(frozen=True, slots=True)
class MocFreeBoundaryShockResult:
  """A shock curve and post-shock field generated without prescribed points."""

  status: MocFreeBoundaryShockStatus
  shock_fit: MocShockBoundaryFitResult | None
  field: MocPostShockCharacteristicFieldResult | None
  shock_points_m: tuple[tuple[float, float], ...]
  upstream_states: tuple[CharacteristicState, ...]
  upstream_pressure_Pa: tuple[float, ...]
  downstream_flow_angles_rad: tuple[float, ...]
  shock_angle_residuals_rad: tuple[float, ...]
  maximum_shock_angle_residual_rad: float | None
  endpoint_m: tuple[float, float] | None
  message: str = ''

  @property
  def converged(self) -> bool:
    return self.status is MocFreeBoundaryShockStatus.CONVERGED_FIELD
  ####

  @property
  def physical_closure_verified(self) -> bool:
    return self.converged and self.field is not None and self.field.physical_closure_verified
  ####

  @property
  def subsonic_terminal_required(self) -> bool:
    """Whether the supersonic MOC lane reached a normal-shock boundary."""

    return self.status is MocFreeBoundaryShockStatus.SUBSONIC_TERMINAL_REQUIRED
  ####

  @property
  def sample_count(self) -> int:
    return len(self.shock_points_m)
  ####

  @property
  def field_status(self) -> MocPostShockFieldStatus | None:
    return None if self.field is None else self.field.status
  ####

  def as_report(self) -> dict[str, object]:
    return {
      'status': self.status.value,
      'converged': self.converged,
      'physical_closure_verified': self.physical_closure_verified,
      'subsonic_terminal_required': self.subsonic_terminal_required,
      'sample_count': self.sample_count,
      'endpoint_m': self.endpoint_m,
      'maximum_shock_angle_residual_rad': self.maximum_shock_angle_residual_rad,
      'field_status': None if self.field_status is None else self.field_status.value,
      'message': self.message,
    }
####


@dataclass(frozen=True, slots=True)
class MocReflectedZoneShockSolveResult:
  """A shock march with an explicit reflected-zone upstream coupling probe.

  The reflected characteristic zone owns the upstream domain.  This wrapper
  records both the generated shock result and the independent domain-bounded
  resampling result, so a successful post-shock field cannot be mistaken for
  an upstream-coupled solve when the path has left the solved zone.  The
  downstream flow-angle condition remains caller-supplied; solving that
  condition and the ambient outer perimeter are separate future gates.
  """

  shock: MocFreeBoundaryShockResult
  coupling: MocReflectedZoneShockCouplingResult
  message: str = ''

  @property
  def converged(self) -> bool:
    """Whether both the shock field and every upstream sample converged."""

    return self.shock.converged and self.coupling.converged
  ####

  @property
  def upstream_coupling_verified(self) -> bool:
    """Whether the generated shock path is fully covered by the reflected zone."""

    return self.converged and (
      len(self.shock.shock_points_m) == len(self.coupling.shock_points_m)
      and len(self.shock.upstream_states) == len(self.coupling.upstream_states)
      and len(self.shock.upstream_pressure_Pa) == len(self.coupling.upstream_pressure_Pa)
    )
  ####

  @property
  def physical_closure_verified(self) -> bool:
    """Whether numerical shock/field closure passed after upstream coupling."""

    return self.upstream_coupling_verified and self.shock.physical_closure_verified
  ####

  def as_report(self) -> dict[str, object]:
    return {
      'status': self.shock.status.value,
      'converged': self.converged,
      'upstream_coupling_verified': self.upstream_coupling_verified,
      'physical_closure_verified': self.physical_closure_verified,
      'shock': self.shock.as_report(),
      'coupling': self.coupling.as_report(),
      'downstream_condition_status': 'caller-supplied',
      'message': self.message,
    }
  ####

@dataclass(frozen=True, slots=True)
class MocReflectedZoneAmbientClosureResult:
  """Ambient closure result carrying an independent reflected-zone probe."""

  closure: MocAmbientClosureResult
  coupling: MocReflectedZoneShockCouplingResult
  message: str = ''

  @property
  def converged(self) -> bool:
    return self.closure.converged and self.coupling.converged
  ####

  @property
  def upstream_coupling_verified(self) -> bool:
    return self.converged
  ####

  @property
  def physical_closure_verified(self) -> bool:
    return self.converged and self.closure.physical_closure_verified
  ####

  def as_report(self) -> dict[str, object]:
    return {
      'status': self.closure.status.value,
      'converged': self.converged,
      'upstream_coupling_verified': self.upstream_coupling_verified,
      'physical_closure_verified': self.physical_closure_verified,
      'closure': self.closure.as_report(),
      'coupling': self.coupling.as_report(),
      'message': self.message,
    }
  ####

  def as_chain_cell(
    self,
    *,
    start_x_m: float,
    end_x_m: float,
    cell_index: int = 1,
    diagnostics: dict[str, object] | None = None,
  ) -> MocChainCell:
    """Promote only an ambient-closed field with complete zone coupling."""

    if not self.converged:
      raise ValueError(
        'only a converged reflected-zone ambient closure can become a '
        'continued MOC chain cell'
      )
    assert self.coupling.converged
    coupled_diagnostics: dict[str, object] = {
      'reflected_zone_upstream_coupling_verified': True,
      'reflected_zone_coupling_sample_count': self.coupling.sampled_count,
    }
    if diagnostics is not None:
      reserved = set(coupled_diagnostics) & set(diagnostics)
      if reserved:
        raise ValueError(
          f'diagnostics cannot override reserved reflected-zone keys: {sorted(reserved)!r}'
        )
      coupled_diagnostics.update(diagnostics)
    return self.closure.as_chain_cell(
      start_x_m=start_x_m,
      end_x_m=end_x_m,
      cell_index=cell_index,
      diagnostics=coupled_diagnostics,
    )
  ####


@dataclass(frozen=True, slots=True)
class _MarchSample:
  point_m: tuple[float, float]
  upstream_state: CharacteristicState
  upstream_pressure_Pa: float
  downstream_flow_angle_rad: float
  shock_angle_rad: float
  boundary_state: MocPostShockBoundaryState
####


def _failure(
  status: MocFreeBoundaryShockStatus,
  *,
  shock_fit: MocShockBoundaryFitResult | None = None,
  field: MocPostShockCharacteristicFieldResult | None = None,
  shock_points: Sequence[tuple[float, float]] = (),
  upstream_states: Sequence[CharacteristicState] = (),
  upstream_pressures: Sequence[float] = (),
  downstream_angles: Sequence[float] = (),
  shock_angle_residuals: Sequence[float] = (),
  endpoint_m: tuple[float, float] | None = None,
  message: str,
) -> MocFreeBoundaryShockResult:
  residuals = tuple(float(value) for value in shock_angle_residuals)
  return MocFreeBoundaryShockResult(
    status=status,
    shock_fit=shock_fit,
    field=field,
    shock_points_m=tuple((float(point[0]), float(point[1])) for point in shock_points),
    upstream_states=tuple(upstream_states),
    upstream_pressure_Pa=tuple(float(value) for value in upstream_pressures),
    downstream_flow_angles_rad=tuple(float(value) for value in downstream_angles),
    shock_angle_residuals_rad=residuals,
    maximum_shock_angle_residual_rad=max((abs(value) for value in residuals), default=None),
    endpoint_m=endpoint_m,
    message=message,
  )
####


def _finite_point(point_m: tuple[float, float], name: str) -> tuple[float, float]:
  if len(point_m) != 2 or not all(isfinite(float(value)) for value in point_m):
    raise ValueError(f'{name} must contain two finite coordinates')
  return float(point_m[0]), float(point_m[1])
####


def solve_marched_attached_shock_field(
  upstream_state_at: Callable[[tuple[float, float]], CharacteristicState | None],
  upstream_pressure_at: Callable[[tuple[float, float]], float | None],
  start_point_m: tuple[float, float],
  *,
  target_centerline_y_m: float = 0.0,
  downstream_flow_angle_at: Callable[[int, tuple[float, float]], float] | None = None,
  downstream_flow_angle_rad: float | None = None,
  incoming_handoff: Sequence[MocChainBoundarySample] | None = None,
  sample_count: int = 17,
  branch: ShockBranch = ShockBranch.WEAK,
  position_tolerance_m: float = 1.0e-10,
  invariant_tolerance: float = 1.0e-10,
  shock_angle_tolerance_rad: float = 1.0e-2,
  maximum_segment_iterations: int = 24,
) -> MocFreeBoundaryShockResult:
  """March an attached shock from a boundary point to the symmetry line.

  At each sample the upstream callback supplies the local state and static
  pressure.  The downstream flow-angle callback supplies the local turn
  boundary condition.  The shock tangent is then
  ``theta_upstream - beta``; a trapezoidal march in ``x(y)`` generates the
  next point.  The generated samples are rechecked by
  :func:`fit_attached_shock_boundary` before the complete post-shock field is
  assembled.

  Exactly one of ``downstream_flow_angle_at`` and
  ``downstream_flow_angle_rad`` may be supplied.  A scalar angle is useful for
  a uniform boundary, but a nonzero angle profile is required to produce a
  finite characteristic-field area in the uniform reference helper. When
  ``incoming_handoff`` is supplied, the assembled field records the exact
  prior terminal trace as consumed state; it does not use that trace as a
  shock curve.
  """

  try:
    start = _finite_point(start_point_m, 'start_point_m')
    target_y = float(target_centerline_y_m)
  except (TypeError, ValueError):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='start point and target centerline ordinate must be finite',
    )
  if not isfinite(target_y) or target_y >= start[1]:
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='target centerline ordinate must be below the shock start',
    )
  if not callable(upstream_state_at) or not callable(upstream_pressure_at):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='upstream state and pressure providers must be callable',
    )
  if (downstream_flow_angle_at is None) == (downstream_flow_angle_rad is None):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='supply exactly one downstream flow-angle provider',
    )
  if not isinstance(branch, ShockBranch):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='branch must be a ShockBranch',
    )
  if isinstance(sample_count, bool) or not isinstance(sample_count, int) or sample_count < 3:
    raise ValueError('sample_count must be an integer of at least three')
  for name, value in (
    ('position_tolerance_m', position_tolerance_m),
    ('invariant_tolerance', invariant_tolerance),
    ('shock_angle_tolerance_rad', shock_angle_tolerance_rad),
  ):
    if not isfinite(float(value)) or value <= 0.0:
      raise ValueError(f'{name} must be finite and positive')
  if (
    isinstance(maximum_segment_iterations, bool)
    or not isinstance(maximum_segment_iterations, int)
    or maximum_segment_iterations < 1
  ):
    raise ValueError('maximum_segment_iterations must be a positive integer')
  ####

  dy = (target_y - start[1]) / (sample_count - 1)
  points: list[tuple[float, float]] = []
  upstream_states: list[CharacteristicState] = []
  upstream_pressures: list[float] = []
  downstream_angles: list[float] = []

  def evaluate(point: tuple[float, float], index: int) -> tuple[_MarchSample | None, str | None, MocFreeBoundaryShockStatus]:
    try:
      state = upstream_state_at(point)
      pressure = upstream_pressure_at(point)
    except (ArithmeticError, FloatingPointError, TypeError, ValueError) as error:
      return None, f'upstream field callback failed at sample {index}: {error}', MocFreeBoundaryShockStatus.UPSTREAM_FIELD_FAILURE
    if not isinstance(state, CharacteristicState):
      return None, f'upstream field callback returned no CharacteristicState at sample {index}', MocFreeBoundaryShockStatus.UPSTREAM_FIELD_FAILURE
    if state.x_m != point[0] or state.y_m != point[1]:
      if (
        abs(state.x_m - point[0]) > position_tolerance_m
        or abs(state.y_m - point[1]) > position_tolerance_m
      ):
        return None, f'upstream state {index} does not lie at the marched shock point', MocFreeBoundaryShockStatus.UPSTREAM_FIELD_FAILURE
      state = replace(state, x_m=point[0], y_m=point[1])
    if pressure is None or not isfinite(float(pressure)) or float(pressure) <= 0.0:
      return None, f'upstream pressure provider returned an invalid value at sample {index}', MocFreeBoundaryShockStatus.UPSTREAM_FIELD_FAILURE
    if downstream_flow_angle_at is not None:
      try:
        target_angle = float(downstream_flow_angle_at(index, point))
      except (ArithmeticError, FloatingPointError, TypeError, ValueError) as error:
        return None, f'downstream angle callback failed at sample {index}: {error}', MocFreeBoundaryShockStatus.INVALID_INPUT
    else:
      assert downstream_flow_angle_rad is not None
      target_angle = float(downstream_flow_angle_rad)
    if not isfinite(target_angle):
      return None, f'downstream flow angle {index} must be finite', MocFreeBoundaryShockStatus.INVALID_INPUT
    turn = target_angle - state.theta_rad
    if turn <= 0.0:
      if (
        abs(turn) <= position_tolerance_m
        and abs(target_y) <= position_tolerance_m
      ):
        return None, (
          f'sample {index} reaches the symmetry line with zero flow turn; '
          'a normal shock would require a subsonic terminal model outside '
          'the supersonic MOC lane'
        ), MocFreeBoundaryShockStatus.SUBSONIC_TERMINAL_REQUIRED
      return None, f'sample {index} does not require a positive compression turn', MocFreeBoundaryShockStatus.COMPRESSION_FAILURE
    compression = solve_attached_compression_to_turn(
      upstream_mach=state.mach,
      gamma=state.gamma,
      upstream_pressure_Pa=float(pressure),
      target_turn_rad=turn,
      branch=branch,
    )
    if (
      not compression.converged
      or compression.beta_rad is None
      or compression.downstream_mach is None
      or compression.upstream_total_pressure_Pa is None
      or compression.downstream_total_pressure_Pa is None
    ):
      failure_status = (
        MocFreeBoundaryShockStatus.SUBSONIC_TERMINAL_REQUIRED
        if compression.downstream_mach is not None and compression.downstream_mach <= 1.0
        else MocFreeBoundaryShockStatus.COMPRESSION_FAILURE
      )
      return None, f'attached compression failed at sample {index}: {compression.message}', failure_status
    shock_angle = state.theta_rad - compression.beta_rad
    if not isfinite(shock_angle) or sin(shock_angle) >= -position_tolerance_m:
      return None, f'shock tangent at sample {index} does not travel toward the centerline', MocFreeBoundaryShockStatus.GEOMETRY_FAILURE
    try:
      boundary_state = MocPostShockBoundaryState(
        point_m=point,
        state=CharacteristicState(
          x_m=point[0],
          y_m=point[1],
          theta_rad=target_angle,
          mach=compression.downstream_mach,
          gamma=state.gamma,
        ),
        upstream_total_pressure_Pa=compression.upstream_total_pressure_Pa,
        downstream_total_pressure_Pa=compression.downstream_total_pressure_Pa,
      )
    except (TypeError, ValueError) as error:
      return None, f'downstream shock state {index} is invalid: {error}', MocFreeBoundaryShockStatus.COMPRESSION_FAILURE
    return (
      _MarchSample(
        point_m=point,
        upstream_state=state,
        upstream_pressure_Pa=float(pressure),
        downstream_flow_angle_rad=target_angle,
        shock_angle_rad=shock_angle,
        boundary_state=boundary_state,
      ),
      None,
      MocFreeBoundaryShockStatus.CONVERGED_FIELD,
    )

  current_point = start
  current_sample, error, error_status = evaluate(current_point, 0)
  if current_sample is None:
    return _failure(error_status, message=error or 'initial shock sample failed')
  points.append(current_sample.point_m)
  upstream_states.append(current_sample.upstream_state)
  upstream_pressures.append(current_sample.upstream_pressure_Pa)
  downstream_angles.append(current_sample.downstream_flow_angle_rad)
  ####

  for index in range(1, sample_count):
    next_y = start[1] + index * dy
    tangent = current_sample.shock_angle_rad
    next_x = current_point[0] + dy / tan(tangent)
    next_sample: _MarchSample | None = None
    for _ in range(maximum_segment_iterations):
      candidate_point = (float(next_x), float(next_y))
      candidate_sample, error, error_status = evaluate(candidate_point, index)
      if candidate_sample is None:
        return _failure(
          error_status,
          shock_points=points,
          upstream_states=upstream_states,
          upstream_pressures=upstream_pressures,
          downstream_angles=downstream_angles,
          endpoint_m=points[-1] if points else None,
          message=error or f'shock sample {index} failed',
        )
      next_sample = candidate_sample
      next_tangent = candidate_sample.shock_angle_rad
      updated_x = current_point[0] + dy * 0.5 * (1.0 / tan(tangent) + 1.0 / tan(next_tangent))
      if abs(updated_x - next_x) <= position_tolerance_m:
        next_x = updated_x
        final_sample, final_error, final_status = evaluate(
          (float(next_x), float(next_y)),
          index,
        )
        if final_sample is None:
          return _failure(
            final_status,
            shock_points=points,
            upstream_states=upstream_states,
            upstream_pressures=upstream_pressures,
            downstream_angles=downstream_angles,
            endpoint_m=points[-1] if points else None,
            message=final_error or f'shock sample {index} failed at its converged endpoint',
          )
        next_sample = final_sample
        break
      next_x = updated_x
    else:
      return _failure(
        MocFreeBoundaryShockStatus.GEOMETRY_FAILURE,
        shock_points=points,
        upstream_states=upstream_states,
        upstream_pressures=upstream_pressures,
        downstream_angles=downstream_angles,
        endpoint_m=points[-1] if points else None,
        message=f'shock segment {index - 1} did not converge to a tangent-consistent endpoint',
      )
    if next_sample is None:
      return _failure(
        MocFreeBoundaryShockStatus.GEOMETRY_FAILURE,
        shock_points=points,
        upstream_states=upstream_states,
        upstream_pressures=upstream_pressures,
        downstream_angles=downstream_angles,
        endpoint_m=points[-1] if points else None,
        message=f'shock segment {index - 1} produced no endpoint sample',
      )
    current_point = (float(next_x), float(next_y))
    if current_point[0] <= points[-1][0] + position_tolerance_m:
      return _failure(
        MocFreeBoundaryShockStatus.GEOMETRY_FAILURE,
        shock_points=points,
        upstream_states=upstream_states,
        upstream_pressures=upstream_pressures,
        downstream_angles=downstream_angles,
        endpoint_m=points[-1] if points else None,
        message=f'shock sample {index} is not strictly downstream',
      )
    points.append(current_point)
    upstream_states.append(replace(next_sample.upstream_state, x_m=current_point[0], y_m=current_point[1]))
    upstream_pressures.append(next_sample.upstream_pressure_Pa)
    downstream_angles.append(next_sample.downstream_flow_angle_rad)
    current_sample = replace(
      next_sample,
      point_m=current_point,
      upstream_state=replace(
        next_sample.upstream_state,
        x_m=current_point[0],
        y_m=current_point[1],
      ),
      boundary_state=replace(
        next_sample.boundary_state,
        point_m=current_point,
        state=replace(
          next_sample.boundary_state.state,
          x_m=current_point[0],
          y_m=current_point[1],
        ),
      ),
    )
  ####

  shock_fit = fit_attached_shock_boundary(
    upstream_states,
    upstream_pressures,
    points,
    downstream_angles,
    branch=branch,
    position_tolerance_m=position_tolerance_m,
    shock_angle_tolerance_rad=shock_angle_tolerance_rad,
  )
  if not shock_fit.converged:
    return _failure(
      MocFreeBoundaryShockStatus.SHOCK_FIT_FAILURE,
      shock_fit=shock_fit,
      shock_points=points,
      upstream_states=upstream_states,
      upstream_pressures=upstream_pressures,
      downstream_angles=downstream_angles,
      shock_angle_residuals=shock_fit.shock_angle_residuals_rad,
      endpoint_m=points[-1],
      message=f'generated shock boundary failed attached-shock verification: {shock_fit.message}',
    )
  field = assemble_post_shock_characteristic_field(
    shock_fit,
    incoming_handoff=incoming_handoff,
    position_tolerance_m=position_tolerance_m,
    invariant_tolerance=invariant_tolerance,
    shock_angle_tolerance_rad=shock_angle_tolerance_rad,
  )
  if not field.converged:
    return _failure(
      MocFreeBoundaryShockStatus.FIELD_FAILURE,
      shock_fit=shock_fit,
      field=field,
      shock_points=points,
      upstream_states=upstream_states,
      upstream_pressures=upstream_pressures,
      downstream_angles=downstream_angles,
      shock_angle_residuals=shock_fit.shock_angle_residuals_rad,
      endpoint_m=points[-1],
      message=f'generated shock boundary did not close its characteristic field: {field.message}',
    )
  field = replace(
    field,
    shock_closure_status='solver-generated-marched-attached-shock',
    message=(
      'solver-generated marched attached shock and post-shock C+/C- field '
      'converged with explicit shock and centerline boundary edges'
    ),
  )
  return MocFreeBoundaryShockResult(
    status=MocFreeBoundaryShockStatus.CONVERGED_FIELD,
    shock_fit=shock_fit,
    field=field,
    shock_points_m=tuple(points),
    upstream_states=tuple(upstream_states),
    upstream_pressure_Pa=tuple(upstream_pressures),
    downstream_flow_angles_rad=tuple(downstream_angles),
    shock_angle_residuals_rad=shock_fit.shock_angle_residuals_rad,
    maximum_shock_angle_residual_rad=shock_fit.maximum_shock_angle_residual_rad,
    endpoint_m=points[-1],
    message=(
      'solver-generated attached-shock boundary reached the symmetry line '
      'and closed the post-shock characteristic field'
    ),
  )
####


def solve_marched_attached_shock_from_source_strip(
  upstream_strip: MocSourceCharacteristicStripResult,
  start_point_m: tuple[float, float],
  *,
  target_centerline_y_m: float = 0.0,
  downstream_flow_angle_at: Callable[[int, tuple[float, float]], float] | None = None,
  downstream_flow_angle_rad: float | None = None,
  incoming_handoff: Sequence[MocChainBoundarySample] | None = None,
  sample_count: int = 17,
  branch: ShockBranch = ShockBranch.WEAK,
  position_tolerance_m: float = 1.0e-10,
  invariant_tolerance: float = 1.0e-10,
  shock_angle_tolerance_rad: float = 1.0e-2,
  maximum_segment_iterations: int = 24,
) -> MocFreeBoundaryShockResult:
  """March a shock using a solved source-boundary MOC strip as upstream data.

  The strip owns the domain boundary.  If the generated shock leaves that
  domain, the result is an explicit ``UPSTREAM_FIELD_FAILURE`` rather than a
  continuation of the last sampled state.
  """

  if not isinstance(upstream_strip, MocSourceCharacteristicStripResult):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='upstream_strip must be a MocSourceCharacteristicStripResult',
    )
  if not upstream_strip.converged:
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message=f'upstream source strip is not converged: {upstream_strip.message}',
    )
  return solve_marched_attached_shock_field(
    upstream_strip.state_at,
    upstream_strip.static_pressure_at,
    start_point_m,
    target_centerline_y_m=target_centerline_y_m,
    downstream_flow_angle_at=downstream_flow_angle_at,
    downstream_flow_angle_rad=downstream_flow_angle_rad,
    incoming_handoff=incoming_handoff,
    sample_count=sample_count,
    branch=branch,
    position_tolerance_m=position_tolerance_m,
    invariant_tolerance=invariant_tolerance,
    shock_angle_tolerance_rad=shock_angle_tolerance_rad,
    maximum_segment_iterations=maximum_segment_iterations,
  )
####


def _coupling_result_for_shock_path(
  reflected_zone: MocReflectedCharacteristicZoneResult,
  shock: MocFreeBoundaryShockResult,
  *,
  position_tolerance_m: float,
) -> MocReflectedZoneShockCouplingResult:
  """Extract an independent coupling result from a generated shock path."""

  if len(shock.shock_points_m) >= 2:
    return sample_reflected_zone_along_shock_path(
      reflected_zone,
      shock.shock_points_m,
      position_tolerance_m=position_tolerance_m,
    )
  status = (
    MocReflectedZoneShockCouplingStatus.OUTSIDE_DOMAIN
    if shock.status is MocFreeBoundaryShockStatus.UPSTREAM_FIELD_FAILURE
    else MocReflectedZoneShockCouplingStatus.INVALID_INPUT
  )
  return MocReflectedZoneShockCouplingResult(
    status=status,
    shock_points_m=shock.shock_points_m,
    upstream_states=shock.upstream_states,
    upstream_pressure_Pa=shock.upstream_pressure_Pa,
    first_missing_sample_index=(
      shock.sample_count
      if status is MocReflectedZoneShockCouplingStatus.OUTSIDE_DOMAIN
      else None
    ),
    message=(
      'shock march stopped before it produced a complete path for the '
      f'reflected-zone coupling probe: {shock.message}'
    ),
  )
####


def solve_marched_attached_shock_from_reflected_zone(
  reflected_zone: MocReflectedCharacteristicZoneResult,
  start_point_m: tuple[float, float],
  *,
  target_centerline_y_m: float = 0.0,
  downstream_flow_angle_at: Callable[[int, tuple[float, float]], float] | None = None,
  downstream_flow_angle_rad: float | None = None,
  incoming_handoff: Sequence[MocChainBoundarySample] | None = None,
  sample_count: int = 17,
  branch: ShockBranch = ShockBranch.WEAK,
  position_tolerance_m: float = 1.0e-10,
  invariant_tolerance: float = 1.0e-10,
  shock_angle_tolerance_rad: float = 1.0e-2,
  maximum_segment_iterations: int = 24,
) -> MocReflectedZoneShockSolveResult:
  """March an attached shock against a solved reflected upstream zone.

  The shock march calls the zone's domain-bounded state and pressure samplers
  at every candidate point.  A second, independent path sampling pass records
  the exact coverage and first missing sample.  The function therefore
  distinguishes a genuinely covered upstream path from a post-shock field
  that only happened to close after a callback or extrapolation.

  ``downstream_flow_angle_at``/``downstream_flow_angle_rad`` remain an explicit
  caller-supplied boundary condition.  This function closes the upstream
  coupling seam; it does not claim that the downstream turn law or ambient
  outer perimeter has been solved.
  """

  if not isinstance(reflected_zone, MocReflectedCharacteristicZoneResult):
    shock = _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='reflected_zone must be a MocReflectedCharacteristicZoneResult',
    )
    coupling = sample_reflected_zone_along_shock_path(reflected_zone, ())
    return MocReflectedZoneShockSolveResult(
      shock=shock,
      coupling=coupling,
      message='reflected-zone shock solve rejected an invalid upstream zone',
    )
  if not reflected_zone.converged:
    shock = _failure(
      MocFreeBoundaryShockStatus.UPSTREAM_FIELD_FAILURE,
      message=f'reflected upstream zone is not converged: {reflected_zone.message}',
    )
    coupling = sample_reflected_zone_along_shock_path(reflected_zone, ())
    return MocReflectedZoneShockSolveResult(
      shock=shock,
      coupling=coupling,
      message='reflected-zone shock solve stopped at the upstream field boundary',
    )

  shock = solve_marched_attached_shock_field(
    reflected_zone.state_at,
    reflected_zone.static_pressure_at,
    start_point_m,
    target_centerline_y_m=target_centerline_y_m,
    downstream_flow_angle_at=downstream_flow_angle_at,
    downstream_flow_angle_rad=downstream_flow_angle_rad,
    incoming_handoff=incoming_handoff,
    sample_count=sample_count,
    branch=branch,
    position_tolerance_m=position_tolerance_m,
    invariant_tolerance=invariant_tolerance,
    shock_angle_tolerance_rad=shock_angle_tolerance_rad,
    maximum_segment_iterations=maximum_segment_iterations,
  )
  coupling = _coupling_result_for_shock_path(
    reflected_zone,
    shock,
    position_tolerance_m=position_tolerance_m,
  )
  if shock.converged and coupling.converged:
    message = (
      'attached shock and post-shock field converged with complete reflected '
      'upstream state/pressure coverage; downstream boundary condition remains '
      'caller-supplied'
    )
  elif not coupling.converged:
    message = f'reflected upstream coupling did not cover the shock path: {coupling.message}'
  else:
    message = shock.message
  return MocReflectedZoneShockSolveResult(
    shock=shock,
    coupling=coupling,
    message=message,
  )
####


def solve_marched_attached_shock_with_ambient_pressure_closure_from_reflected_zone(
  reflected_zone: MocReflectedCharacteristicZoneResult,
  start_point_m: tuple[float, float],
  ambient_pressure_Pa: float,
  outer_downstream_flow_angle_lower_rad: float,
  outer_downstream_flow_angle_upper_rad: float,
  *,
  target_centerline_y_m: float = 0.0,
  target_centerline_flow_angle_rad: float = 0.0,
  incoming_handoff: Sequence[MocChainBoundarySample] | None = None,
  sample_count: int = 17,
  branch: ShockBranch = ShockBranch.WEAK,
  position_tolerance_m: float = 1.0e-10,
  invariant_tolerance: float = 1.0e-10,
  closure_tolerance: float = 1.0e-8,
  pressure_tolerance: float = 1.0e-8,
  tangent_tolerance: float = 1.0e-8,
  shock_angle_tolerance_rad: float = 1.0e-2,
  maximum_segment_iterations: int = 24,
  maximum_shooting_iterations: int = 40,
) -> MocReflectedZoneAmbientClosureResult:
  """Solve ambient closure while retaining reflected-zone domain coverage.

  The upstream state and pressure callbacks are owned by the converged
  reflected characteristic zone.  The returned coupling probe samples the
  exact generated shock path independently, so a closed downstream fan cannot
  hide a shock that left the solved upstream domain.
  """

  from exhaust_plume.models.moc.coupled import (
    MocAmbientClosureResult,
    MocAmbientClosureStatus,
    solve_marched_attached_shock_with_ambient_pressure_closure,
  )

  try:
    requested_pressure = float(ambient_pressure_Pa)
  except (TypeError, ValueError):
    requested_pressure = None
  try:
    requested_bracket = (
      float(outer_downstream_flow_angle_lower_rad),
      float(outer_downstream_flow_angle_upper_rad),
    )
  except (TypeError, ValueError):
    requested_bracket = None

  if not isinstance(reflected_zone, MocReflectedCharacteristicZoneResult):
    shock = _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='reflected_zone must be a MocReflectedCharacteristicZoneResult',
    )
    coupling = sample_reflected_zone_along_shock_path(reflected_zone, ())
    closure = MocAmbientClosureResult(
      status=MocAmbientClosureStatus.INVALID_INPUT,
      shock=shock,
      ambient_boundary=None,
      ambient_pressure_Pa=requested_pressure,
      outer_downstream_flow_angle_rad=None,
      outer_flow_angle_bracket=requested_bracket,
      closure_residual=None,
      shooting_iterations=0,
      message='ambient closure rejected an invalid reflected upstream zone',
    )
    return MocReflectedZoneAmbientClosureResult(
      closure=closure,
      coupling=coupling,
      message='reflected-zone ambient closure stopped before generating a shock path',
    )
  if not reflected_zone.converged:
    shock = _failure(
      MocFreeBoundaryShockStatus.UPSTREAM_FIELD_FAILURE,
      message=f'reflected upstream zone is not converged: {reflected_zone.message}',
    )
    coupling = sample_reflected_zone_along_shock_path(reflected_zone, ())
    closure = MocAmbientClosureResult(
      status=MocAmbientClosureStatus.FIELD_FAILURE,
      shock=shock,
      ambient_boundary=None,
      ambient_pressure_Pa=requested_pressure,
      outer_downstream_flow_angle_rad=None,
      outer_flow_angle_bracket=requested_bracket,
      closure_residual=None,
      shooting_iterations=0,
      message='ambient closure stopped at the unconverged reflected upstream field',
    )
    return MocReflectedZoneAmbientClosureResult(
      closure=closure,
      coupling=coupling,
      message='reflected-zone ambient closure stopped before generating a shock path',
    )

  closure = solve_marched_attached_shock_with_ambient_pressure_closure(
    reflected_zone.state_at,
    reflected_zone.static_pressure_at,
    start_point_m,
    ambient_pressure_Pa,
    outer_downstream_flow_angle_lower_rad,
    outer_downstream_flow_angle_upper_rad,
    target_centerline_y_m=target_centerline_y_m,
    target_centerline_flow_angle_rad=target_centerline_flow_angle_rad,
    incoming_handoff=incoming_handoff,
    sample_count=sample_count,
    branch=branch,
    position_tolerance_m=position_tolerance_m,
    invariant_tolerance=invariant_tolerance,
    closure_tolerance=closure_tolerance,
    pressure_tolerance=pressure_tolerance,
    tangent_tolerance=tangent_tolerance,
    shock_angle_tolerance_rad=shock_angle_tolerance_rad,
    maximum_segment_iterations=maximum_segment_iterations,
    maximum_shooting_iterations=maximum_shooting_iterations,
  )
  if closure.shock is None:
    coupling = sample_reflected_zone_along_shock_path(reflected_zone, ())
  else:
    coupling = _coupling_result_for_shock_path(
      reflected_zone,
      closure.shock,
      position_tolerance_m=position_tolerance_m,
    )
  if not coupling.converged:
    message = (
      'reflected upstream coupling did not cover the ambient-closure shock '
      f'path: {coupling.message}'
    )
  elif not closure.converged:
    message = closure.message
  else:
    message = (
      'ambient-pressure closure and reflected upstream state/pressure coupling '
      'both converged on the generated shock path'
    )
  return MocReflectedZoneAmbientClosureResult(
    closure=closure,
    coupling=coupling,
    message=message,
  )
####


def solve_reflected_boundary_trace_extension(
  reflected_boundary: MocReflectedBoundaryResult,
  upstream_pressure_Pa: float,
  *,
  target_centerline_y_m: float = 0.0,
  outer_downstream_flow_angle_rad: float = 0.05,
  sample_count: int = 17,
  branch: ShockBranch = ShockBranch.WEAK,
  position_tolerance_m: float = 1.0e-10,
  invariant_tolerance: float = 1.0e-10,
  shock_angle_tolerance_rad: float = 1.0e-2,
) -> MocFreeBoundaryShockResult:
  """Generate a shock from the terminal reflected-boundary trace.

  The terminal reflected state is extended as a constant characteristic trace
  only to provide a deterministic intermediate reference. This deliberately
  does not sample or extrapolate the reflected interior lattice; callers must
  identify the result as ``reflected-boundary-trace-extension`` until an
  upstream characteristic strip is solved between that boundary and the
  shock.
  """

  if not isinstance(reflected_boundary, MocReflectedBoundaryResult):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='reflected_boundary must be a MocReflectedBoundaryResult',
    )
  if not reflected_boundary.converged or not reflected_boundary.boundary_states:
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message=f'reflected boundary is not converged: {reflected_boundary.message}',
    )
  try:
    pressure = float(upstream_pressure_Pa)
  except (TypeError, ValueError):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='upstream_pressure_Pa must be finite and positive',
    )
  if not isfinite(pressure) or pressure <= 0.0:
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='upstream_pressure_Pa must be finite and positive',
    )
  start = reflected_boundary.boundary_points_m[-1]
  anchor = reflected_boundary.boundary_states[-1]
  if start[1] <= float(target_centerline_y_m):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='terminal reflected-boundary trace must be above the target centerline',
    )
  denominator = start[1] - float(target_centerline_y_m)

  def state_at(point: tuple[float, float]) -> CharacteristicState:
    return replace(anchor, x_m=point[0], y_m=point[1])

  def angle_at(_index: int, point: tuple[float, float]) -> float:
    fraction = (point[1] - float(target_centerline_y_m)) / denominator
    return outer_downstream_flow_angle_rad * max(0.0, min(1.0, fraction))

  result = solve_marched_attached_shock_field(
    state_at,
    lambda _point: pressure,
    start,
    target_centerline_y_m=float(target_centerline_y_m),
    downstream_flow_angle_at=angle_at,
    sample_count=sample_count,
    branch=branch,
    position_tolerance_m=position_tolerance_m,
    invariant_tolerance=invariant_tolerance,
    shock_angle_tolerance_rad=shock_angle_tolerance_rad,
  )
  if not result.converged or result.field is None:
    return result
  return replace(
    result,
    field=replace(
      result.field,
      shock_closure_status='reflected-boundary-trace-extension',
      message=(
        'reflected-boundary trace extension generated a closed post-shock '
        'field; upstream characteristic-strip coupling remains pending'
      ),
    ),
    message=(
      'terminal reflected-boundary trace reached the symmetry line through a '
      'callback-conditioned shock extension'
    ),
  )
####


def solve_marched_attached_shock_chain_cell(
  current_cell: MocChainCell,
  next_cell_index: int,
  incoming_handoff: Sequence[MocChainBoundarySample],
  *,
  start_point_m: tuple[float, float],
  end_x_m: float,
  upstream_state_at: Callable[[tuple[float, float]], CharacteristicState | None],
  upstream_pressure_at: Callable[[tuple[float, float]], float | None],
  target_centerline_y_m: float = 0.0,
  downstream_flow_angle_at: Callable[[int, tuple[float, float]], float] | None = None,
  downstream_flow_angle_rad: float | None = None,
  sample_count: int = 17,
  branch: ShockBranch = ShockBranch.WEAK,
  position_tolerance_m: float = 1.0e-10,
  invariant_tolerance: float = 1.0e-10,
  shock_angle_tolerance_rad: float = 1.0e-2,
) -> MocPostShockChainCellSolve:
  """Generate one continued chain cell from a prior terminal trace.

  This is the bridge between the marched shock solver and
  :func:`continue_post_shock_characteristic_chain`. The caller still owns the
  upstream field and downstream turn boundary condition; this helper enforces
  that the callback receives the current cell's exact typed handoff, generates
  a new shock/field, and returns the field in the chain solver's state-carrying
  result type.
  """

  if not isinstance(current_cell, MocChainCell):
    raise TypeError('current_cell must be a MocChainCell')
  if (
    isinstance(next_cell_index, bool)
    or not isinstance(next_cell_index, int)
    or next_cell_index != current_cell.cell_index + 1
  ):
    raise ValueError('next_cell_index must immediately follow current_cell.cell_index')
  handoff = tuple(incoming_handoff)
  if handoff != current_cell.continuation_boundary:
    raise ValueError('incoming_handoff must exactly match the current cell boundary')
  if len(handoff) < 3:
    raise ValueError('continued marched shock cells require at least three handoff samples')
  if not isfinite(float(end_x_m)) or end_x_m <= current_cell.end_x_m:
    raise ValueError('continued cell end_x_m must be strictly downstream of the current cell')
  if not isfinite(float(position_tolerance_m)) or position_tolerance_m <= 0.0:
    raise ValueError('position_tolerance_m must be finite and positive')
  start = _finite_point(start_point_m, 'start_point_m')
  if start[0] <= current_cell.end_x_m + position_tolerance_m:
    raise ValueError('continued shock start point must be downstream of the current cell')

  result = solve_marched_attached_shock_field(
    upstream_state_at,
    upstream_pressure_at,
    start,
    target_centerline_y_m=target_centerline_y_m,
    downstream_flow_angle_at=downstream_flow_angle_at,
    downstream_flow_angle_rad=downstream_flow_angle_rad,
    incoming_handoff=handoff,
    sample_count=sample_count,
    branch=branch,
    position_tolerance_m=position_tolerance_m,
    invariant_tolerance=invariant_tolerance,
    shock_angle_tolerance_rad=shock_angle_tolerance_rad,
  )
  if not result.converged or result.field is None:
    raise ValueError(
      f'continued marched shock cell failed: {result.status.value}: {result.message}'
    )
  return MocPostShockChainCellSolve(field=result.field, end_x_m=float(end_x_m))
####


def solve_marched_attached_shock_chain_cell_from_reflected_zone(
  current_cell: MocChainCell,
  next_cell_index: int,
  incoming_handoff: Sequence[MocChainBoundarySample],
  reflected_zone: MocReflectedCharacteristicZoneResult,
  *,
  start_point_m: tuple[float, float],
  end_x_m: float,
  target_centerline_y_m: float = 0.0,
  downstream_flow_angle_at: Callable[[int, tuple[float, float]], float] | None = None,
  downstream_flow_angle_rad: float | None = None,
  sample_count: int = 17,
  branch: ShockBranch = ShockBranch.WEAK,
  position_tolerance_m: float = 1.0e-10,
  invariant_tolerance: float = 1.0e-10,
  shock_angle_tolerance_rad: float = 1.0e-2,
  maximum_segment_iterations: int = 24,
) -> MocPostShockChainCellSolve:
  """Solve one continued chain cell from a reflected-zone upstream field.

  The prior cell's exact terminal trace is passed into the generated field and
  checked before returning a chain-cell solve.  A path that leaves the solved
  reflected zone raises with its bounded coupling status; it is never turned
  into a prescribed or reduced-order cell.
  """

  if not isinstance(current_cell, MocChainCell):
    raise TypeError('current_cell must be a MocChainCell')
  if (
    isinstance(next_cell_index, bool)
    or not isinstance(next_cell_index, int)
    or next_cell_index != current_cell.cell_index + 1
  ):
    raise ValueError('next_cell_index must immediately follow current_cell.cell_index')
  handoff = tuple(incoming_handoff)
  if handoff != current_cell.continuation_boundary:
    raise ValueError('incoming_handoff must exactly match the current cell boundary')
  if len(handoff) < 3:
    raise ValueError('continued reflected-zone shock cells require at least three handoff samples')
  if not isfinite(float(end_x_m)) or end_x_m <= current_cell.end_x_m:
    raise ValueError('continued cell end_x_m must be strictly downstream of the current cell')
  if not isfinite(float(position_tolerance_m)) or position_tolerance_m <= 0.0:
    raise ValueError('position_tolerance_m must be finite and positive')
  start = _finite_point(start_point_m, 'start_point_m')
  if start[0] <= current_cell.end_x_m + position_tolerance_m:
    raise ValueError('continued shock start point must be downstream of the current cell')

  solved = solve_marched_attached_shock_from_reflected_zone(
    reflected_zone,
    start,
    target_centerline_y_m=target_centerline_y_m,
    downstream_flow_angle_at=downstream_flow_angle_at,
    downstream_flow_angle_rad=downstream_flow_angle_rad,
    incoming_handoff=handoff,
    sample_count=sample_count,
    branch=branch,
    position_tolerance_m=position_tolerance_m,
    invariant_tolerance=invariant_tolerance,
    shock_angle_tolerance_rad=shock_angle_tolerance_rad,
    maximum_segment_iterations=maximum_segment_iterations,
  )
  if not solved.converged or solved.shock.field is None:
    raise ValueError(
      'continued reflected-zone shock cell did not converge: '
      f'{solved.shock.status.value}; {solved.message}'
    )
  field = solved.shock.field
  expected_states = tuple(sample.state for sample in handoff)
  expected_pressures = tuple(sample.total_pressure_Pa for sample in handoff)
  if (
    field.incoming_handoff_states != expected_states
    or field.incoming_handoff_total_pressure_Pa != expected_pressures
  ):
    raise ValueError(
      'continued reflected-zone field did not retain the exact incoming handoff'
    )
  return MocPostShockChainCellSolve(field=field, end_x_m=float(end_x_m))
####


def solve_uniform_attached_shock_field(
  upstream_state: CharacteristicState,
  upstream_pressure_Pa: float,
  start_point_m: tuple[float, float],
  *,
  target_centerline_y_m: float = 0.0,
  outer_downstream_flow_angle_rad: float = 0.05,
  sample_count: int = 17,
  branch: ShockBranch = ShockBranch.WEAK,
  position_tolerance_m: float = 1.0e-10,
  invariant_tolerance: float = 1.0e-10,
  shock_angle_tolerance_rad: float = 1.0e-2,
  incoming_handoff: Sequence[MocChainBoundarySample] | None = None,
) -> MocFreeBoundaryShockResult:
  """Solve the uniform-upstream linear-turn attached-shock reference case."""

  if not isinstance(upstream_state, CharacteristicState):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='upstream_state must be a CharacteristicState',
    )
  try:
    start = _finite_point(start_point_m, 'start_point_m')
    pressure = float(upstream_pressure_Pa)
    outer_angle = float(outer_downstream_flow_angle_rad)
  except (TypeError, ValueError):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='uniform reference inputs must be finite',
    )
  if not isfinite(pressure) or pressure <= 0.0:
    raise ValueError('upstream_pressure_Pa must be finite and positive')
  if not isfinite(outer_angle):
    raise ValueError('outer_downstream_flow_angle_rad must be finite')
  if start[1] <= float(target_centerline_y_m):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='uniform reference start point must be above the target centerline',
    )
  denominator = start[1] - float(target_centerline_y_m)

  def state_at(point: tuple[float, float]) -> CharacteristicState:
    return replace(upstream_state, x_m=point[0], y_m=point[1])

  def angle_at(_index: int, point: tuple[float, float]) -> float:
    fraction = (point[1] - float(target_centerline_y_m)) / denominator
    return outer_angle * max(0.0, min(1.0, fraction))

  return solve_marched_attached_shock_field(
    state_at,
    lambda _point: pressure,
    start,
    target_centerline_y_m=float(target_centerline_y_m),
    downstream_flow_angle_at=angle_at,
    incoming_handoff=incoming_handoff,
    sample_count=sample_count,
    branch=branch,
    position_tolerance_m=position_tolerance_m,
    invariant_tolerance=invariant_tolerance,
    shock_angle_tolerance_rad=shock_angle_tolerance_rad,
  )
####
