"""Solver-generated attached-shock boundaries for the planar MOC lane.

The older post-shock primitives accept an explicitly sampled shock curve.  This
module supplies the next boundary: it marches the shock tangent returned by the
attached theta-beta-Mach solve until a requested symmetry-line ordinate is
reached.  The upstream state and static-pressure fields remain explicit
callbacks so this solver does not invent a thermodynamic field or silently
reuse a lower-fidelity provider.

The uniform reference helper is a deterministic canonical fixture for the
constant-gamma planar lane.  It uses a uniform upstream state and a linear
downstream flow-angle law; its shock geometry is still generated by the
attached-shock march, not supplied as points.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from enum import Enum
from math import isfinite, sin, tan
from typing import Callable, Sequence

from exhaust_plume.models.moc.compression import solve_attached_compression_to_turn
from exhaust_plume.models.moc.chain import MocChainBoundarySample, MocChainCell
from exhaust_plume.models.moc.post_shock import (
  MocPostShockBoundaryState,
  MocPostShockChainCellSolve,
  MocPostShockCharacteristicFieldResult,
  MocPostShockFieldStatus,
  MocShockBoundaryFitResult,
  assemble_post_shock_characteristic_field,
  fit_attached_shock_boundary,
)
from exhaust_plume.models.moc.primitives import CharacteristicState
from exhaust_plume.util.aero.shock_validity import ShockBranch

__all__ = (
  'MocFreeBoundaryShockResult',
  'MocFreeBoundaryShockStatus',
  'solve_marched_attached_shock_field',
  'solve_marched_attached_shock_chain_cell',
  'solve_uniform_attached_shock_field',
)


class MocFreeBoundaryShockStatus(str, Enum):
  """Structured outcome for a solver-generated attached-shock field."""

  CONVERGED_FIELD = 'converged_free_boundary_field'
  INVALID_INPUT = 'invalid_input'
  UPSTREAM_FIELD_FAILURE = 'upstream_field_failure'
  COMPRESSION_FAILURE = 'compression_failure'
  GEOMETRY_FAILURE = 'geometry_failure'
  SHOCK_FIT_FAILURE = 'shock_fit_failure'
  FIELD_FAILURE = 'field_failure'
####


@dataclass(frozen=True, slots=True)
class MocFreeBoundaryShockResult:
  """A shock curve and post-shock field generated without prescribed points."""

  status: MocFreeBoundaryShockStatus
  shock_fit: MocShockBoundaryFitResult | None
  field: MocPostShockCharacteristicFieldResult | None
  shock_points_m: tuple[tuple[float, float], ...]
  upstream_states: tuple[CharacteristicState, ...]
  upstream_pressure_Pa: tuple[float, ...]
  downstream_flow_angles_rad: tuple[float, ...]
  shock_angle_residuals_rad: tuple[float, ...]
  maximum_shock_angle_residual_rad: float | None
  endpoint_m: tuple[float, float] | None
  message: str = ''

  @property
  def converged(self) -> bool:
    return self.status is MocFreeBoundaryShockStatus.CONVERGED_FIELD
  ####

  @property
  def physical_closure_verified(self) -> bool:
    return self.converged and self.field is not None and self.field.physical_closure_verified
  ####

  @property
  def sample_count(self) -> int:
    return len(self.shock_points_m)
  ####

  @property
  def field_status(self) -> MocPostShockFieldStatus | None:
    return None if self.field is None else self.field.status
  ####

  def as_report(self) -> dict[str, object]:
    return {
      'status': self.status.value,
      'converged': self.converged,
      'physical_closure_verified': self.physical_closure_verified,
      'sample_count': self.sample_count,
      'endpoint_m': self.endpoint_m,
      'maximum_shock_angle_residual_rad': self.maximum_shock_angle_residual_rad,
      'field_status': None if self.field_status is None else self.field_status.value,
      'message': self.message,
    }
####


@dataclass(frozen=True, slots=True)
class _MarchSample:
  point_m: tuple[float, float]
  upstream_state: CharacteristicState
  upstream_pressure_Pa: float
  downstream_flow_angle_rad: float
  shock_angle_rad: float
  boundary_state: MocPostShockBoundaryState
####


def _failure(
  status: MocFreeBoundaryShockStatus,
  *,
  shock_fit: MocShockBoundaryFitResult | None = None,
  field: MocPostShockCharacteristicFieldResult | None = None,
  shock_points: Sequence[tuple[float, float]] = (),
  upstream_states: Sequence[CharacteristicState] = (),
  upstream_pressures: Sequence[float] = (),
  downstream_angles: Sequence[float] = (),
  shock_angle_residuals: Sequence[float] = (),
  endpoint_m: tuple[float, float] | None = None,
  message: str,
) -> MocFreeBoundaryShockResult:
  residuals = tuple(float(value) for value in shock_angle_residuals)
  return MocFreeBoundaryShockResult(
    status=status,
    shock_fit=shock_fit,
    field=field,
    shock_points_m=tuple((float(point[0]), float(point[1])) for point in shock_points),
    upstream_states=tuple(upstream_states),
    upstream_pressure_Pa=tuple(float(value) for value in upstream_pressures),
    downstream_flow_angles_rad=tuple(float(value) for value in downstream_angles),
    shock_angle_residuals_rad=residuals,
    maximum_shock_angle_residual_rad=max((abs(value) for value in residuals), default=None),
    endpoint_m=endpoint_m,
    message=message,
  )
####


def _finite_point(point_m: tuple[float, float], name: str) -> tuple[float, float]:
  if len(point_m) != 2 or not all(isfinite(float(value)) for value in point_m):
    raise ValueError(f'{name} must contain two finite coordinates')
  return float(point_m[0]), float(point_m[1])
####


def solve_marched_attached_shock_field(
  upstream_state_at: Callable[[tuple[float, float]], CharacteristicState | None],
  upstream_pressure_at: Callable[[tuple[float, float]], float | None],
  start_point_m: tuple[float, float],
  *,
  target_centerline_y_m: float = 0.0,
  downstream_flow_angle_at: Callable[[int, tuple[float, float]], float] | None = None,
  downstream_flow_angle_rad: float | None = None,
  incoming_handoff: Sequence[MocChainBoundarySample] | None = None,
  sample_count: int = 17,
  branch: ShockBranch = ShockBranch.WEAK,
  position_tolerance_m: float = 1.0e-10,
  invariant_tolerance: float = 1.0e-10,
  shock_angle_tolerance_rad: float = 1.0e-2,
  maximum_segment_iterations: int = 24,
) -> MocFreeBoundaryShockResult:
  """March an attached shock from a boundary point to the symmetry line.

  At each sample the upstream callback supplies the local state and static
  pressure.  The downstream flow-angle callback supplies the local turn
  boundary condition.  The shock tangent is then
  ``theta_upstream - beta``; a trapezoidal march in ``x(y)`` generates the
  next point.  The generated samples are rechecked by
  :func:`fit_attached_shock_boundary` before the complete post-shock field is
  assembled.

  Exactly one of ``downstream_flow_angle_at`` and
  ``downstream_flow_angle_rad`` may be supplied.  A scalar angle is useful for
  a uniform boundary, but a nonzero angle profile is required to produce a
  finite characteristic-field area in the uniform reference helper. When
  ``incoming_handoff`` is supplied, the assembled field records the exact
  prior terminal trace as consumed state; it does not use that trace as a
  shock curve.
  """

  try:
    start = _finite_point(start_point_m, 'start_point_m')
    target_y = float(target_centerline_y_m)
  except (TypeError, ValueError):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='start point and target centerline ordinate must be finite',
    )
  if not isfinite(target_y) or target_y >= start[1]:
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='target centerline ordinate must be below the shock start',
    )
  if not callable(upstream_state_at) or not callable(upstream_pressure_at):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='upstream state and pressure providers must be callable',
    )
  if (downstream_flow_angle_at is None) == (downstream_flow_angle_rad is None):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='supply exactly one downstream flow-angle provider',
    )
  if not isinstance(branch, ShockBranch):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='branch must be a ShockBranch',
    )
  if isinstance(sample_count, bool) or not isinstance(sample_count, int) or sample_count < 3:
    raise ValueError('sample_count must be an integer of at least three')
  for name, value in (
    ('position_tolerance_m', position_tolerance_m),
    ('invariant_tolerance', invariant_tolerance),
    ('shock_angle_tolerance_rad', shock_angle_tolerance_rad),
  ):
    if not isfinite(float(value)) or value <= 0.0:
      raise ValueError(f'{name} must be finite and positive')
  if (
    isinstance(maximum_segment_iterations, bool)
    or not isinstance(maximum_segment_iterations, int)
    or maximum_segment_iterations < 1
  ):
    raise ValueError('maximum_segment_iterations must be a positive integer')
  ####

  dy = (target_y - start[1]) / (sample_count - 1)
  points: list[tuple[float, float]] = []
  upstream_states: list[CharacteristicState] = []
  upstream_pressures: list[float] = []
  downstream_angles: list[float] = []

  def evaluate(point: tuple[float, float], index: int) -> tuple[_MarchSample | None, str | None, MocFreeBoundaryShockStatus]:
    try:
      state = upstream_state_at(point)
      pressure = upstream_pressure_at(point)
    except (ArithmeticError, FloatingPointError, TypeError, ValueError) as error:
      return None, f'upstream field callback failed at sample {index}: {error}', MocFreeBoundaryShockStatus.UPSTREAM_FIELD_FAILURE
    if not isinstance(state, CharacteristicState):
      return None, f'upstream field callback returned no CharacteristicState at sample {index}', MocFreeBoundaryShockStatus.UPSTREAM_FIELD_FAILURE
    if state.x_m != point[0] or state.y_m != point[1]:
      if (
        abs(state.x_m - point[0]) > position_tolerance_m
        or abs(state.y_m - point[1]) > position_tolerance_m
      ):
        return None, f'upstream state {index} does not lie at the marched shock point', MocFreeBoundaryShockStatus.UPSTREAM_FIELD_FAILURE
      state = replace(state, x_m=point[0], y_m=point[1])
    if pressure is None or not isfinite(float(pressure)) or float(pressure) <= 0.0:
      return None, f'upstream pressure provider returned an invalid value at sample {index}', MocFreeBoundaryShockStatus.UPSTREAM_FIELD_FAILURE
    if downstream_flow_angle_at is not None:
      try:
        target_angle = float(downstream_flow_angle_at(index, point))
      except (ArithmeticError, FloatingPointError, TypeError, ValueError) as error:
        return None, f'downstream angle callback failed at sample {index}: {error}', MocFreeBoundaryShockStatus.INVALID_INPUT
    else:
      assert downstream_flow_angle_rad is not None
      target_angle = float(downstream_flow_angle_rad)
    if not isfinite(target_angle):
      return None, f'downstream flow angle {index} must be finite', MocFreeBoundaryShockStatus.INVALID_INPUT
    turn = target_angle - state.theta_rad
    if turn <= 0.0:
      return None, f'sample {index} does not require a positive compression turn', MocFreeBoundaryShockStatus.COMPRESSION_FAILURE
    compression = solve_attached_compression_to_turn(
      upstream_mach=state.mach,
      gamma=state.gamma,
      upstream_pressure_Pa=float(pressure),
      target_turn_rad=turn,
      branch=branch,
    )
    if (
      not compression.converged
      or compression.beta_rad is None
      or compression.downstream_mach is None
      or compression.upstream_total_pressure_Pa is None
      or compression.downstream_total_pressure_Pa is None
    ):
      return None, f'attached compression failed at sample {index}: {compression.message}', MocFreeBoundaryShockStatus.COMPRESSION_FAILURE
    shock_angle = state.theta_rad - compression.beta_rad
    if not isfinite(shock_angle) or sin(shock_angle) >= -position_tolerance_m:
      return None, f'shock tangent at sample {index} does not travel toward the centerline', MocFreeBoundaryShockStatus.GEOMETRY_FAILURE
    try:
      boundary_state = MocPostShockBoundaryState(
        point_m=point,
        state=CharacteristicState(
          x_m=point[0],
          y_m=point[1],
          theta_rad=target_angle,
          mach=compression.downstream_mach,
          gamma=state.gamma,
        ),
        upstream_total_pressure_Pa=compression.upstream_total_pressure_Pa,
        downstream_total_pressure_Pa=compression.downstream_total_pressure_Pa,
      )
    except (TypeError, ValueError) as error:
      return None, f'downstream shock state {index} is invalid: {error}', MocFreeBoundaryShockStatus.COMPRESSION_FAILURE
    return (
      _MarchSample(
        point_m=point,
        upstream_state=state,
        upstream_pressure_Pa=float(pressure),
        downstream_flow_angle_rad=target_angle,
        shock_angle_rad=shock_angle,
        boundary_state=boundary_state,
      ),
      None,
      MocFreeBoundaryShockStatus.CONVERGED_FIELD,
    )

  current_point = start
  current_sample, error, error_status = evaluate(current_point, 0)
  if current_sample is None:
    return _failure(error_status, message=error or 'initial shock sample failed')
  points.append(current_sample.point_m)
  upstream_states.append(current_sample.upstream_state)
  upstream_pressures.append(current_sample.upstream_pressure_Pa)
  downstream_angles.append(current_sample.downstream_flow_angle_rad)
  ####

  for index in range(1, sample_count):
    next_y = start[1] + index * dy
    tangent = current_sample.shock_angle_rad
    next_x = current_point[0] + dy / tan(tangent)
    next_sample: _MarchSample | None = None
    for _ in range(maximum_segment_iterations):
      candidate_point = (float(next_x), float(next_y))
      candidate_sample, error, error_status = evaluate(candidate_point, index)
      if candidate_sample is None:
        return _failure(
          error_status,
          shock_points=points,
          upstream_states=upstream_states,
          upstream_pressures=upstream_pressures,
          downstream_angles=downstream_angles,
          endpoint_m=points[-1] if points else None,
          message=error or f'shock sample {index} failed',
        )
      next_sample = candidate_sample
      next_tangent = candidate_sample.shock_angle_rad
      updated_x = current_point[0] + dy * 0.5 * (1.0 / tan(tangent) + 1.0 / tan(next_tangent))
      if abs(updated_x - next_x) <= position_tolerance_m:
        next_x = updated_x
        final_sample, final_error, final_status = evaluate(
          (float(next_x), float(next_y)),
          index,
        )
        if final_sample is None:
          return _failure(
            final_status,
            shock_points=points,
            upstream_states=upstream_states,
            upstream_pressures=upstream_pressures,
            downstream_angles=downstream_angles,
            endpoint_m=points[-1] if points else None,
            message=final_error or f'shock sample {index} failed at its converged endpoint',
          )
        next_sample = final_sample
        break
      next_x = updated_x
    else:
      return _failure(
        MocFreeBoundaryShockStatus.GEOMETRY_FAILURE,
        shock_points=points,
        upstream_states=upstream_states,
        upstream_pressures=upstream_pressures,
        downstream_angles=downstream_angles,
        endpoint_m=points[-1] if points else None,
        message=f'shock segment {index - 1} did not converge to a tangent-consistent endpoint',
      )
    if next_sample is None:
      return _failure(
        MocFreeBoundaryShockStatus.GEOMETRY_FAILURE,
        shock_points=points,
        upstream_states=upstream_states,
        upstream_pressures=upstream_pressures,
        downstream_angles=downstream_angles,
        endpoint_m=points[-1] if points else None,
        message=f'shock segment {index - 1} produced no endpoint sample',
      )
    current_point = (float(next_x), float(next_y))
    if current_point[0] <= points[-1][0] + position_tolerance_m:
      return _failure(
        MocFreeBoundaryShockStatus.GEOMETRY_FAILURE,
        shock_points=points,
        upstream_states=upstream_states,
        upstream_pressures=upstream_pressures,
        downstream_angles=downstream_angles,
        endpoint_m=points[-1] if points else None,
        message=f'shock sample {index} is not strictly downstream',
      )
    points.append(current_point)
    upstream_states.append(replace(next_sample.upstream_state, x_m=current_point[0], y_m=current_point[1]))
    upstream_pressures.append(next_sample.upstream_pressure_Pa)
    downstream_angles.append(next_sample.downstream_flow_angle_rad)
    current_sample = replace(
      next_sample,
      point_m=current_point,
      upstream_state=replace(
        next_sample.upstream_state,
        x_m=current_point[0],
        y_m=current_point[1],
      ),
      boundary_state=replace(
        next_sample.boundary_state,
        point_m=current_point,
        state=replace(
          next_sample.boundary_state.state,
          x_m=current_point[0],
          y_m=current_point[1],
        ),
      ),
    )
  ####

  shock_fit = fit_attached_shock_boundary(
    upstream_states,
    upstream_pressures,
    points,
    downstream_angles,
    branch=branch,
    position_tolerance_m=position_tolerance_m,
    shock_angle_tolerance_rad=shock_angle_tolerance_rad,
  )
  if not shock_fit.converged:
    return _failure(
      MocFreeBoundaryShockStatus.SHOCK_FIT_FAILURE,
      shock_fit=shock_fit,
      shock_points=points,
      upstream_states=upstream_states,
      upstream_pressures=upstream_pressures,
      downstream_angles=downstream_angles,
      shock_angle_residuals=shock_fit.shock_angle_residuals_rad,
      endpoint_m=points[-1],
      message=f'generated shock boundary failed attached-shock verification: {shock_fit.message}',
    )
  field = assemble_post_shock_characteristic_field(
    shock_fit,
    incoming_handoff=incoming_handoff,
    position_tolerance_m=position_tolerance_m,
    invariant_tolerance=invariant_tolerance,
    shock_angle_tolerance_rad=shock_angle_tolerance_rad,
  )
  if not field.converged:
    return _failure(
      MocFreeBoundaryShockStatus.FIELD_FAILURE,
      shock_fit=shock_fit,
      field=field,
      shock_points=points,
      upstream_states=upstream_states,
      upstream_pressures=upstream_pressures,
      downstream_angles=downstream_angles,
      shock_angle_residuals=shock_fit.shock_angle_residuals_rad,
      endpoint_m=points[-1],
      message=f'generated shock boundary did not close its characteristic field: {field.message}',
    )
  field = replace(
    field,
    shock_closure_status='solver-generated-marched-attached-shock',
    message=(
      'solver-generated marched attached shock and post-shock C+/C- field '
      'converged with explicit shock and centerline boundary edges'
    ),
  )
  return MocFreeBoundaryShockResult(
    status=MocFreeBoundaryShockStatus.CONVERGED_FIELD,
    shock_fit=shock_fit,
    field=field,
    shock_points_m=tuple(points),
    upstream_states=tuple(upstream_states),
    upstream_pressure_Pa=tuple(upstream_pressures),
    downstream_flow_angles_rad=tuple(downstream_angles),
    shock_angle_residuals_rad=shock_fit.shock_angle_residuals_rad,
    maximum_shock_angle_residual_rad=shock_fit.maximum_shock_angle_residual_rad,
    endpoint_m=points[-1],
    message=(
      'solver-generated attached-shock boundary reached the symmetry line '
      'and closed the post-shock characteristic field'
    ),
  )
####


def solve_marched_attached_shock_chain_cell(
  current_cell: MocChainCell,
  next_cell_index: int,
  incoming_handoff: Sequence[MocChainBoundarySample],
  *,
  start_point_m: tuple[float, float],
  end_x_m: float,
  upstream_state_at: Callable[[tuple[float, float]], CharacteristicState | None],
  upstream_pressure_at: Callable[[tuple[float, float]], float | None],
  target_centerline_y_m: float = 0.0,
  downstream_flow_angle_at: Callable[[int, tuple[float, float]], float] | None = None,
  downstream_flow_angle_rad: float | None = None,
  sample_count: int = 17,
  branch: ShockBranch = ShockBranch.WEAK,
  position_tolerance_m: float = 1.0e-10,
  invariant_tolerance: float = 1.0e-10,
  shock_angle_tolerance_rad: float = 1.0e-2,
) -> MocPostShockChainCellSolve:
  """Generate one continued chain cell from a prior terminal trace.

  This is the bridge between the marched shock solver and
  :func:`continue_post_shock_characteristic_chain`. The caller still owns the
  upstream field and downstream turn boundary condition; this helper enforces
  that the callback receives the current cell's exact typed handoff, generates
  a new shock/field, and returns the field in the chain solver's state-carrying
  result type.
  """

  if not isinstance(current_cell, MocChainCell):
    raise TypeError('current_cell must be a MocChainCell')
  if (
    isinstance(next_cell_index, bool)
    or not isinstance(next_cell_index, int)
    or next_cell_index != current_cell.cell_index + 1
  ):
    raise ValueError('next_cell_index must immediately follow current_cell.cell_index')
  handoff = tuple(incoming_handoff)
  if handoff != current_cell.continuation_boundary:
    raise ValueError('incoming_handoff must exactly match the current cell boundary')
  if len(handoff) < 3:
    raise ValueError('continued marched shock cells require at least three handoff samples')
  if not isfinite(float(end_x_m)) or end_x_m <= current_cell.end_x_m:
    raise ValueError('continued cell end_x_m must be strictly downstream of the current cell')
  if not isfinite(float(position_tolerance_m)) or position_tolerance_m <= 0.0:
    raise ValueError('position_tolerance_m must be finite and positive')
  start = _finite_point(start_point_m, 'start_point_m')
  if start[0] <= current_cell.end_x_m + position_tolerance_m:
    raise ValueError('continued shock start point must be downstream of the current cell')

  result = solve_marched_attached_shock_field(
    upstream_state_at,
    upstream_pressure_at,
    start,
    target_centerline_y_m=target_centerline_y_m,
    downstream_flow_angle_at=downstream_flow_angle_at,
    downstream_flow_angle_rad=downstream_flow_angle_rad,
    incoming_handoff=handoff,
    sample_count=sample_count,
    branch=branch,
    position_tolerance_m=position_tolerance_m,
    invariant_tolerance=invariant_tolerance,
    shock_angle_tolerance_rad=shock_angle_tolerance_rad,
  )
  if not result.converged or result.field is None:
    raise ValueError(
      f'continued marched shock cell failed: {result.status.value}: {result.message}'
    )
  return MocPostShockChainCellSolve(field=result.field, end_x_m=float(end_x_m))
####


def solve_uniform_attached_shock_field(
  upstream_state: CharacteristicState,
  upstream_pressure_Pa: float,
  start_point_m: tuple[float, float],
  *,
  target_centerline_y_m: float = 0.0,
  outer_downstream_flow_angle_rad: float = 0.05,
  sample_count: int = 17,
  branch: ShockBranch = ShockBranch.WEAK,
  position_tolerance_m: float = 1.0e-10,
  invariant_tolerance: float = 1.0e-10,
  shock_angle_tolerance_rad: float = 1.0e-2,
  incoming_handoff: Sequence[MocChainBoundarySample] | None = None,
) -> MocFreeBoundaryShockResult:
  """Solve the uniform-upstream linear-turn attached-shock reference case."""

  if not isinstance(upstream_state, CharacteristicState):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='upstream_state must be a CharacteristicState',
    )
  try:
    start = _finite_point(start_point_m, 'start_point_m')
    pressure = float(upstream_pressure_Pa)
    outer_angle = float(outer_downstream_flow_angle_rad)
  except (TypeError, ValueError):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='uniform reference inputs must be finite',
    )
  if not isfinite(pressure) or pressure <= 0.0:
    raise ValueError('upstream_pressure_Pa must be finite and positive')
  if not isfinite(outer_angle):
    raise ValueError('outer_downstream_flow_angle_rad must be finite')
  if start[1] <= float(target_centerline_y_m):
    return _failure(
      MocFreeBoundaryShockStatus.INVALID_INPUT,
      message='uniform reference start point must be above the target centerline',
    )
  denominator = start[1] - float(target_centerline_y_m)

  def state_at(point: tuple[float, float]) -> CharacteristicState:
    return replace(upstream_state, x_m=point[0], y_m=point[1])

  def angle_at(_index: int, point: tuple[float, float]) -> float:
    fraction = (point[1] - float(target_centerline_y_m)) / denominator
    return outer_angle * max(0.0, min(1.0, fraction))

  return solve_marched_attached_shock_field(
    state_at,
    lambda _point: pressure,
    start,
    target_centerline_y_m=float(target_centerline_y_m),
    downstream_flow_angle_at=angle_at,
    incoming_handoff=incoming_handoff,
    sample_count=sample_count,
    branch=branch,
    position_tolerance_m=position_tolerance_m,
    invariant_tolerance=invariant_tolerance,
    shock_angle_tolerance_rad=shock_angle_tolerance_rad,
  )
####
