"""Solver-owned variable-entropy/free-boundary reference for the MOC lane.

The terminal shock interface carries a nonuniform total-pressure (entropy)
profile, while the existing scalar mixed-regime references either prescribe a
uniform isentrope or accept a caller-owned source map.  This module removes
that caller-owned map from the next research seam.  It builds a deterministic
streamline-aligned downstream field from the exact terminal interface and
solves the ambient-pressure free boundary from the stream-tube mass-flux
relation.

This is intentionally an intermediate fidelity model.  It solves steady
continuity, constant total enthalpy, shock-interface entropy transport, and a
local ambient/free-boundary condition on a mapped planar mesh.  It reports
  both primitive transverse momentum and independently auditable normalized
  conservative mass-momentum-energy residuals instead of hiding the fact that
  the mapped stream-tube law is not yet a coupled 2-D Euler/MOC solve.
Consequently the result remains research-only, cannot seed another
supersonic cell, and does not change any fast visual, reduced-order,
signature, ray, or FPA provider.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from math import atan2, cos, hypot, isfinite, log, sin, sqrt, tan
from typing import Any, Sequence

from exhaust_plume.models.moc.mixed_regime import (
  MocMixedRegimeBoundaryResult,
  MocMixedRegimeControlSection,
  MocMixedRegimeControlSectionResult,
  MocMixedRegimeDownstreamConditionKind,
  MocMixedRegimeDownstreamConditionResult,
  MocMixedRegimeDownstreamPerimeterSpec,
  MocMixedRegimeFieldResult,
  MocMixedRegimeFieldSample,
  MocMixedRegimeFieldStatus,
  MocMixedRegimePerimeterRequest,
  validate_mixed_regime_boundary,
  validate_mixed_regime_control_section,
  validate_mixed_regime_downstream_condition,
)
from exhaust_plume.models.moc.mixed_regime_entropy import (
  MocMixedRegimeEntropyHandoffResult,
)
from exhaust_plume.models.moc.topology import validate_moc_mesh
from exhaust_plume.models.moc.zone import MocCharacteristicCell

__all__ = (
  'MocMixedRegimeVariableEntropyFreeBoundaryStatus',
  'MocMixedRegimeVariableEntropyFreeBoundaryResult',
  'solve_mixed_regime_variable_entropy_free_boundary',
)


Point = tuple[float, float]
VARIABLE_ENTROPY_MODEL = (
  'solver-owned-streamline-variable-entropy-free-boundary-reference'
)


class MocMixedRegimeVariableEntropyFreeBoundaryStatus(str, Enum):
  """Outcome of the mapped variable-entropy/free-boundary reference."""

  CONVERGED_REFERENCE = (
    'converged-solver-owned-variable-entropy-free-boundary-reference'
  )
  INVALID_INPUT = 'invalid_input'
  HANDOFF_FAILURE = 'variable-entropy-handoff-failure'
  CONTROL_SECTION_FAILURE = 'variable-entropy-control-section-failure'
  PRESSURE_UNREACHABLE = 'variable-entropy-pressure-unreachable'
  GEOMETRY_FAILURE = 'variable-entropy-free-boundary-geometry-failure'
  FIELD_FAILURE = 'variable-entropy-field-failure'
  FREE_BOUNDARY_FAILURE = 'variable-entropy-free-boundary-failure'
  RESIDUAL_FAILURE = 'variable-entropy-residual-failure'
####


@dataclass(frozen=True, slots=True)
class MocMixedRegimeVariableEntropyFreeBoundaryResult:
  """Auditable result for one solver-owned entropy/free-boundary solve.

  ``source_arc_length_m`` and ``streamline_ids`` are generated by this
  solver from the ordered control section; they are retained so an
  independent measurement can audit the mapping.  They are not caller
  inputs.  The field is stored in the scalar mixed-regime container only as a
  mesh-backed reference; it is not a ``CharacteristicState`` field.
  """

  status: MocMixedRegimeVariableEntropyFreeBoundaryStatus
  request: MocMixedRegimePerimeterRequest
  handoff: MocMixedRegimeEntropyHandoffResult | None
  control_section: MocMixedRegimeControlSection
  control_section_validation: MocMixedRegimeControlSectionResult | None
  ambient_pressure_Pa: float
  downstream_length_m: float
  initial_outlet_height_m: float
  inlet_height_m: float
  outlet_height_m: float | None
  axial_station_count: int
  transverse_station_count: int
  free_boundary_points_m: tuple[Point, ...] = ()
  free_boundary_heights_m: tuple[float, ...] = ()
  initial_free_boundary_heights_m: tuple[float, ...] = ()
  transverse_fractions: tuple[float, ...] = ()
  source_arc_length_by_transverse_index_m: tuple[float, ...] = ()
  source_total_pressure_by_transverse_index_Pa: tuple[float, ...] = ()
  source_gamma_by_transverse_index: tuple[float, ...] = ()
  source_arc_length_m: tuple[float, ...] = ()
  streamline_ids: tuple[int, ...] = ()
  transported_total_pressure_Pa: tuple[float, ...] = ()
  iteration_count: int = 0
  residual_history: tuple[float, ...] = ()
  maximum_free_boundary_pressure_residual_Pa: float | None = None
  maximum_free_boundary_tangent_residual_rad: float | None = None
  maximum_continuity_residual: float | None = None
  maximum_connector_continuity_residual: float | None = None
  maximum_entrance_continuity_residual: float | None = None
  maximum_entropy_advection_residual: float | None = None
  maximum_entrance_entropy_advection_residual: float | None = None
  maximum_transverse_momentum_residual: float | None = None
  maximum_conservative_mass_residual: float | None = None
  maximum_conservative_streamwise_momentum_residual: float | None = None
  maximum_conservative_transverse_momentum_residual: float | None = None
  maximum_conservative_energy_residual: float | None = None
  maximum_conservative_euler_residual: float | None = None
  conservative_euler_residuals_measured: bool = False
  maximum_mass_flow_residual: float | None = None
  maximum_entrance_mass_flow_residual: float | None = None
  maximum_control_source_pressure_residual_Pa: float | None = None
  maximum_control_source_gamma_residual: float | None = None
  maximum_inlet_angle_law_residual_rad: float | None = None
  source_streamline_mapping_verified: bool = False
  entropy_transport_verified: bool = False
  continuity_verified: bool = False
  free_boundary_condition_verified: bool = False
  field_topology_verified: bool = False
  canonical_euler_verified: bool = False
  boundary: MocMixedRegimeBoundaryResult | None = None
  downstream_condition: MocMixedRegimeDownstreamConditionResult | None = None
  field: MocMixedRegimeFieldResult | None = None
  model: str = VARIABLE_ENTROPY_MODEL
  message: str = ''

  def __post_init__(self) -> None:
    if not isinstance(
      self.status,
      MocMixedRegimeVariableEntropyFreeBoundaryStatus,
    ):
      raise TypeError(
        'status must be a '
        'MocMixedRegimeVariableEntropyFreeBoundaryStatus'
      )
    ####
    if not isinstance(self.request, MocMixedRegimePerimeterRequest):
      raise TypeError('request must be a MocMixedRegimePerimeterRequest')
    ####
    if self.handoff is not None and not isinstance(
      self.handoff,
      MocMixedRegimeEntropyHandoffResult,
    ):
      raise TypeError(
        'handoff must be a MocMixedRegimeEntropyHandoffResult or None'
      )
    ####
    if not isinstance(self.control_section, MocMixedRegimeControlSection):
      raise TypeError(
        'control_section must be a MocMixedRegimeControlSection'
      )
    ####
    if self.control_section_validation is not None and not isinstance(
      self.control_section_validation,
      MocMixedRegimeControlSectionResult,
    ):
      raise TypeError(
        'control_section_validation must be a '
        'MocMixedRegimeControlSectionResult or None'
      )
    ####
    for name, value in (
      ('ambient_pressure_Pa', self.ambient_pressure_Pa),
      ('downstream_length_m', self.downstream_length_m),
      ('initial_outlet_height_m', self.initial_outlet_height_m),
      ('inlet_height_m', self.inlet_height_m),
    ):
      numeric = float(value)
      if not isfinite(numeric) or numeric <= 0.0:
        raise ValueError(f'{name} must be finite and positive')
      ####
      object.__setattr__(self, name, numeric)
    ####
    if self.outlet_height_m is not None:
      outlet_height = float(self.outlet_height_m)
      if not isfinite(outlet_height) or outlet_height <= 0.0:
        raise ValueError('outlet_height_m must be finite and positive')
      ####
      object.__setattr__(self, 'outlet_height_m', outlet_height)
    ####
    for name, minimum in (
      ('axial_station_count', 5),
      ('transverse_station_count', 3),
      ('iteration_count', 0),
    ):
      value = getattr(self, name)
      if isinstance(value, bool) or not isinstance(value, int) or value < minimum:
        raise ValueError(
          f'{name} must be an integer greater than or equal to {minimum}'
        )
      ####
    ####
    for name in (
      'free_boundary_points_m',
      'free_boundary_heights_m',
      'initial_free_boundary_heights_m',
      'transverse_fractions',
      'source_arc_length_by_transverse_index_m',
      'source_total_pressure_by_transverse_index_Pa',
      'source_gamma_by_transverse_index',
      'source_arc_length_m',
      'transported_total_pressure_Pa',
      'residual_history',
    ):
      values = getattr(self, name)
      if name == 'free_boundary_points_m':
        normalised = tuple(
          (float(point[0]), float(point[1])) for point in values
        )
        if any(not all(isfinite(value) for value in point) for point in normalised):
          raise ValueError('free_boundary_points_m must contain finite points')
        ####
        object.__setattr__(self, name, normalised)
        continue
      ####
      normalised_values = tuple(float(value) for value in values)
      if any(not isfinite(value) for value in normalised_values):
        raise ValueError(f'{name} must contain finite values')
      ####
      object.__setattr__(self, name, normalised_values)
    ####
    for name in (
      'maximum_free_boundary_pressure_residual_Pa',
      'maximum_free_boundary_tangent_residual_rad',
      'maximum_continuity_residual',
      'maximum_connector_continuity_residual',
      'maximum_entrance_continuity_residual',
      'maximum_entropy_advection_residual',
      'maximum_entrance_entropy_advection_residual',
      'maximum_transverse_momentum_residual',
      'maximum_conservative_mass_residual',
      'maximum_conservative_streamwise_momentum_residual',
      'maximum_conservative_transverse_momentum_residual',
      'maximum_conservative_energy_residual',
      'maximum_conservative_euler_residual',
      'maximum_mass_flow_residual',
      'maximum_entrance_mass_flow_residual',
      'maximum_control_source_pressure_residual_Pa',
      'maximum_control_source_gamma_residual',
      'maximum_inlet_angle_law_residual_rad',
    ):
      value = getattr(self, name)
      if value is not None:
        numeric = float(value)
        if not isfinite(numeric) or numeric < 0.0:
          raise ValueError(f'{name} must be finite and nonnegative')
        ####
        object.__setattr__(self, name, numeric)
      ####
    ####
    for name in (
      'source_streamline_mapping_verified',
      'entropy_transport_verified',
      'continuity_verified',
      'free_boundary_condition_verified',
      'field_topology_verified',
      'canonical_euler_verified',
      'conservative_euler_residuals_measured',
    ):
      if not isinstance(getattr(self, name), bool):
        raise TypeError(f'{name} must be a bool')
      ####
    ####
    if self.boundary is not None and not isinstance(
      self.boundary,
      MocMixedRegimeBoundaryResult,
    ):
      raise TypeError(
        'boundary must be a MocMixedRegimeBoundaryResult or None'
      )
    ####
    if self.downstream_condition is not None and not isinstance(
      self.downstream_condition,
      MocMixedRegimeDownstreamConditionResult,
    ):
      raise TypeError(
        'downstream_condition must be a '
        'MocMixedRegimeDownstreamConditionResult or None'
      )
    ####
    if self.field is not None and not isinstance(
      self.field,
      MocMixedRegimeFieldResult,
    ):
      raise TypeError('field must be a MocMixedRegimeFieldResult or None')
    ####
    if any(
      isinstance(streamline_id, bool)
      or not isinstance(streamline_id, int)
      or streamline_id < 0
      for streamline_id in self.streamline_ids
    ):
      raise ValueError('streamline_ids must contain nonnegative integers')
    ####
    if self.boundary is not None and self.field is not None and (
      self.field.boundary != self.boundary
    ):
      raise ValueError('field must retain the exact variable-entropy boundary')
    ####
    model = str(self.model)
    if not model:
      raise ValueError('model must be a non-empty string')
    ####
    object.__setattr__(self, 'model', model)
    object.__setattr__(self, 'message', str(self.message))
  ####

  @property
  def converged(self) -> bool:
    """Whether the local solver-owned reference passed its declared gates."""

    return bool(
      self.status
      is MocMixedRegimeVariableEntropyFreeBoundaryStatus.CONVERGED_REFERENCE
      and self.handoff is not None
      and self.handoff.converged
      and self.boundary is not None
      and self.boundary.converged
      and self.downstream_condition is not None
      and self.downstream_condition.converged
      and self.field is not None
      and self.field.converged
      and self.source_streamline_mapping_verified
      and self.entropy_transport_verified
      and self.free_boundary_condition_verified
      and self.field_topology_verified
    )
  ####

  @property
  def physical_closure_verified(self) -> bool:
    """The mapped reference is not canonical reflected-MOC closure."""

    return False
  ####

  @property
  def canonical_free_boundary_verified(self) -> bool:
    """The mapped stream-tube envelope is not the canonical free boundary."""

    return False
  ####

  @property
  def chain_promotion_blocked(self) -> bool:
    return True
  ####

  @property
  def production_claim_allowed(self) -> bool:
    return False
  ####

  @property
  def node_count(self) -> int:
    return 0 if self.field is None else self.field.node_count
  ####

  @property
  def cell_count(self) -> int:
    return 0 if self.field is None else self.field.cell_count
  ####

  def as_report(self) -> dict[str, Any]:
    return {
      'status': self.status.value,
      'converged': self.converged,
      'model': self.model,
      'request_terminal_point_m': self.request.terminal_point_m,
      'ambient_pressure_Pa': self.ambient_pressure_Pa,
      'downstream_length_m': self.downstream_length_m,
      'initial_outlet_height_m': self.initial_outlet_height_m,
      'inlet_height_m': self.inlet_height_m,
      'outlet_height_m': self.outlet_height_m,
      'axial_station_count': self.axial_station_count,
      'transverse_station_count': self.transverse_station_count,
      'free_boundary_points_m': self.free_boundary_points_m,
      'free_boundary_heights_m': self.free_boundary_heights_m,
      'initial_free_boundary_heights_m': self.initial_free_boundary_heights_m,
      'transverse_fractions': self.transverse_fractions,
      'source_arc_length_by_transverse_index_m': (
        self.source_arc_length_by_transverse_index_m
      ),
      'source_total_pressure_by_transverse_index_Pa': (
        self.source_total_pressure_by_transverse_index_Pa
      ),
      'source_gamma_by_transverse_index': self.source_gamma_by_transverse_index,
      'source_arc_length_m': self.source_arc_length_m,
      'streamline_ids': self.streamline_ids,
      'transported_total_pressure_Pa': self.transported_total_pressure_Pa,
      'iteration_count': self.iteration_count,
      'residual_history': self.residual_history,
      'maximum_free_boundary_pressure_residual_Pa': (
        self.maximum_free_boundary_pressure_residual_Pa
      ),
      'maximum_free_boundary_tangent_residual_rad': (
        self.maximum_free_boundary_tangent_residual_rad
      ),
      'maximum_continuity_residual': self.maximum_continuity_residual,
      'maximum_connector_continuity_residual': (
        self.maximum_connector_continuity_residual
      ),
      'maximum_entrance_continuity_residual': (
        self.maximum_entrance_continuity_residual
      ),
      'maximum_entropy_advection_residual': (
        self.maximum_entropy_advection_residual
      ),
      'maximum_entrance_entropy_advection_residual': (
        self.maximum_entrance_entropy_advection_residual
      ),
      'maximum_transverse_momentum_residual': (
        self.maximum_transverse_momentum_residual
      ),
      'maximum_conservative_mass_residual': (
        self.maximum_conservative_mass_residual
      ),
      'maximum_conservative_streamwise_momentum_residual': (
        self.maximum_conservative_streamwise_momentum_residual
      ),
      'maximum_conservative_transverse_momentum_residual': (
        self.maximum_conservative_transverse_momentum_residual
      ),
      'maximum_conservative_energy_residual': (
        self.maximum_conservative_energy_residual
      ),
      'maximum_conservative_euler_residual': (
        self.maximum_conservative_euler_residual
      ),
      'conservative_euler_residuals_measured': (
        self.conservative_euler_residuals_measured
      ),
      'maximum_mass_flow_residual': self.maximum_mass_flow_residual,
      'maximum_entrance_mass_flow_residual': (
        self.maximum_entrance_mass_flow_residual
      ),
      'maximum_control_source_pressure_residual_Pa': (
        self.maximum_control_source_pressure_residual_Pa
      ),
      'maximum_control_source_gamma_residual': (
        self.maximum_control_source_gamma_residual
      ),
      'maximum_inlet_angle_law_residual_rad': (
        self.maximum_inlet_angle_law_residual_rad
      ),
      'source_streamline_mapping_verified': (
        self.source_streamline_mapping_verified
      ),
      'entropy_transport_verified': self.entropy_transport_verified,
      'continuity_verified': self.continuity_verified,
      'free_boundary_condition_verified': self.free_boundary_condition_verified,
      'field_topology_verified': self.field_topology_verified,
      'canonical_euler_verified': self.canonical_euler_verified,
      'physical_closure_verified': self.physical_closure_verified,
      'canonical_free_boundary_verified': self.canonical_free_boundary_verified,
      'chain_promotion_blocked': self.chain_promotion_blocked,
      'production_claim_allowed': self.production_claim_allowed,
      'handoff': None if self.handoff is None else self.handoff.as_report(),
      'control_section': self.control_section.as_report(),
      'control_section_validation': (
        None
        if self.control_section_validation is None
        else self.control_section_validation.as_report()
      ),
      'boundary': None if self.boundary is None else self.boundary.as_report(),
      'downstream_condition': (
        None
        if self.downstream_condition is None
        else self.downstream_condition.as_report()
      ),
      'field': None if self.field is None else self.field.as_report(),
      'message': self.message,
      'claim_status': (
        'solver-owned-streamline-variable-entropy-free-boundary-reference; '
        'mapped-continuity-and-entropy-evidence-only; canonical-2d-euler-'
        'free-boundary-and-external-validation-pending'
      ),
    }
  ####
####


@dataclass(frozen=True, slots=True)
class _VariableEntropyCandidate:
  boundary: MocMixedRegimeBoundaryResult
  downstream_condition: MocMixedRegimeDownstreamConditionResult
  perimeter_spec: MocMixedRegimeDownstreamPerimeterSpec
  field: MocMixedRegimeFieldResult
  free_boundary_points_m: tuple[Point, ...]
  free_boundary_pressure_residuals_Pa: tuple[float, ...]
  free_boundary_tangent_residuals_rad: tuple[float, ...]
  source_arc_length_m: tuple[float, ...]
  streamline_ids: tuple[int, ...]
  transported_total_pressure_Pa: tuple[float, ...]
  maximum_continuity_residual: float
  maximum_connector_continuity_residual: float
  maximum_entrance_continuity_residual: float
  maximum_entropy_advection_residual: float
  maximum_entrance_entropy_advection_residual: float
  maximum_transverse_momentum_residual: float
  maximum_conservative_mass_residual: float
  maximum_conservative_streamwise_momentum_residual: float
  maximum_conservative_transverse_momentum_residual: float
  maximum_conservative_energy_residual: float
  maximum_conservative_euler_residual: float
  maximum_mass_flow_residual: float
  maximum_entrance_mass_flow_residual: float
  field_topology_verified: bool
####


def _result(
  status: MocMixedRegimeVariableEntropyFreeBoundaryStatus,
  request: MocMixedRegimePerimeterRequest,
  control_section: MocMixedRegimeControlSection,
  control_section_validation: MocMixedRegimeControlSectionResult | None,
  *,
  ambient_pressure_Pa: float,
  downstream_length_m: float,
  initial_outlet_height_m: float,
  inlet_height_m: float,
  axial_station_count: int,
  transverse_station_count: int,
  message: str,
  handoff: MocMixedRegimeEntropyHandoffResult | None = None,
  **kwargs: object,
) -> MocMixedRegimeVariableEntropyFreeBoundaryResult:
  return MocMixedRegimeVariableEntropyFreeBoundaryResult(
    status=status,
    request=request,
    handoff=handoff,
    control_section=control_section,
    control_section_validation=control_section_validation,
    ambient_pressure_Pa=ambient_pressure_Pa,
    downstream_length_m=downstream_length_m,
    initial_outlet_height_m=initial_outlet_height_m,
    inlet_height_m=inlet_height_m,
    outlet_height_m=kwargs.pop('outlet_height_m', None),
    axial_station_count=axial_station_count,
    transverse_station_count=transverse_station_count,
    message=message,
    **kwargs,
  )
####


def _subsonic_mass_flux_factor(mach: float, gamma: float) -> float:
  exponent = (gamma + 1.0) / (2.0 * (gamma - 1.0))
  return mach * (1.0 + 0.5 * (gamma - 1.0) * mach * mach) ** (-exponent)
####


def _subsonic_mach_from_mass_flux_factor(
  target: float,
  gamma: float,
  *,
  subsonic_margin: float,
) -> float:
  if not isfinite(target) or target <= 0.0:
    raise ValueError('subsonic mass-flux target must be finite and positive')
  ####
  lower = 1.0e-10
  upper = 1.0 - subsonic_margin
  upper_value = _subsonic_mass_flux_factor(upper, gamma)
  if target >= upper_value:
    raise ValueError(
      'streamline mass-flux target reaches the strict-subsonic limit: '
      f'target={target}, limit={upper_value}'
    )
  ####
  for _ in range(90):
    midpoint = 0.5 * (lower + upper)
    if _subsonic_mass_flux_factor(midpoint, gamma) < target:
      lower = midpoint
    else:
      upper = midpoint
    ####
  ####
  return 0.5 * (lower + upper)
####


def _static_pressure(
  total_pressure_Pa: float,
  mach: float,
  gamma: float,
) -> float:
  return total_pressure_Pa / (
    1.0 + 0.5 * (gamma - 1.0) * mach * mach
  ) ** (gamma / (gamma - 1.0))
####


def _normalized_density(
  total_pressure_Pa: float,
  reference_total_pressure_Pa: float,
  mach: float,
  gamma: float,
) -> float:
  enthalpy_factor = 1.0 + 0.5 * (gamma - 1.0) * mach * mach
  return (
    total_pressure_Pa / reference_total_pressure_Pa
  ) ** (1.0 / gamma) * enthalpy_factor ** (-1.0 / (gamma - 1.0))
####


def _triangle_gradients(
  points: Sequence[Point],
  values: Sequence[float],
) -> tuple[float, float, float, float]:
  if len(points) != 3 or len(values) != 3:
    raise ValueError('triangle gradients require three points and values')
  ####
  (x1, y1), (x2, y2), (x3, y3) = points
  denominator = (
    x1 * (y2 - y3)
    + x2 * (y3 - y1)
    + x3 * (y1 - y2)
  )
  if not isfinite(denominator) or abs(denominator) <= 1.0e-20:
    raise ValueError('triangle gradient has zero area')
  ####
  gradient_x = (
    values[0] * (y2 - y3)
    + values[1] * (y3 - y1)
    + values[2] * (y1 - y2)
  ) / denominator
  gradient_y = (
    values[0] * (x3 - x2)
    + values[1] * (x1 - x3)
    + values[2] * (x2 - x1)
  ) / denominator
  area = abs(denominator) * 0.5
  diameter = max(
    hypot(points[1][0] - points[0][0], points[1][1] - points[0][1]),
    hypot(points[2][0] - points[1][0], points[2][1] - points[1][1]),
    hypot(points[0][0] - points[2][0], points[0][1] - points[2][1]),
  )
  return gradient_x, gradient_y, area, diameter
####


def _conservative_euler_residuals(
  points: Sequence[Point],
  samples: Sequence[MocMixedRegimeFieldSample],
  reference_total_pressure_Pa: float,
) -> tuple[float, float, float, float, float]:
  """Return normalized steady-Euler residuals for one mapped triangle.

  The variable-entropy reference stores scalar primitive samples rather than
  a conservative state.  This operator reconstructs a normalized ideal-gas
  state using ``p_ref`` and ``R T0`` as the pressure and density/velocity
  scales, then evaluates the strong-form mass-momentum-energy flux
  divergence.  It is deliberately an audit of the mapped field, not a
  replacement for a coupled finite-volume or characteristic solver.
  """

  if len(points) != 3 or len(samples) != 3:
    raise ValueError('conservative Euler residuals require triangular cells')
  ####
  temperatures = tuple(
    1.0
    / (1.0 + 0.5 * (sample.gamma - 1.0) * sample.mach * sample.mach)
    for sample in samples
  )
  pressures = tuple(
    sample.static_pressure_Pa / reference_total_pressure_Pa
    for sample in samples
  )
  densities = tuple(
    pressure / temperature
    for pressure, temperature in zip(pressures, temperatures, strict=True)
  )
  velocities = tuple(
    (
      sample.mach * sqrt(sample.gamma * temperature) * cos(sample.flow_angle_rad),
      sample.mach * sqrt(sample.gamma * temperature) * sin(sample.flow_angle_rad),
    )
    for sample, temperature in zip(samples, temperatures, strict=True)
  )
  momentum_x = tuple(
    density * velocity[0] * velocity[0] + pressure
    for density, velocity, pressure in zip(
      densities,
      velocities,
      pressures,
      strict=True,
    )
  )
  momentum_xy = tuple(
    density * velocity[0] * velocity[1]
    for density, velocity in zip(densities, velocities, strict=True)
  )
  momentum_y = tuple(
    density * velocity[1] * velocity[1] + pressure
    for density, velocity, pressure in zip(
      densities,
      velocities,
      pressures,
      strict=True,
    )
  )
  total_energy = tuple(
    pressure / (sample.gamma - 1.0)
    + 0.5 * density * (velocity[0] * velocity[0] + velocity[1] * velocity[1])
    for sample, density, velocity, pressure in zip(
      samples,
      densities,
      velocities,
      pressures,
      strict=True,
    )
  )
  energy_flux_x = tuple(
    (energy + pressure) * velocity[0]
    for energy, pressure, velocity in zip(
      total_energy,
      pressures,
      velocities,
      strict=True,
    )
  )
  energy_flux_y = tuple(
    (energy + pressure) * velocity[1]
    for energy, pressure, velocity in zip(
      total_energy,
      pressures,
      velocities,
      strict=True,
    )
  )
  mass_flux_x = tuple(
    density * velocity[0]
    for density, velocity in zip(densities, velocities, strict=True)
  )
  mass_flux_y = tuple(
    density * velocity[1]
    for density, velocity in zip(densities, velocities, strict=True)
  )
  mass_x, _mass_y, _area, diameter = _triangle_gradients(
    points,
    mass_flux_x,
  )
  _mass_x, mass_y, _area, _diameter = _triangle_gradients(
    points,
    mass_flux_y,
  )
  streamwise_x, _streamwise_y, _area, diameter = _triangle_gradients(
    points,
    momentum_x,
  )
  cross_x, cross_y, _area, _diameter = _triangle_gradients(
    points,
    momentum_xy,
  )
  _transverse_x, transverse_y, _area, _diameter = _triangle_gradients(
    points,
    momentum_y,
  )
  energy_x, energy_y, _area, _diameter = _triangle_gradients(
    points,
    energy_flux_x,
  )
  _energy_y_x, energy_y_y, _area, _diameter = _triangle_gradients(
    points,
    energy_flux_y,
  )
  momentum_scale = max(
    1.0e-12,
    *(abs(value) for value in (*momentum_x, *momentum_xy, *momentum_y)),
  )
  energy_scale = max(
    1.0e-12,
    *(abs(value) for value in (*energy_flux_x, *energy_flux_y)),
  )
  mass_scale = max(
    1.0e-12,
    *(abs(value) for value in (*mass_flux_x, *mass_flux_y)),
  )
  mass_residual = abs(mass_x + mass_y) * diameter / mass_scale
  streamwise_residual = abs(streamwise_x + cross_y) * diameter / momentum_scale
  transverse_residual = abs(cross_x + transverse_y) * diameter / momentum_scale
  energy_residual = abs(energy_x + energy_y_y) * diameter / energy_scale
  return (
    mass_residual,
    streamwise_residual,
    transverse_residual,
    energy_residual,
    max(mass_residual, streamwise_residual, transverse_residual, energy_residual),
  )
####


def _profile_at_arc_length(
  handoff: MocMixedRegimeEntropyHandoffResult,
  coordinate: float,
  attribute: str,
) -> float:
  arc = handoff.cumulative_arc_length_m
  samples = handoff.samples
  if not arc or len(arc) != len(samples):
    raise ValueError('entropy handoff does not expose a complete arc profile')
  ####
  if coordinate < arc[0] - 1.0e-12 or coordinate > arc[-1] + 1.0e-12:
    raise ValueError('source arc coordinate lies outside the entropy handoff')
  ####
  coordinate = min(arc[-1], max(arc[0], coordinate))
  if coordinate <= arc[0]:
    return float(getattr(samples[0], attribute))
  ####
  if coordinate >= arc[-1]:
    return float(getattr(samples[-1], attribute))
  ####
  for first_arc, second_arc, first, second in zip(
    arc,
    arc[1:],
    samples,
    samples[1:],
    strict=True,
  ):
    if coordinate <= second_arc:
      fraction = (coordinate - first_arc) / (second_arc - first_arc)
      first_value = float(getattr(first, attribute))
      second_value = float(getattr(second, attribute))
      return first_value + fraction * (second_value - first_value)
    ####
  ####
  return float(getattr(samples[-1], attribute))
####


def _validate_control_geometry(
  request: MocMixedRegimePerimeterRequest,
  section: MocMixedRegimeControlSection,
  *,
  position_tolerance_m: float,
  tangent_tolerance_rad: float,
) -> tuple[tuple[float, ...], float, float]:
  """Return transverse fractions, entrance slope, and entrance x location."""

  terminal_x, terminal_y = request.terminal_point_m
  if abs(section.normal_angle_rad) > tangent_tolerance_rad:
    raise ValueError(
      'variable-entropy reference requires a section normal aligned with +x'
    )
  ####
  if any(
    abs(point[0] - section.points_m[0][0]) > position_tolerance_m
    for point in section.points_m
  ):
    raise ValueError('variable-entropy control section must be vertical')
  ####
  section_x = section.points_m[0][0]
  if section_x <= terminal_x + position_tolerance_m:
    raise ValueError(
      'variable-entropy control section must lie downstream of the terminal'
    )
  ####
  height = section.points_m[-1][1] - terminal_y
  if height <= position_tolerance_m:
    raise ValueError(
      'variable-entropy control section must start at the terminal axis and '
      'extend to a positive outer height'
    )
  ####
  if abs(section.points_m[0][1] - terminal_y) > position_tolerance_m:
    raise ValueError(
      'variable-entropy control section must start at the terminal point '
      'transverse coordinate'
    )
  ####
  fractions = tuple(
    (point[1] - terminal_y) / height for point in section.points_m
  )
  if (
    fractions[0] < -tangent_tolerance_rad
    or abs(fractions[-1] - 1.0) > position_tolerance_m / max(height, 1.0)
  ):
    raise ValueError('variable-entropy control section has invalid transverse extent')
  ####
  if any(
    second <= first + position_tolerance_m / max(height, 1.0)
    for first, second in zip(fractions, fractions[1:])
  ):
    raise ValueError('variable-entropy transverse fractions must be increasing')
  ####
  slopes = tuple(
    tan(sample.flow_angle_rad) / fraction
    for sample, fraction in zip(section.samples[1:], fractions[1:], strict=True)
  )
  entrance_slope = sum(slopes) / len(slopes)
  angle_residual = max(
    abs(
      sample.flow_angle_rad
      - atan2(fraction * entrance_slope, 1.0)
    )
    for sample, fraction in zip(section.samples, fractions, strict=True)
  )
  if angle_residual > tangent_tolerance_rad:
    raise ValueError(
      'control-section flow angles do not define one mapped entrance '
      f'streamline slope: residual={angle_residual}'
    )
  ####
  return fractions, entrance_slope, section_x
####


def _build_candidate(
  request: MocMixedRegimePerimeterRequest,
  handoff: MocMixedRegimeEntropyHandoffResult,
  control_section: MocMixedRegimeControlSection,
  fractions: Sequence[float],
  source_arc_by_fraction: Sequence[float],
  source_pressure_by_fraction: Sequence[float],
  source_gamma_by_fraction: Sequence[float],
  inlet_slope: float,
  section_x: float,
  heights: Sequence[float],
  *,
  ambient_pressure_Pa: float,
  downstream_length_m: float,
  subsonic_margin: float,
  position_tolerance_m: float,
  state_tolerance: float,
  pressure_tolerance: float,
  tangent_tolerance_rad: float,
) -> _VariableEntropyCandidate:
  axial_count = len(heights)
  transverse_count = len(fractions)
  if axial_count < 5 or transverse_count < 3:
    raise ValueError('variable-entropy mesh resolution is too small')
  ####
  if len(source_arc_by_fraction) != transverse_count:
    raise ValueError('source arc and transverse fraction layouts do not match')
  ####
  if len(source_pressure_by_fraction) != transverse_count:
    raise ValueError('source pressure and transverse fraction layouts do not match')
  ####
  if len(source_gamma_by_fraction) != transverse_count:
    raise ValueError('source gamma and transverse fraction layouts do not match')
  ####
  if any(
    not isfinite(float(height)) or float(height) <= 0.0
    for height in heights
  ):
    raise ValueError('variable-entropy free-boundary heights must be positive')
  ####
  x0, y0 = control_section.points_m[0]
  dx = downstream_length_m / (axial_count - 1)
  x_stations = tuple(x0 + index * dx for index in range(axial_count))
  height_values = tuple(float(value) for value in heights)
  grid_points = tuple(
    tuple(
      (x_stations[i], y0 + float(fractions[j]) * height_values[i])
      for j in range(transverse_count)
    )
    for i in range(axial_count)
  )
  slopes: list[float] = []
  for index in range(axial_count):
    if index == 0:
      slopes.append(float(inlet_slope))
    elif index == axial_count - 1:
      slopes.append((height_values[-1] - height_values[-2]) / dx)
    else:
      slopes.append((height_values[index + 1] - height_values[index - 1]) / (2.0 * dx))
    ####
  ####

  inlet_machs = tuple(sample.mach for sample in control_section.samples)
  node_samples: list[MocMixedRegimeFieldSample] = []
  source_arc: list[float] = []
  streamline_ids: list[int] = []
  transported_pressure: list[float] = []
  terminal = request.terminal
  terminal_values = (
    terminal.downstream_mach,
    terminal.downstream_flow_angle_rad,
    terminal.downstream_pressure_Pa,
    terminal.downstream_total_pressure_Pa,
    terminal.upstream_state,
  )
  if any(value is None for value in terminal_values):
    raise ValueError('terminal does not expose complete scalar values')
  ####
  terminal_mach, terminal_angle, terminal_pressure, terminal_p0, terminal_state = terminal_values
  assert terminal_mach is not None
  assert terminal_angle is not None
  assert terminal_pressure is not None
  assert terminal_p0 is not None
  assert terminal_state is not None
  terminal_sample = MocMixedRegimeFieldSample(
    point_m=request.terminal_point_m,
    mach=terminal_mach,
    flow_angle_rad=terminal_angle,
    static_pressure_Pa=terminal_pressure,
    total_pressure_Pa=terminal_p0,
    gamma=terminal_state.gamma,
  )
  node_samples.append(terminal_sample)
  source_arc.append(handoff.cumulative_arc_length_m[-1])
  streamline_ids.append(0)
  transported_pressure.append(terminal_p0)
  for i in range(axial_count):
    for j in range(transverse_count):
      gamma = float(source_gamma_by_fraction[j])
      source_pressure = float(source_pressure_by_fraction[j])
      target_factor = _subsonic_mass_flux_factor(inlet_machs[j], gamma) * (
        control_section.points_m[-1][1] - control_section.points_m[0][1]
      ) / height_values[i]
      mach = _subsonic_mach_from_mass_flux_factor(
        target_factor,
        gamma,
        subsonic_margin=subsonic_margin,
      )
      angle = atan2(float(fractions[j]) * slopes[i], 1.0)
      point = grid_points[i][j]
      node_samples.append(
        MocMixedRegimeFieldSample(
          point_m=point,
          mach=mach,
          flow_angle_rad=angle,
          static_pressure_Pa=_static_pressure(source_pressure, mach, gamma),
          total_pressure_Pa=source_pressure,
          gamma=gamma,
        )
      )
      source_arc.append(float(source_arc_by_fraction[j]))
      streamline_ids.append(j)
      transported_pressure.append(source_pressure)
    ####
  ####

  def grid_index(i: int, j: int) -> int:
    return 1 + i * transverse_count + j
  ####

  cells: list[MocCharacteristicCell] = []
  connectivity: list[tuple[int, int, int]] = []
  for j in range(transverse_count - 1):
    indices = (0, grid_index(0, j), grid_index(0, j + 1))
    connectivity.append(indices)
    cells.append(
      MocCharacteristicCell(
        cell_index=len(cells),
        cell_kind='variable-entropy-terminal-connector',
        vertices_xr_m=tuple(node_samples[index].point_m for index in indices),
        centerline_indices=(),
        boundary_indices=(j, j + 1),
      )
    )
  ####
  for i in range(axial_count - 1):
    for j in range(transverse_count - 1):
      first = (grid_index(i, j), grid_index(i, j + 1), grid_index(i + 1, j + 1))
      second = (grid_index(i, j), grid_index(i + 1, j + 1), grid_index(i + 1, j))
      for indices in (first, second):
        connectivity.append(indices)
        cells.append(
          MocCharacteristicCell(
            cell_index=len(cells),
            cell_kind='variable-entropy-streamtube',
            vertices_xr_m=tuple(node_samples[index].point_m for index in indices),
            centerline_indices=(),
            boundary_indices=(i, j),
          )
        )
      ####
    ####
  ####
  topology = validate_moc_mesh(tuple(cells))
  if not topology.forms_closed_zone or topology.nonmanifold_edge_count:
    raise ValueError(f'variable-entropy mesh topology failed: {topology.message}')
  ####

  boundary_indices = [0, grid_index(0, transverse_count - 1)]
  boundary_indices.extend(
    grid_index(i, transverse_count - 1) for i in range(1, axial_count)
  )
  boundary_indices.extend(
    grid_index(axial_count - 1, j)
    for j in range(transverse_count - 2, -1, -1)
  )
  boundary_indices.extend(
    grid_index(i, 0) for i in range(axial_count - 2, -1, -1)
  )
  boundary_indices.append(0)
  boundary_points = tuple(node_samples[index].point_m for index in boundary_indices)
  boundary_samples = tuple(node_samples[index] for index in boundary_indices)
  boundary = validate_mixed_regime_boundary(
    request.terminal,
    request.supersonic_patch,
    supersonic_patch_converged=True,
    subsonic_samples=boundary_samples,
    perimeter_points_m=boundary_points,
    position_tolerance_m=position_tolerance_m,
    state_tolerance=state_tolerance,
    pressure_tolerance=pressure_tolerance,
    allow_distributed_total_pressure_profile=True,
  )
  if not boundary.converged:
    raise ValueError(f'variable-entropy perimeter seam failed: {boundary.message}')
  ####
  free_boundary_points = tuple(
    grid_points[i][-1] for i in range(axial_count)
  )
  # The first three outer stations are an explicit entrance regularization.  A
  # centered tangent estimate at the third station still sees the incoming
  # connector, so the ambient condition starts at the next outer edge.
  condition_edges = tuple(range(4, axial_count))
  condition_samples = tuple(range(4, axial_count + 1))
  perimeter_spec = MocMixedRegimeDownstreamPerimeterSpec(
    perimeter_points_m=boundary_points,
    condition_kind=MocMixedRegimeDownstreamConditionKind.AMBIENT_PRESSURE_FREE_BOUNDARY,
    ambient_pressure_Pa=ambient_pressure_Pa,
    model=VARIABLE_ENTROPY_MODEL,
    condition_edge_indices=condition_edges,
    condition_sample_indices=condition_samples,
  )
  downstream_condition = validate_mixed_regime_downstream_condition(
    boundary,
    perimeter_spec.condition_kind,
    ambient_pressure_Pa=ambient_pressure_Pa,
    condition_edge_indices=condition_edges,
    condition_sample_indices=condition_samples,
    position_tolerance_m=position_tolerance_m,
    tangent_tolerance_rad=tangent_tolerance_rad,
    pressure_tolerance=pressure_tolerance,
  )

  reference_p0 = terminal_p0
  grid_continuity: list[float] = []
  connector_continuity: list[float] = []
  entrance_continuity: list[float] = []
  entropy_residuals: list[float] = []
  entrance_entropy_residuals: list[float] = []
  transverse_residuals: list[float] = []
  conservative_mass_residuals: list[float] = []
  conservative_streamwise_residuals: list[float] = []
  conservative_transverse_residuals: list[float] = []
  conservative_energy_residuals: list[float] = []
  conservative_euler_residuals: list[float] = []
  for cell_index, indices in enumerate(connectivity):
    samples = tuple(node_samples[index] for index in indices)
    points = tuple(sample.point_m for sample in samples)
    (
      conservative_mass,
      conservative_streamwise,
      conservative_transverse,
      conservative_energy,
      conservative_euler,
    ) = _conservative_euler_residuals(points, samples, reference_p0)
    conservative_mass_residuals.append(conservative_mass)
    conservative_streamwise_residuals.append(conservative_streamwise)
    conservative_transverse_residuals.append(conservative_transverse)
    conservative_energy_residuals.append(conservative_energy)
    densities = tuple(
      _normalized_density(
        sample.total_pressure_Pa,
        reference_p0,
        sample.mach,
        sample.gamma,
      )
      for sample in samples
    )
    speeds = tuple(
      sample.mach
      / sqrt(1.0 + 0.5 * (sample.gamma - 1.0) * sample.mach * sample.mach)
      for sample in samples
    )
    velocity = tuple(
      (speed * cos(sample.flow_angle_rad), speed * sin(sample.flow_angle_rad))
      for speed, sample in zip(speeds, samples, strict=True)
    )
    mass_velocity = tuple(
      (density * value[0], density * value[1])
      for density, value in zip(densities, velocity, strict=True)
    )
    gradient_mx_x, gradient_mx_y, _, diameter = _triangle_gradients(
      points,
      tuple(value[0] for value in mass_velocity),
    )
    gradient_my_x, gradient_my_y, _, _ = _triangle_gradients(
      points,
      tuple(value[1] for value in mass_velocity),
    )
    continuity = abs(gradient_mx_x + gradient_my_y) * diameter / max(
      1.0e-12,
      max(hypot(*value) for value in mass_velocity),
    )
    conservative_euler_residuals.append(
      conservative_euler
    )
    entropy_gradient_x, entropy_gradient_y, _, _ = _triangle_gradients(
      points,
      tuple(log(sample.total_pressure_Pa) for sample in samples),
    )
    center_velocity = (
      sum(value[0] for value in velocity) / 3.0,
      sum(value[1] for value in velocity) / 3.0,
    )
    entropy_residual = abs(
      center_velocity[0] * entropy_gradient_x
      + center_velocity[1] * entropy_gradient_y
    ) * diameter / max(1.0e-12, hypot(*center_velocity))
    pressure_gradient_x, pressure_gradient_y, _, _ = _triangle_gradients(
      points,
      tuple(sample.static_pressure_Pa / reference_p0 for sample in samples),
    )
    velocity_y_gradient_x, velocity_y_gradient_y, _, _ = _triangle_gradients(
      points,
      tuple(value[1] for value in velocity),
    )
    density_center = sum(densities) / 3.0
    transverse = abs(
      center_velocity[0] * velocity_y_gradient_x
      + center_velocity[1] * velocity_y_gradient_y
      + pressure_gradient_y / max(1.0e-12, density_center)
    ) * diameter
    entrance_cell = cell_index < transverse_count - 1
    if not entrance_cell:
      grid_cell_index = cell_index - (transverse_count - 1)
      station_index = grid_cell_index // (2 * (transverse_count - 1))
      entrance_cell = station_index < 3
    ####
    if cell_index < transverse_count - 1:
      connector_continuity.append(continuity)
    elif entrance_cell:
      entrance_continuity.append(continuity)
    else:
      grid_continuity.append(continuity)
    ####
    if entrance_cell:
      entrance_entropy_residuals.append(entropy_residual)
    else:
      entropy_residuals.append(entropy_residual)
    ####
    transverse_residuals.append(transverse)
  ####

  mass_flow_residuals: list[float] = []
  entrance_mass_flow_residuals: list[float] = []
  inlet_height = control_section.points_m[-1][1] - control_section.points_m[0][1]
  for i in range(axial_count):
    for j in range(transverse_count):
      sample = node_samples[grid_index(i, j)]
      speed = sample.mach / sqrt(
        1.0 + 0.5 * (sample.gamma - 1.0) * sample.mach * sample.mach
      )
      flux = (
        _normalized_density(
          sample.total_pressure_Pa,
          reference_p0,
          sample.mach,
          sample.gamma,
        )
        * speed
        * cos(sample.flow_angle_rad)
        * height_values[i]
      )
      inlet_sample = control_section.samples[j]
      inlet_speed = inlet_sample.mach / sqrt(
        1.0
        + 0.5 * (inlet_sample.gamma - 1.0) * inlet_sample.mach * inlet_sample.mach
      )
      inlet_flux = (
        _normalized_density(
          source_pressure_by_fraction[j],
          reference_p0,
          inlet_sample.mach,
          inlet_sample.gamma,
        )
        * inlet_speed
        * cos(inlet_sample.flow_angle_rad)
        * inlet_height
      )
      mass_flow_residual = abs(flux - inlet_flux) / max(
        1.0e-12,
        abs(inlet_flux),
      )
      if i < 3:
        entrance_mass_flow_residuals.append(mass_flow_residual)
      else:
        mass_flow_residuals.append(mass_flow_residual)
      ####
    ####
  ####

  field = MocMixedRegimeFieldResult(
    status=MocMixedRegimeFieldStatus.CONVERGED_ELLIPTIC_FIELD,
    boundary=boundary,
    nodes=tuple(node_samples),
    cells=tuple(cells),
    topology=topology,
    interior_point_m=(
      sum(point[0] for point in grid_points[0]) / transverse_count,
      sum(point[1] for point in grid_points[-1]) / transverse_count,
    ),
    maximum_thermodynamic_residual=0.0,
    maximum_harmonic_residual=None,
    maximum_velocity_divergence_residual=max(grid_continuity, default=0.0),
    minimum_mach=min(sample.mach for sample in node_samples),
    maximum_mach=max(sample.mach for sample in node_samples),
    model=VARIABLE_ENTROPY_MODEL,
    radial_divisions=1,
    downstream_condition=None,
    maximum_mass_conservation_residual=max(grid_continuity, default=0.0),
    maximum_boundary_velocity_residual=0.0,
    maximum_boundary_normal_velocity_residual=max(
      downstream_condition.tangent_residuals_rad,
      default=0.0,
    ),
    control_section=control_section,
    message=(
      'mapped variable-entropy stream-tube field assembled on a closed '
      'triangular mesh; transverse momentum remains a reported 2-D Euler '
      'closure residual and no canonical characteristic field is claimed'
    ),
  )
  pressure_residuals = tuple(
    node_samples[index].static_pressure_Pa - ambient_pressure_Pa
    for index in boundary_indices[4:axial_count + 1]
  )
  if not pressure_residuals:
    raise ValueError('variable-entropy free boundary produced no pressure samples')
  ####
  return _VariableEntropyCandidate(
    boundary=boundary,
    downstream_condition=downstream_condition,
    perimeter_spec=perimeter_spec,
    field=field,
    free_boundary_points_m=free_boundary_points,
    free_boundary_pressure_residuals_Pa=pressure_residuals,
    free_boundary_tangent_residuals_rad=downstream_condition.tangent_residuals_rad,
    source_arc_length_m=tuple(source_arc),
    streamline_ids=tuple(streamline_ids),
    transported_total_pressure_Pa=tuple(transported_pressure),
    maximum_continuity_residual=max(grid_continuity, default=0.0),
    maximum_connector_continuity_residual=max(connector_continuity, default=0.0),
    maximum_entrance_continuity_residual=max(entrance_continuity, default=0.0),
    maximum_entropy_advection_residual=max(entropy_residuals, default=0.0),
    maximum_entrance_entropy_advection_residual=max(
      entrance_entropy_residuals,
      default=0.0,
    ),
    maximum_transverse_momentum_residual=max(transverse_residuals, default=0.0),
    maximum_conservative_mass_residual=max(
      conservative_mass_residuals,
      default=0.0,
    ),
    maximum_conservative_streamwise_momentum_residual=max(
      conservative_streamwise_residuals,
      default=0.0,
    ),
    maximum_conservative_transverse_momentum_residual=max(
      conservative_transverse_residuals,
      default=0.0,
    ),
    maximum_conservative_energy_residual=max(
      conservative_energy_residuals,
      default=0.0,
    ),
    maximum_conservative_euler_residual=max(
      conservative_euler_residuals,
      default=0.0,
    ),
    maximum_mass_flow_residual=max(mass_flow_residuals, default=0.0),
    maximum_entrance_mass_flow_residual=max(
      entrance_mass_flow_residuals,
      default=0.0,
    ),
    field_topology_verified=topology.forms_closed_zone and not topology.nonmanifold_edge_count,
  )
####


def solve_mixed_regime_variable_entropy_free_boundary(
  request: MocMixedRegimePerimeterRequest,
  handoff: MocMixedRegimeEntropyHandoffResult,
  control_section: MocMixedRegimeControlSection,
  *,
  ambient_pressure_Pa: float,
  downstream_length_m: float,
  initial_outlet_height_m: float,
  axial_station_count: int = 7,
  maximum_iterations: int = 32,
  shape_relaxation: float = 0.85,
  position_tolerance_m: float = 1.0e-10,
  state_tolerance: float = 1.0e-8,
  pressure_tolerance: float = 1.0e-8,
  tangent_tolerance_rad: float = 2.0e-2,
  continuity_tolerance: float = 0.25,
  entropy_transport_tolerance: float = 0.25,
  subsonic_margin: float = 1.0e-6,
) -> MocMixedRegimeVariableEntropyFreeBoundaryResult:
  """Solve the mapped variable-entropy/free-boundary reference.

  The control section must be a downstream vertical section beginning on the
  terminal axis.  Its geometry supplies the transverse streamline labels;
  its total-pressure samples must agree with the solver-generated reverse
  mapping of the ordered shock-interface handoff.  The free-boundary height
  is iterated from the ambient pressure on the outer streamline.  No source
  coordinate or streamline identifier is accepted from the caller.
  """

  if not isinstance(request, MocMixedRegimePerimeterRequest):
    raise TypeError('request must be a MocMixedRegimePerimeterRequest')
  ####
  if not isinstance(handoff, MocMixedRegimeEntropyHandoffResult):
    raise TypeError('handoff must be a MocMixedRegimeEntropyHandoffResult')
  ####
  if not isinstance(control_section, MocMixedRegimeControlSection):
    raise TypeError('control_section must be a MocMixedRegimeControlSection')
  ####
  for name, value in (
    ('ambient_pressure_Pa', ambient_pressure_Pa),
    ('downstream_length_m', downstream_length_m),
    ('initial_outlet_height_m', initial_outlet_height_m),
    ('position_tolerance_m', position_tolerance_m),
    ('state_tolerance', state_tolerance),
    ('pressure_tolerance', pressure_tolerance),
    ('tangent_tolerance_rad', tangent_tolerance_rad),
    ('continuity_tolerance', continuity_tolerance),
    ('entropy_transport_tolerance', entropy_transport_tolerance),
    ('subsonic_margin', subsonic_margin),
  ):
    if not isfinite(float(value)) or float(value) <= 0.0:
      raise ValueError(f'{name} must be finite and positive')
    ####
  ####
  if subsonic_margin >= 1.0:
    raise ValueError('subsonic_margin must be less than one')
  ####
  if not 0.0 < shape_relaxation <= 1.0:
    raise ValueError('shape_relaxation must lie in the interval (0, 1]')
  ####
  for name, value, minimum in (
    ('axial_station_count', axial_station_count, 5),
    ('maximum_iterations', maximum_iterations, 1),
  ):
    if isinstance(value, bool) or not isinstance(value, int) or value < minimum:
      raise ValueError(
        f'{name} must be an integer greater than or equal to {minimum}'
      )
    ####
  ####
  if handoff.request != request:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.HANDOFF_FAILURE,
      request,
      control_section,
      None,
      ambient_pressure_Pa=ambient_pressure_Pa,
      downstream_length_m=downstream_length_m,
      initial_outlet_height_m=initial_outlet_height_m,
      inlet_height_m=max(position_tolerance_m, 1.0),
      axial_station_count=axial_station_count,
      transverse_station_count=max(3, len(control_section.samples)),
      handoff=handoff,
      message='entropy handoff must retain the exact mixed-regime request',
    )
  ####
  if not handoff.converged or not handoff.entropy_transport_verified:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.HANDOFF_FAILURE,
      request,
      control_section,
      None,
      ambient_pressure_Pa=ambient_pressure_Pa,
      downstream_length_m=downstream_length_m,
      initial_outlet_height_m=initial_outlet_height_m,
      inlet_height_m=max(position_tolerance_m, 1.0),
      axial_station_count=axial_station_count,
      transverse_station_count=max(3, len(control_section.samples)),
      handoff=handoff,
      message=f'entropy handoff is not converged: {handoff.message}',
    )
  ####
  control_validation = validate_mixed_regime_control_section(
    request,
    control_section,
    position_tolerance_m=position_tolerance_m,
    state_tolerance=state_tolerance,
    pressure_tolerance=pressure_tolerance,
    allow_distributed_total_pressure_profile=True,
  )
  inlet_height = control_section.points_m[-1][1] - control_section.points_m[0][1]
  common = {
    'ambient_pressure_Pa': float(ambient_pressure_Pa),
    'downstream_length_m': float(downstream_length_m),
    'initial_outlet_height_m': float(initial_outlet_height_m),
    'inlet_height_m': max(float(inlet_height), position_tolerance_m),
    'axial_station_count': axial_station_count,
    'transverse_station_count': max(3, len(control_section.samples)),
    'handoff': handoff,
  }
  if not control_validation.converged:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.CONTROL_SECTION_FAILURE,
      request,
      control_section,
      control_validation,
      message=(
        'variable-entropy reference requires a valid downstream control '
        f'section: {control_validation.message}'
      ),
      **common,
    )
  ####
  try:
    fractions, inlet_slope, section_x = _validate_control_geometry(
      request,
      control_section,
      position_tolerance_m=position_tolerance_m,
      tangent_tolerance_rad=tangent_tolerance_rad,
    )
  except (ArithmeticError, FloatingPointError, TypeError, ValueError) as error:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.GEOMETRY_FAILURE,
      request,
      control_section,
      control_validation,
      message=f'variable-entropy control geometry failed: {error}',
      **common,
    )
  ####
  if len(fractions) < 3:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.CONTROL_SECTION_FAILURE,
      request,
      control_section,
      control_validation,
      message='variable-entropy reference requires at least three streamlines',
      **common,
    )
  ####
  interface_length = handoff.cumulative_arc_length_m[-1]
  source_arc_by_fraction = tuple(interface_length * (1.0 - fraction) for fraction in fractions)
  try:
    source_pressure_by_fraction = tuple(
      _profile_at_arc_length(
        handoff,
        coordinate,
        'downstream_total_pressure_Pa',
      )
      for coordinate in source_arc_by_fraction
    )
    source_gamma_by_fraction = tuple(
      _profile_at_arc_length(handoff, coordinate, 'gamma')
      for coordinate in source_arc_by_fraction
    )
  except (ArithmeticError, FloatingPointError, TypeError, ValueError) as error:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.HANDOFF_FAILURE,
      request,
      control_section,
      control_validation,
      message=f'variable-entropy source profile failed: {error}',
      **common,
    )
  ####
  input_pressure_residuals = tuple(
    abs(sample.total_pressure_Pa - expected)
    for sample, expected in zip(
      control_section.samples,
      source_pressure_by_fraction,
      strict=True,
    )
  )
  input_gamma_residuals = tuple(
    abs(sample.gamma - expected)
    for sample, expected in zip(
      control_section.samples,
      source_gamma_by_fraction,
      strict=True,
    )
  )
  angle_residual = max(
    abs(
      sample.flow_angle_rad
      - atan2(fraction * inlet_slope, 1.0)
    )
    for sample, fraction in zip(control_section.samples, fractions, strict=True)
  )
  pressure_input_tolerance = pressure_tolerance * max(
    1.0,
    max(abs(value) for value in source_pressure_by_fraction),
  )
  if (
    max(input_pressure_residuals, default=0.0) > pressure_input_tolerance
    or max(input_gamma_residuals, default=0.0) > state_tolerance
  ):
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.CONTROL_SECTION_FAILURE,
      request,
      control_section,
      control_validation,
      maximum_control_source_pressure_residual_Pa=max(input_pressure_residuals, default=0.0),
      maximum_control_source_gamma_residual=max(input_gamma_residuals, default=0.0),
      maximum_inlet_angle_law_residual_rad=angle_residual,
      message=(
        'control-section total pressure/gamma do not match the solver-owned '
        'reverse entropy mapping: '
        f'pressure_residual={max(input_pressure_residuals, default=0.0)}, '
        f'gamma_residual={max(input_gamma_residuals, default=0.0)}'
      ),
      **common,
    )
  ####
  outer_gamma = source_gamma_by_fraction[-1]
  outer_source_pressure = source_pressure_by_fraction[-1]
  if ambient_pressure_Pa >= outer_source_pressure:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.PRESSURE_UNREACHABLE,
      request,
      control_section,
      control_validation,
      maximum_control_source_pressure_residual_Pa=max(input_pressure_residuals, default=0.0),
      maximum_control_source_gamma_residual=max(input_gamma_residuals, default=0.0),
      maximum_inlet_angle_law_residual_rad=angle_residual,
      message='ambient pressure must be below the outer-streamline total pressure',
      **common,
    )
  ####
  ambient_mach_squared = 2.0 / (outer_gamma - 1.0) * (
    (outer_source_pressure / ambient_pressure_Pa) ** ((outer_gamma - 1.0) / outer_gamma)
    - 1.0
  )
  ambient_mach = sqrt(ambient_mach_squared) if ambient_mach_squared > 0.0 else float('nan')
  if not isfinite(ambient_mach) or ambient_mach >= 1.0 - subsonic_margin:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.PRESSURE_UNREACHABLE,
      request,
      control_section,
      control_validation,
      maximum_control_source_pressure_residual_Pa=max(input_pressure_residuals, default=0.0),
      maximum_control_source_gamma_residual=max(input_gamma_residuals, default=0.0),
      maximum_inlet_angle_law_residual_rad=angle_residual,
      message=(
        'ambient pressure does not map to a strict-subsonic outer '
        f'streamline Mach number: mach={ambient_mach}'
      ),
      **common,
    )
  ####
  outer_inlet_mach = control_section.samples[-1].mach
  target_height = inlet_height * _subsonic_mass_flux_factor(
    outer_inlet_mach,
    outer_gamma,
  ) / _subsonic_mass_flux_factor(ambient_mach, outer_gamma)
  if not isfinite(target_height) or target_height <= 0.0:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.PRESSURE_UNREACHABLE,
      request,
      control_section,
      control_validation,
      maximum_control_source_pressure_residual_Pa=max(input_pressure_residuals, default=0.0),
      maximum_control_source_gamma_residual=max(input_gamma_residuals, default=0.0),
      maximum_inlet_angle_law_residual_rad=angle_residual,
      message='ambient pressure produced an invalid free-boundary height',
      **common,
    )
  ####
  strict_subsonic_flux_limit = _subsonic_mass_flux_factor(
    1.0 - subsonic_margin,
    outer_gamma,
  )
  minimum_streamtube_height = max(
    inlet_height
    * _subsonic_mass_flux_factor(sample.mach, sample.gamma)
    / strict_subsonic_flux_limit
    * (1.0 + 1.0e-6)
    for sample in control_section.samples
  )
  dx = downstream_length_m / (axial_station_count - 1)
  initial_heights = tuple(
    inlet_height
    + (float(initial_outlet_height_m) - inlet_height)
    * index
    / (axial_station_count - 1)
    for index in range(axial_station_count)
  )
  heights = list(initial_heights)
  heights[0] = inlet_height
  heights[1] = max(
    inlet_height + inlet_slope * dx,
    minimum_streamtube_height,
  )
  for index in range(2, axial_station_count):
    heights[index] = max(heights[index], minimum_streamtube_height)
  ####
  if heights[1] <= position_tolerance_m:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.GEOMETRY_FAILURE,
      request,
      control_section,
      control_validation,
      initial_free_boundary_heights_m=initial_heights,
      maximum_control_source_pressure_residual_Pa=max(input_pressure_residuals, default=0.0),
      maximum_control_source_gamma_residual=max(input_gamma_residuals, default=0.0),
      maximum_inlet_angle_law_residual_rad=angle_residual,
      message='control-section entrance slope leaves a nonpositive first height',
      **common,
    )
  ####
  residual_history: list[float] = []
  candidate: _VariableEntropyCandidate | None = None
  last_error = ''
  pressure_scale = max(1.0, abs(ambient_pressure_Pa))
  for iteration in range(maximum_iterations):
    try:
      candidate = _build_candidate(
        request,
        handoff,
        control_section,
        fractions,
        source_arc_by_fraction,
        source_pressure_by_fraction,
        source_gamma_by_fraction,
        inlet_slope,
        section_x,
        heights,
        ambient_pressure_Pa=ambient_pressure_Pa,
        downstream_length_m=downstream_length_m,
        subsonic_margin=subsonic_margin,
        position_tolerance_m=position_tolerance_m,
        state_tolerance=state_tolerance,
        pressure_tolerance=pressure_tolerance,
        tangent_tolerance_rad=tangent_tolerance_rad,
      )
    except (ArithmeticError, FloatingPointError, TypeError, ValueError) as error:
      last_error = str(error)
      return _result(
        MocMixedRegimeVariableEntropyFreeBoundaryStatus.FIELD_FAILURE,
        request,
        control_section,
        control_validation,
        initial_free_boundary_heights_m=initial_heights,
        free_boundary_heights_m=tuple(heights),
        source_arc_length_by_transverse_index_m=source_arc_by_fraction,
        source_total_pressure_by_transverse_index_Pa=source_pressure_by_fraction,
        source_gamma_by_transverse_index=source_gamma_by_fraction,
        maximum_control_source_pressure_residual_Pa=max(input_pressure_residuals, default=0.0),
        maximum_control_source_gamma_residual=max(input_gamma_residuals, default=0.0),
        maximum_inlet_angle_law_residual_rad=angle_residual,
        residual_history=tuple(residual_history),
        message=f'variable-entropy field trial failed: {error}',
        **common,
      )
    ####
    pressure_residual = max(
      (abs(value) for value in candidate.free_boundary_pressure_residuals_Pa),
      default=float('inf'),
    )
    residual_history.append(pressure_residual)
    if pressure_residual <= pressure_tolerance * pressure_scale:
      break
    ####
    for index in range(2, axial_station_count):
      heights[index] += shape_relaxation * (target_height - heights[index])
    ####
    if any(height <= position_tolerance_m for height in heights):
      last_error = 'free-boundary iteration produced a nonpositive height'
      break
    ####
  ####
  if candidate is None:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.FIELD_FAILURE,
      request,
      control_section,
      control_validation,
      initial_free_boundary_heights_m=initial_heights,
      residual_history=tuple(residual_history),
      maximum_control_source_pressure_residual_Pa=max(input_pressure_residuals, default=0.0),
      maximum_control_source_gamma_residual=max(input_gamma_residuals, default=0.0),
      maximum_inlet_angle_law_residual_rad=angle_residual,
      message=f'variable-entropy field produced no candidate: {last_error}',
      **common,
    )
  ####
  pressure_residual = max(
    (abs(value) for value in candidate.free_boundary_pressure_residuals_Pa),
    default=float('inf'),
  )
  common_solution = {
    **common,
    'handoff': handoff,
    'outlet_height_m': heights[-1],
    'initial_free_boundary_heights_m': initial_heights,
    'free_boundary_heights_m': tuple(heights),
    'free_boundary_points_m': candidate.free_boundary_points_m,
    'transverse_fractions': tuple(fractions),
    'source_arc_length_by_transverse_index_m': source_arc_by_fraction,
    'source_total_pressure_by_transverse_index_Pa': source_pressure_by_fraction,
    'source_gamma_by_transverse_index': source_gamma_by_fraction,
    'source_arc_length_m': candidate.source_arc_length_m,
    'streamline_ids': candidate.streamline_ids,
    'transported_total_pressure_Pa': candidate.transported_total_pressure_Pa,
    'iteration_count': len(residual_history),
    'residual_history': tuple(residual_history),
    'maximum_free_boundary_pressure_residual_Pa': pressure_residual,
    'maximum_free_boundary_tangent_residual_rad': max(
      candidate.free_boundary_tangent_residuals_rad,
      default=0.0,
    ),
    'maximum_continuity_residual': candidate.maximum_continuity_residual,
    'maximum_connector_continuity_residual': candidate.maximum_connector_continuity_residual,
    'maximum_entrance_continuity_residual': candidate.maximum_entrance_continuity_residual,
    'maximum_entropy_advection_residual': candidate.maximum_entropy_advection_residual,
    'maximum_entrance_entropy_advection_residual': candidate.maximum_entrance_entropy_advection_residual,
    'maximum_transverse_momentum_residual': candidate.maximum_transverse_momentum_residual,
    'maximum_conservative_mass_residual': (
      candidate.maximum_conservative_mass_residual
    ),
    'maximum_conservative_streamwise_momentum_residual': (
      candidate.maximum_conservative_streamwise_momentum_residual
    ),
    'maximum_conservative_transverse_momentum_residual': (
      candidate.maximum_conservative_transverse_momentum_residual
    ),
    'maximum_conservative_energy_residual': (
      candidate.maximum_conservative_energy_residual
    ),
    'maximum_conservative_euler_residual': (
      candidate.maximum_conservative_euler_residual
    ),
    'conservative_euler_residuals_measured': True,
    'maximum_mass_flow_residual': candidate.maximum_mass_flow_residual,
    'maximum_entrance_mass_flow_residual': candidate.maximum_entrance_mass_flow_residual,
    'maximum_control_source_pressure_residual_Pa': max(input_pressure_residuals, default=0.0),
    'maximum_control_source_gamma_residual': max(input_gamma_residuals, default=0.0),
    'maximum_inlet_angle_law_residual_rad': angle_residual,
    'source_streamline_mapping_verified': True,
    'entropy_transport_verified': candidate.maximum_entropy_advection_residual <= entropy_transport_tolerance,
    'continuity_verified': (
      candidate.maximum_continuity_residual <= continuity_tolerance
      and candidate.maximum_connector_continuity_residual
      <= 10.0 * continuity_tolerance
    ),
    'free_boundary_condition_verified': candidate.downstream_condition.converged,
    'field_topology_verified': candidate.field_topology_verified,
    'boundary': candidate.boundary,
    'downstream_condition': candidate.downstream_condition,
    'field': candidate.field,
  }
  if pressure_residual > pressure_tolerance * pressure_scale:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.FREE_BOUNDARY_FAILURE,
      request,
      control_section,
      control_validation,
      message=(
        'variable-entropy free-boundary iteration stopped before the ambient '
        f'pressure gate: residual={pressure_residual}, last_error={last_error}'
      ),
      **common_solution,
    )
  ####
  if not candidate.downstream_condition.converged:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.FREE_BOUNDARY_FAILURE,
      request,
      control_section,
      control_validation,
      message=(
        'variable-entropy free boundary did not pass its tangent/pressure '
        f'condition: {candidate.downstream_condition.message}'
      ),
      **common_solution,
    )
  ####
  if candidate.maximum_entropy_advection_residual > entropy_transport_tolerance:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.RESIDUAL_FAILURE,
      request,
      control_section,
      control_validation,
      message=(
        'mapped variable-entropy field did not meet its entropy-advection '
        f'residual tolerance: {candidate.maximum_entropy_advection_residual}'
      ),
      **common_solution,
    )
  ####
  if not common_solution['continuity_verified']:
    return _result(
      MocMixedRegimeVariableEntropyFreeBoundaryStatus.RESIDUAL_FAILURE,
      request,
      control_section,
      control_validation,
      message=(
        'mapped variable-entropy field did not meet its continuity '
        'residual tolerance: '
        f'downstream={candidate.maximum_continuity_residual}, '
        f'connector={candidate.maximum_connector_continuity_residual}'
      ),
      **common_solution,
    )
  ####
  return _result(
    MocMixedRegimeVariableEntropyFreeBoundaryStatus.CONVERGED_REFERENCE,
    request,
    control_section,
    control_validation,
    message=(
      'solver-owned streamline entropy transport, mapped continuity, '
      'ambient free-boundary pressure/tangency, and closed mesh topology '
      'passed; transverse 2-D Euler coupling and canonical promotion remain '
      'pending'
    ),
    **common_solution,
  )
####
