"""Public capability contracts and provider lifecycle for exhaust-plume products."""

from __future__ import annotations

from exhaust_plume.api.adapters import sectioned_tube_payload_from_axisymmetric_zones
from exhaust_plume.api.capabilities import (
    ENGINEERING_FLUX_SECTION_V1,
    IMAGE_SPECTRAL_RADIANCE_V1,
    OPTICAL_SPECTRAL_RAY_TRANSFER_V1,
    PRIMARY_CAPABILITY_IDS,
    SIGNATURE_SPECTRAL_RADIANT_INTENSITY_V1,
    SPATIAL_AXISYMMETRIC_ZONE_FIELD_V1,
    SPATIAL_LOCAL_FIELD_V1,
    SPATIAL_PROJECTED_AREA_V1,
    SPATIAL_SUPPORT_V1,
    SUPPORTING_CAPABILITY_IDS,
    VISUAL_SECTIONED_TUBE_V1,
)
from exhaust_plume.api.contracts import (
    Applicability,
    DerivationStep,
    FeatureAssociation,
    FeatureChannel,
    FidelityClaim,
    FrameRef,
    ItemStatus,
    ModelFidelity,
    PlumeFluxSection,
    PlumeFluxSectionResult,
    Pose3,
    ProductResult,
    Provenance,
    ResultEnvelope,
    ResultStatus,
    SectionedTubePayload,
    SectionedTubeResult,
    SnapshotRequest,
    SpeciesMassFlow,
    SpectralRadiantIntensityPayload,
    SpectralRadiantIntensityResult,
    SpectralRayTransferPayload,
    SpectralRayTransferResult,
    StrictFrozenModel,
    SupportDefinition,
    TimeAccessPolicy,
    TubeSection,
    ValidationLevel,
    calculate_content_sha256,
)
from exhaust_plume.api.errors import PlumeApiError, PlumeErrorCode
from exhaust_plume.api.lifecycle import (
    CapabilityAdvertisement,
    PlumeProvider,
    PlumeSession,
    PlumeSnapshot,
    ProductRequest,
    ProviderDescriptor,
)
from exhaust_plume.api.prescribed import (
    PrescribedSectionedTubeProvider,
    PrescribedSectionedTubeSession,
    PrescribedSectionedTubeSnapshot,
)

__all__ = (
    'ENGINEERING_FLUX_SECTION_V1',
    'IMAGE_SPECTRAL_RADIANCE_V1',
    'OPTICAL_SPECTRAL_RAY_TRANSFER_V1',
    'PRIMARY_CAPABILITY_IDS',
    'SIGNATURE_SPECTRAL_RADIANT_INTENSITY_V1',
    'SPATIAL_AXISYMMETRIC_ZONE_FIELD_V1',
    'SPATIAL_LOCAL_FIELD_V1',
    'SPATIAL_PROJECTED_AREA_V1',
    'SPATIAL_SUPPORT_V1',
    'SUPPORTING_CAPABILITY_IDS',
    'VISUAL_SECTIONED_TUBE_V1',
    'Applicability',
    'CapabilityAdvertisement',
    'DerivationStep',
    'FeatureAssociation',
    'FeatureChannel',
    'FidelityClaim',
    'FrameRef',
    'ItemStatus',
    'ModelFidelity',
    'PlumeApiError',
    'PlumeErrorCode',
    'PlumeFluxSection',
    'PlumeFluxSectionResult',
    'PlumeProvider',
    'PlumeSession',
    'PlumeSnapshot',
    'Pose3',
    'PrescribedSectionedTubeProvider',
    'PrescribedSectionedTubeSession',
    'PrescribedSectionedTubeSnapshot',
    'ProductRequest',
    'ProductResult',
    'Provenance',
    'ProviderDescriptor',
    'ResultEnvelope',
    'ResultStatus',
    'SectionedTubePayload',
    'SectionedTubeResult',
    'SnapshotRequest',
    'SpeciesMassFlow',
    'SpectralRadiantIntensityPayload',
    'SpectralRadiantIntensityResult',
    'SpectralRayTransferPayload',
    'SpectralRayTransferResult',
    'StrictFrozenModel',
    'SupportDefinition',
    'TimeAccessPolicy',
    'TubeSection',
    'ValidationLevel',
    'calculate_content_sha256',
    'sectioned_tube_payload_from_axisymmetric_zones',
)
