"""Versioned capability identities for public exhaust-plume products."""

from __future__ import annotations

from exhaust_plume.contracts.capability import (
    CANONICAL_CAPABILITY_IDENTITIES,
    CANONICAL_CAPABILITY_REGISTRY,
    PRIMARY_CAPABILITY_IDENTITIES,
    SUPPORTING_CAPABILITY_IDENTITIES,
)

VISUAL_SECTIONED_TUBE_V1 = PRIMARY_CAPABILITY_IDENTITIES[0].wire_id
SIGNATURE_SPECTRAL_RADIANT_INTENSITY_V1 = PRIMARY_CAPABILITY_IDENTITIES[1].wire_id
OPTICAL_SPECTRAL_RAY_TRANSFER_V1 = PRIMARY_CAPABILITY_IDENTITIES[2].wire_id

ENGINEERING_FLUX_SECTION_V1 = SUPPORTING_CAPABILITY_IDENTITIES[0].wire_id
SPATIAL_SUPPORT_V1 = SUPPORTING_CAPABILITY_IDENTITIES[1].wire_id
SPATIAL_LOCAL_FIELD_V1 = SUPPORTING_CAPABILITY_IDENTITIES[2].wire_id
SPATIAL_AXISYMMETRIC_ZONE_FIELD_V1 = SUPPORTING_CAPABILITY_IDENTITIES[3].wire_id
SPATIAL_PROJECTED_AREA_V1 = SUPPORTING_CAPABILITY_IDENTITIES[4].wire_id
IMAGE_SPECTRAL_RADIANCE_V1 = SUPPORTING_CAPABILITY_IDENTITIES[5].wire_id

PRIMARY_CAPABILITY_IDS = (
    VISUAL_SECTIONED_TUBE_V1,
    SIGNATURE_SPECTRAL_RADIANT_INTENSITY_V1,
    OPTICAL_SPECTRAL_RAY_TRANSFER_V1,
)

SUPPORTING_CAPABILITY_IDS = (
    ENGINEERING_FLUX_SECTION_V1,
    SPATIAL_SUPPORT_V1,
    SPATIAL_LOCAL_FIELD_V1,
    SPATIAL_AXISYMMETRIC_ZONE_FIELD_V1,
    SPATIAL_PROJECTED_AREA_V1,
    IMAGE_SPECTRAL_RADIANCE_V1,
)

__all__ = (
    'CANONICAL_CAPABILITY_IDENTITIES',
    'CANONICAL_CAPABILITY_REGISTRY',
    'ENGINEERING_FLUX_SECTION_V1',
    'IMAGE_SPECTRAL_RADIANCE_V1',
    'OPTICAL_SPECTRAL_RAY_TRANSFER_V1',
    'PRIMARY_CAPABILITY_IDS',
    'SIGNATURE_SPECTRAL_RADIANT_INTENSITY_V1',
    'SPATIAL_AXISYMMETRIC_ZONE_FIELD_V1',
    'SPATIAL_LOCAL_FIELD_V1',
    'SPATIAL_PROJECTED_AREA_V1',
    'SPATIAL_SUPPORT_V1',
    'SUPPORTING_CAPABILITY_IDS',
    'VISUAL_SECTIONED_TUBE_V1',
)
####
