"""Public package interface for the exhaust-plume study model."""

from __future__ import annotations

from exhaust_plume.constants import MODULE_NAME, VERSION
from exhaust_plume.models.plume import (
    AmbientState,
    AmbientStateField,
    ConstantDensityFreeJetExactSolution,
    ConstantDensityMixtureThermodynamics,
    ConstantEntrainment,
    CurvedPlumeOptions,
    CurvedPlumeResult,
    CurvedPlumeSource,
    CurvedPlumeSourceTermModel,
    CurvedPlumeSourceTerms,
    CurvedPlumeStation,
    CurvedPlumeTermination,
    DevelopingShearForcedEntrainment,
    EngineParameters,
    EntrainmentModel,
    ExpansionFanState,
    FlowState,
    IdealGasMixtureThermodynamics,
    MixtureState,
    MixtureThermodynamics,
    ObliqueShockState,
    OrthogonalUniformCrossflowExactSolution,
    UniformAmbientField,
    ZeroCurvedPlumeSourceTermModel,
    ZoneCoordinates,
    ZoneResult,
    ZoneType,
    calcNozzleExitFlowState,
    calculateConstantDensityFreeJetExact,
    calculateOrthogonalUniformCrossflowExact,
    calculatePlumeZones,
    solveCurvedPlume,
)

__version__ = VERSION

__all__ = (
    'MODULE_NAME',
    'VERSION',
    '__version__',
    'AmbientState',
    'AmbientStateField',
    'ConstantDensityFreeJetExactSolution',
    'ConstantDensityMixtureThermodynamics',
    'ConstantEntrainment',
    'CurvedPlumeOptions',
    'CurvedPlumeResult',
    'CurvedPlumeSource',
    'CurvedPlumeSourceTermModel',
    'CurvedPlumeSourceTerms',
    'CurvedPlumeStation',
    'CurvedPlumeTermination',
    'DevelopingShearForcedEntrainment',
    'EngineParameters',
    'EntrainmentModel',
    'ExpansionFanState',
    'FlowState',
    'IdealGasMixtureThermodynamics',
    'MixtureState',
    'MixtureThermodynamics',
    'ObliqueShockState',
    'OrthogonalUniformCrossflowExactSolution',
    'UniformAmbientField',
    'ZeroCurvedPlumeSourceTermModel',
    'ZoneCoordinates',
    'ZoneResult',
    'ZoneType',
    'calcNozzleExitFlowState',
    'calculateConstantDensityFreeJetExact',
    'calculateOrthogonalUniformCrossflowExact',
    'calculatePlumeZones',
    'solveCurvedPlume',
)
