"""Public package interface for the exhaust-plume study model."""

from __future__ import annotations

from exhaust_plume.constants import MODULE_NAME, VERSION
from exhaust_plume.models.plume import (
    ActuatorDiskWakeField,
    AmbientState,
    AmbientStateField,
    AmbientVelocityField,
    CompositeVelocityField,
    ConstantDensityFreeJetExactSolution,
    ConstantDensityMixtureThermodynamics,
    ConstantEntrainment,
    CurvedPlumeOptions,
    CurvedPlumeResult,
    CurvedPlumeSource,
    CurvedPlumeSourceTermModel,
    CurvedPlumeSourceTerms,
    CurvedPlumeStation,
    CurvedPlumeTermination,
    DevelopingShearForcedEntrainment,
    EngineParameters,
    EntrainmentModel,
    ExpansionFanState,
    FlowState,
    IdealGasMixtureThermodynamics,
    MixtureState,
    MixtureThermodynamics,
    ObliqueShockState,
    OrthogonalUniformCrossflowExactSolution,
    SweptTubeMesh,
    UniformAmbientField,
    UniformVelocityField,
    VelocityAugmentedAmbientField,
    ZeroCurvedPlumeSourceTermModel,
    ZoneCoordinates,
    ZoneResult,
    ZoneType,
    calcNozzleExitFlowState,
    calculateConstantDensityFreeJetExact,
    calculateOrthogonalUniformCrossflowExact,
    calculatePlumeZones,
    calculateRotationMinimizingFrames,
    generateCurvedPlumeMesh,
    generateSweptTubeMesh,
    solveCurvedPlume,
)

__version__ = VERSION

__all__ = (
    'MODULE_NAME',
    'VERSION',
    '__version__',
    'ActuatorDiskWakeField',
    'AmbientState',
    'AmbientStateField',
    'AmbientVelocityField',
    'CompositeVelocityField',
    'ConstantDensityFreeJetExactSolution',
    'ConstantDensityMixtureThermodynamics',
    'ConstantEntrainment',
    'CurvedPlumeOptions',
    'CurvedPlumeResult',
    'CurvedPlumeSource',
    'CurvedPlumeSourceTermModel',
    'CurvedPlumeSourceTerms',
    'CurvedPlumeStation',
    'CurvedPlumeTermination',
    'DevelopingShearForcedEntrainment',
    'EngineParameters',
    'EntrainmentModel',
    'ExpansionFanState',
    'FlowState',
    'IdealGasMixtureThermodynamics',
    'MixtureState',
    'MixtureThermodynamics',
    'ObliqueShockState',
    'OrthogonalUniformCrossflowExactSolution',
    'SweptTubeMesh',
    'UniformAmbientField',
    'UniformVelocityField',
    'VelocityAugmentedAmbientField',
    'ZeroCurvedPlumeSourceTermModel',
    'ZoneCoordinates',
    'ZoneResult',
    'ZoneType',
    'calcNozzleExitFlowState',
    'calculateConstantDensityFreeJetExact',
    'calculateOrthogonalUniformCrossflowExact',
    'calculatePlumeZones',
    'calculateRotationMinimizingFrames',
    'generateCurvedPlumeMesh',
    'generateSweptTubeMesh',
    'solveCurvedPlume',
)
