"""Typed provider and consumer contracts for plume products."""

from __future__ import annotations

from exhaust_plume.contracts.capability import (
  CAPABILITY_MAJOR_VERSIONS,
  CANONICAL_CAPABILITY_IDENTITIES,
  CANONICAL_CAPABILITY_REGISTRY,
  CapabilityId,
  ENGINEERING_FLUX_SECTION_CAPABILITY,
  IMAGE_SPECTRAL_RADIANCE_CAPABILITY,
  PRIMARY_CAPABILITY_IDENTITIES,
  SIGNATURE_SPECTRAL_RADIANT_INTENSITY_CAPABILITY,
  SPATIAL_AXISYMMETRIC_ZONE_FIELD_CAPABILITY,
  SPATIAL_LOCAL_FIELD_CAPABILITY,
  SPATIAL_PROJECTED_AREA_CAPABILITY,
  SPATIAL_SUPPORT_CAPABILITY,
  SPECTRAL_RAY_TRANSFER_CAPABILITY,
  SUPPORTING_CAPABILITY_IDENTITIES,
  VISUAL_SECTIONED_TUBE_CAPABILITY,
)
from exhaust_plume.contracts.descriptor import (
    PlumeMorphology,
    PlumeProviderDescriptor,
    ProviderApplicability,
    ProviderFidelity,
)
from exhaust_plume.contracts.errors import (
  AngularDomainError,
  CapabilityVersionMismatchError,
  ContractViolationError,
  InvalidProductRequestError,
  OperatingStateDomainError,
  ProductOutsideApplicabilityError,
  ProductSnapshotExpiredError,
  PublicContractError,
  ProviderClosedError,
  ProviderConfigurationError,
  ProviderError,
  SnapshotInvalidatedError,
  SpatialDomainError,
  SpectralDomainError,
  TemporalDomainError,
  UnsupportedProductCapabilityError,
  UnsupportedProductVersionError,
  UnsupportedCapabilityError,
)
from exhaust_plume.contracts.execution import (
    ConcurrencyMode,
    ProviderExecutionProfile,
    SnapshotRetention,
    TimeAccessMode,
)
from exhaust_plume.contracts.handoff import PlumeFluxSection
from exhaust_plume.contracts.provenance import PlumeProvenance
from exhaust_plume.contracts.common_v1 import (
  ApiError,
  ApiModel,
  ApplicabilityReport,
  ApplicabilityStatus,
  CapabilityIdentity,
  ConsistencyLevel,
  Derivation,
  ErrorCode,
  GeometryClaim,
  Pose,
  ProductClaims,
  ProviderDescriptor,
  RadiationClaim,
  ResultMetadata,
  ResultProvenance,
  SampleStatus,
  SampleStatusCode,
  SessionMetadata,
  SnapshotMetadata,
  TimeModel,
  Vector3,
  canonical_digest,
)
from exhaust_plume.contracts.conformance_v1 import (
  VisualProviderConformanceReport,
  run_visual_provider_conformance,
)
from exhaust_plume.contracts.lifecycle_v1 import (
  CapabilityEvaluator,
  CapabilitySpec,
  ImmutableProductSnapshot,
  ProductProvider,
  ProductSession,
  ProductSnapshot,
)
from exhaust_plume.contracts.ray_transfer_v1 import (
  SpectralRayTransferRequest,
  SpectralRayTransferResult as VersionedSpectralRayTransferResult,
)
from exhaust_plume.contracts.radiometry import (
  DirectionalSpectralIntensityQuery,
  DirectionalSpectralIntensityResult,
  SpectralRayTransferQuery,
  SpectralRayTransferResult,
)
from exhaust_plume.contracts.signature_v1 import (
  SPECTRAL_RADIANT_INTENSITY_CAPABILITY,
  SpectralSignatureRequest,
  SpectralSignatureResult,
)
from exhaust_plume.contracts.schema_v1 import PUBLIC_CONTRACT_MODELS, export_public_schemas
from exhaust_plume.contracts.specs_v1 import (
  PRIMARY_PRODUCT_CAPABILITY_SPECS,
  SPECTRAL_RADIANT_INTENSITY_V1,
  SPECTRAL_RAY_TRANSFER_V1,
  VISUAL_SECTIONED_TUBE_V1,
  get_product_capability_spec,
)
from exhaust_plume.contracts.termination import TerminationReason, TerminationReport
from exhaust_plume.contracts.snapshot import (
    PlumeCapability,
    PlumeProvider,
    PlumeSession,
    PlumeSnapshot,
)
from exhaust_plume.contracts.spatial import AxisymmetricZone, AxisymmetricZoneField, ProjectedAreaCapability, SpatialSupport
from exhaust_plume.contracts.visual_v1 import (
  LodProfile,
  VisualBounds,
  VisualChannelId,
  VisualSampling,
  VisualSection,
  VisualSectionedTubeRequest,
  VisualSectionedTubeResult,
  VisualTubeRequest,
  VisualTubeResult,
  VisualTubeSection,
  VisualTubeSummary,
)

__all__ = (
  'AngularDomainError',
  'ApiError',
  'ApiModel',
  'AxisymmetricZone',
  'AxisymmetricZoneField',
  'ApplicabilityReport',
  'ApplicabilityStatus',
  'CAPABILITY_MAJOR_VERSIONS',
  'CANONICAL_CAPABILITY_IDENTITIES',
  'CANONICAL_CAPABILITY_REGISTRY',
  'CapabilityId',
  'CapabilityIdentity',
  'CapabilityEvaluator',
  'CapabilitySpec',
  'CapabilityVersionMismatchError',
  'ConcurrencyMode',
  'ConsistencyLevel',
  'ContractViolationError',
  'Derivation',
  'ENGINEERING_FLUX_SECTION_CAPABILITY',
  'DirectionalSpectralIntensityQuery',
  'DirectionalSpectralIntensityResult',
  'ErrorCode',
  'GeometryClaim',
  'IMAGE_SPECTRAL_RADIANCE_CAPABILITY',
  'ImmutableProductSnapshot',
  'InvalidProductRequestError',
  'LodProfile',
  'OperatingStateDomainError',
  'PlumeCapability',
    'PlumeMorphology',
    'PlumeFluxSection',
    'PlumeProvider',
    'PlumeProviderDescriptor',
    'PlumeProvenance',
    'PlumeSession',
    'PlumeSnapshot',
  'ProviderApplicability',
  'ProviderClosedError',
  'ProviderConfigurationError',
  'ProviderError',
  'ProviderExecutionProfile',
  'ProviderFidelity',
  'ProviderDescriptor',
  'ProductOutsideApplicabilityError',
  'ProductProvider',
  'ProductSession',
  'ProductSnapshot',
  'ProductSnapshotExpiredError',
  'ProductClaims',
  'PRIMARY_PRODUCT_CAPABILITY_SPECS',
  'PRIMARY_CAPABILITY_IDENTITIES',
  'PublicContractError',
  'ProjectedAreaCapability',
  'PUBLIC_CONTRACT_MODELS',
  'Pose',
  'RadiationClaim',
  'ResultMetadata',
  'ResultProvenance',
  'SampleStatus',
  'SampleStatusCode',
  'SessionMetadata',
  'SnapshotMetadata',
  'SnapshotInvalidatedError',
  'SnapshotRetention',
  'SpatialDomainError',
  'SpatialSupport',
  'SPECTRAL_RADIANT_INTENSITY_CAPABILITY',
  'SIGNATURE_SPECTRAL_RADIANT_INTENSITY_CAPABILITY',
  'SPECTRAL_RADIANT_INTENSITY_V1',
  'SPECTRAL_RAY_TRANSFER_CAPABILITY',
  'SPECTRAL_RAY_TRANSFER_V1',
  'SpectralDomainError',
  'SpectralSignatureRequest',
  'SpectralSignatureResult',
  'SpectralRayTransferQuery',
  'SpectralRayTransferResult',
  'SpectralRayTransferRequest',
  'VersionedSpectralRayTransferResult',
  'TemporalDomainError',
  'TerminationReason',
  'TerminationReport',
  'TimeModel',
  'TimeAccessMode',
  'UnsupportedCapabilityError',
  'UnsupportedProductCapabilityError',
  'UnsupportedProductVersionError',
  'Vector3',
  'VISUAL_SECTIONED_TUBE_CAPABILITY',
  'VISUAL_SECTIONED_TUBE_V1',
  'VisualBounds',
  'VisualChannelId',
  'VisualSampling',
  'VisualSection',
  'VisualSectionedTubeRequest',
  'VisualSectionedTubeResult',
  'VisualTubeRequest',
  'VisualTubeResult',
  'VisualTubeSection',
  'VisualTubeSummary',
  'SPATIAL_AXISYMMETRIC_ZONE_FIELD_CAPABILITY',
  'SPATIAL_LOCAL_FIELD_CAPABILITY',
  'SPATIAL_PROJECTED_AREA_CAPABILITY',
  'SPATIAL_SUPPORT_CAPABILITY',
  'SUPPORTING_CAPABILITY_IDENTITIES',
  'VisualProviderConformanceReport',
  'run_visual_provider_conformance',
  'canonical_digest',
  'export_public_schemas',
  'get_product_capability_spec',
)
