"""Core plume models and their flow-state result types."""

from __future__ import annotations

from exhaust_plume.models.plume.curved_plume import (
    ActuatorDiskWakeField,
    AmbientState,
    AmbientStateField,
    AmbientVelocityField,
    CompositeVelocityField,
    ConstantDensityFreeJetExactSolution,
    ConstantDensityMixtureThermodynamics,
    ConstantEntrainment,
    CurvedPlumeOptions,
    CurvedPlumeResult,
    CurvedPlumeSource,
    CurvedPlumeSourceTermModel,
    CurvedPlumeSourceTerms,
    CurvedPlumeStation,
    CurvedPlumeTermination,
    DevelopingShearForcedEntrainment,
    EntrainmentModel,
    IdealGasMixtureThermodynamics,
    MixtureState,
    MixtureThermodynamics,
    OrthogonalUniformCrossflowExactSolution,
    UniformAmbientField,
    UniformVelocityField,
    VelocityAugmentedAmbientField,
    ZeroCurvedPlumeSourceTermModel,
    calculateConstantDensityFreeJetExact,
    calculateOrthogonalUniformCrossflowExact,
    solveCurvedPlume,
)
from exhaust_plume.models.plume.motor_parameters import EngineParameters
from exhaust_plume.models.plume.plume_solve import (
    ZoneCoordinates,
    ZoneResult,
    ZoneType,
    calcNozzleExitFlowState,
    calculatePlumeZones,
)
from exhaust_plume.util.aero.expansion_fan import ExpansionFanState
from exhaust_plume.util.aero.flow_state import FlowState
from exhaust_plume.util.aero.oblique_shock import ObliqueShockState

__all__ = (
    'ActuatorDiskWakeField',
    'AmbientState',
    'AmbientStateField',
    'AmbientVelocityField',
    'CompositeVelocityField',
    'ConstantDensityFreeJetExactSolution',
    'ConstantDensityMixtureThermodynamics',
    'ConstantEntrainment',
    'CurvedPlumeOptions',
    'CurvedPlumeResult',
    'CurvedPlumeSource',
    'CurvedPlumeSourceTermModel',
    'CurvedPlumeSourceTerms',
    'CurvedPlumeStation',
    'CurvedPlumeTermination',
    'DevelopingShearForcedEntrainment',
    'EngineParameters',
    'EntrainmentModel',
    'ExpansionFanState',
    'FlowState',
    'IdealGasMixtureThermodynamics',
    'MixtureState',
    'MixtureThermodynamics',
    'ObliqueShockState',
    'OrthogonalUniformCrossflowExactSolution',
    'UniformAmbientField',
    'UniformVelocityField',
    'VelocityAugmentedAmbientField',
    'ZeroCurvedPlumeSourceTermModel',
    'ZoneCoordinates',
    'ZoneResult',
    'ZoneType',
    'calcNozzleExitFlowState',
    'calculateConstantDensityFreeJetExact',
    'calculateOrthogonalUniformCrossflowExact',
    'calculatePlumeZones',
    'solveCurvedPlume',
)
