"""Focused 3-D geometry helpers for visualizing calculated plume zones."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional, Sequence

import numpy as np
from numpy import ndarray


@dataclass(frozen=True)
class RevolvedMesh:
  """A triangular surface generated by revolving a 2-D zone boundary."""

  vertices: ndarray
  faces: ndarray

  def __post_init__(self) -> None:
    vertices = np.asarray(self.vertices, dtype=float)
    faces = np.asarray(self.faces, dtype=int)
    if vertices.ndim != 2 or vertices.shape[1] != 3:
      raise ValueError(f'Expected vertices to have shape (N, 3), got {vertices.shape}.')
    ####
    if faces.ndim != 2 or faces.shape[1] != 3:
      raise ValueError(f'Expected faces to have shape (N, 3), got {faces.shape}.')
    ####
    if faces.size and (np.min(faces) < 0 or np.max(faces) >= len(vertices)):
      raise ValueError('Mesh faces contain an invalid vertex index.')
    ####
    vertices.flags.writeable = False
    faces.flags.writeable = False
    object.__setattr__(self, 'vertices', vertices)
    object.__setattr__(self, 'faces', faces)
  ####

  @property
  def min(self) -> ndarray:
    return self.vertices.min(axis=0)
  ####

  @property
  def max(self) -> ndarray:
    return self.vertices.max(axis=0)
  ####
####


def _rotation_matrix(axis: ndarray, angle_rad: float) -> ndarray:
  x, y, z = axis
  c = np.cos(angle_rad)
  s = np.sin(angle_rad)
  one_minus_c = 1.0 - c
  return np.asarray((
      (c + x * x * one_minus_c, x * y * one_minus_c - z * s, x * z * one_minus_c + y * s),
      (y * x * one_minus_c + z * s, c + y * y * one_minus_c, y * z * one_minus_c - x * s),
      (z * x * one_minus_c - y * s, z * y * one_minus_c + x * s, c + z * z * one_minus_c),
  ))
####


def generateRevolvedMesh(points: ndarray, axis: ndarray, num_rotations: int) -> RevolvedMesh:
  """Revolve a closed 2-D boundary around a 3-D axis."""
  points = np.asarray(points, dtype=float)
  axis = np.asarray(axis, dtype=float)
  if points.ndim != 2 or points.shape[1] not in (2, 3):
    raise ValueError(f'Expected points to have shape (N, 2) or (N, 3), got {points.shape}.')
  ####
  if axis.shape != (3,):
    raise ValueError(f'Expected axis to have shape (3,), got {axis.shape}.')
  ####
  if len(points) < 2 or num_rotations < 3:
    raise ValueError('A revolved mesh needs at least two boundary points and three rotations.')
  ####
  axis_norm = np.linalg.norm(axis)
  if not np.isfinite(axis_norm) or axis_norm == 0.0:
    raise ValueError('The revolution axis must be finite and non-zero.')
  ####
  axis = axis / axis_norm
  if points.shape[1] == 2:
    points = np.column_stack((points, np.zeros(len(points))))
  ####

  rotations = [_rotation_matrix(axis, 2.0 * np.pi * index / num_rotations) for index in range(num_rotations)]
  vertices = np.vstack([points @ rotation.T for rotation in rotations])
  faces = []
  num_points = len(points)
  for strip in range(num_rotations):
    next_strip = (strip + 1) % num_rotations
    for point in range(num_points):
      next_point = (point + 1) % num_points
      i0 = strip * num_points + point
      i1 = strip * num_points + next_point
      i2 = next_strip * num_points + point
      i3 = next_strip * num_points + next_point
      faces.extend(((i0, i1, i2), (i1, i3, i2)))
    ####
  ####
  return RevolvedMesh(vertices=vertices, faces=np.asarray(faces, dtype=int))
####


def plotRevolvedMeshes(
    meshes: Sequence[RevolvedMesh],
    ax: Optional[Any] = None,
    face_colors: Optional[Sequence[Any]] = None,
    face_kwargs: Optional[dict[str, Any]] = None,
) -> tuple[Any, list[Any]]:
  """Plot revolved meshes with Matplotlib, importing it only for plot use."""
  if not meshes:
    raise ValueError('No meshes to plot.')
  ####
  from matplotlib import pyplot as plt
  from mpl_toolkits.mplot3d.art3d import Poly3DCollection

  if ax is None:
    ax = plt.gcf().add_subplot(111, projection='3d')
  ####
  colors = list(face_colors) if face_colors is not None else ['#DEDBEF'] * len(meshes)
  kwargs = {'edgecolor': 'black', 'alpha': 0.3, **(face_kwargs or {})}
  plotted = []
  # Right/up plume coordinates become right/forward/up display coordinates.
  display_matrix = np.asarray(((0.0, 1.0, 0.0), (1.0, 0.0, 0.0), (0.0, 0.0, -1.0)))
  display_vertices = [mesh.vertices @ display_matrix for mesh in meshes]
  all_vertices = np.vstack(display_vertices)
  for mesh, vertices, color in zip(meshes, display_vertices, colors):
    collection = Poly3DCollection(vertices[mesh.faces], facecolor=color, **kwargs)
    ax.add_collection3d(collection)
    plotted.append(collection)
  ####
  lower = all_vertices.min(axis=0)
  upper = all_vertices.max(axis=0)
  center = (lower + upper) / 2.0
  extent = max(float(np.max(upper - lower)), 1.0) * 0.6
  ax.set_xlim(center[0] - extent, center[0] + extent)
  ax.set_ylim(center[1] - extent, center[1] + extent)
  ax.set_zlim(center[2] - extent, center[2] + extent)
  ax.set_xlabel('Right')
  ax.set_ylabel('Forward')
  ax.set_zlabel('Up')
  ax.set_box_aspect((1.0, 1.0, 1.0))
  return ax, plotted
####
